### ISSUE TITLE
Silently skip XML tests if Java not installed?

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#103]
The XML writing tests all fail if there's no Java installed (and in addition, at least on my Mac, every test cycle now pops up a dialog box asking if I want to go install Java). Is this the behavior we want, i.e. to force folks to install Java? Or would we rather have the tests not execute, or at least not fail, if Java is not installed? Not sure.

**Comment by bpbond** [comment]
>Currently the tests for the CSV to XML pipeline utilities are disabled since they fail if a user does not have Java installed. We could add some sort of global option that disables the tests and calling Java in run_xml_conversion.

>Of course disabling those calls means no XML files will be generated. This is ok in the short term while we are building up the gcamdata chunks but in the long run we will probably need to have the XML files thus force people to install Java?

I think we'd always like to keep the _option_ of running the data system without Java. Maybe a global option `USE_JAVA` whose default is FALSE for now, but we'll change to TRUE later?

**Comment by pralitp** [comment]
Yup, I was thinking something similar.  It would be pretty easy.  Although I did notice in the tests you took out the calls to `skip`, was there a reason for that?  Otherwise I was thinking in the tests we start with:
```
if(!USE_JAVA) {
  skip("Requires Java to run this test")
}
```

**Comment by bpbond** [comment]
Only because `skip` prints a message, sullying my test screen. :)

**Comment by pralitp** [comment]
Do you have objections to me using `skip` as noted above?  It seems to be the designated way to handle this use case.

**Comment by bpbond** [comment]
I guess not. I just like the satisfaction of seeing all the tests pass cleanly. Rows of pretty dots...

**Comment by pralitp** [comment]
Should I issue a warning if someone calls `run_xml_conversion` with USE_JAVA=FALSE?

**Comment by bpbond** [comment]
Probably, the first time only?

**Comment by pralitp** [comment]
Is there an easy way to detect that or do I roll my own solution?

**Comment by bpbond** [comment]
Hmm. I guess the three ways to do this (warning first time only) would be [a closure](http://stackoverflow.com/questions/1088639/static-variables-in-r) or a package global that you change (`XML_WARNING_GIVEN <<- TRUE`).

We could also stick this on the to-do list for now. I'm fine with that.

**Comment by bpbond** [comment]
Let's handle `USE_JAVA` via R options mechanism I think?

**Comment by bpbond** [comment]
If that sounds good, I'd suggest create a new file `onload.R` with the following code:

```
.onLoad <- function(libname, pkgname) {
  op <- options()
  op.gcamdata <- list(
    gcamdata.use_java = TRUE
  )
  toset <- !(names(op.gcamdata) %in% names(op))
  if (any(toset)) {
    options(op.gcamdata[toset])
  }
  invisible()
}
```

Then your code can check `getOptions("gcamdata.use_java")` for behavior to follow.

**Comment by pralitp** [comment]
Thanks! much more advanced than I was thinking.

**Comment by bpbond** [comment]
No problem. To be safe, checking code should say `if(isTRUE(getOptions("gcamdata.use_java")))`

**Comment by pralitp** [comment]
Thanks Ben!  I ended up going the closure route for `XML_WARNING_GIVEN` since otherwise I was running into this:
https://www.r-bloggers.com/package-wide-variablescache-in-r-packages/

The closure seemed to be the cleanest solution in the end.

One last question.  Is there some way to set `options(gcamdata.use_java=TRUE)` before travis(?) kicks off the tests?  Might as well get the fullest automated checking even if a user won't need the functionality.

**Comment by bpbond** [comment]
OK, cool. So the `.onLoad` function will execute when the package is loaded, before the tests run; you can modify it anytime within test code simply by `options(gcamdata.use_java = FALSE)`
