### ISSUE TITLE
Regional aggregation prior to basin downscaling of agricultural data causes distortions

### ISSUE THREAD

**Issue by pkyle** [JGCRI/gcamdata#1048]
This is a pointer for an issue documented in [Jira Issue 319](https://jira.pnnl.gov/jira/browse/JGCRI-319), also decribed here. The main datasets used for estimating historical agricultural production and harvested area by GCAM region, basin, and year are FAOSTAT (1971-2010 production and harvested area by crop and country) and the Monfreda gridded inventory of production and harvested area by crop, around the year 2000. This dataset is aggregated to basin and country in our Land Data System (LDS), and is provided as an exogenous input to gcamdata. The current method in gcamdata first aggregates FAOSTAT countries to GCAM's 32 GCAM regions, then aggregates Monfreda/LDS to GCAM region and basin, and then uses the aggregated Monfreda/LDS dataset to downscale production from GCAM region to GCAM region and basin. This is a problematic sequence as it amplifies the distortions owing to the use of a single-year snapshot to perform the basin-level downscaling. A better sequence would be to perform the basin-level downscaling prior to aggregating by GCAM regions.

**Comment by russellhz** [comment]
This was completed in 943f6f8bad7da4da075f954d8659b87505026476 - 086782e98ae13d036f1146bb10fe0d55a8c793b2
