### ISSUE TITLE
Level 1 chunks shouldn't use MODEL_BASE_YEARS

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#1067]
See @pkyle 's comment:
https://stash.pnnl.gov/projects/JGCRI/repos/gcam-core/pull-requests/83/overview?commentId=12432

Check all other level 1s and make sure they don't either.

**Comment by pkyle** [comment]
And by "we", you mean you and your daughter? For fun, on a Sunday?

**Comment by bpbond** [comment]
See also #455
