### ISSUE TITLE
dplyr::funs deprecated

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#1092]
Caleb notes:
While we're at it, just learned about this one:

```
Warning message:
funs() is soft deprecated as of dplyr 0.8.0
please use list() instead
```

:weary:

**Comment by rplzzz** [comment]
The change is annoying, but honestly its only valid use was making anonymous functions using the `.` notation, and it looks like you can now do that by writing the anonymous function as a formula.

So, for example, this:
https://github.com/JGCRI/gcamdata/blob/9569f567f2ff26b94f727de57677a92b76854be8/R/zchunk_LA123.electricity.R#L59
could have been done with an ordinary list all along.

And this:
https://github.com/JGCRI/gcamdata/blob/7008318a40f6e3a9b2d84df2c7a15e580bab64c8/R/zchunk_L103.ghg_an_USA_S_T_Y.R#L56-L57
could be done as
```R
    dplyr::mutate_all( list( ~replace(., is.na(.), 0))) %>%
    dplyr::mutate_if(is.numeric, list( ~. * CONV_GG_TG))
```

So, I think this is an easy fix in our code, and on the plus side it removes from dplyr a misbegotten construct that maybe never should have existed in the first place.

**Comment by bpbond** [comment]
Agreed.
