### ISSUE TITLE
gcamdata fails to produce XML files

### ISSUE THREAD

**Issue by ssmithClimate** [JGCRI/gcamdata#1101]
The following:
library(gcamdata)
x <- driver(stop_after="module_climate_xml_batch_hector_xml")

Fails to write any XML files if the gcamdata folder in a directory path that contains spaces on OSX. (If put in a path with no spaces works as normal.)

No error message, but the following warning appears.

Warning message:
In run_xml_conversion(cd) :
  java.io.FileNotFoundException: /Users/D3K117/GCAM%20E-M-India/input/gcamdata/xml/hector.xml (No such file or directory)	at java.base/java.io.FileOutputStream.open0(Native Method)	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:292)	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:185)	at java.xml/com.sun.org.apache.xml.internal.serializer.dom3.LSSerializerImpl.writeToURI(LSSerializerImpl.java:1221)	at ModelInterface.ModelGUI2.csvconv.CSVToXMLMain.writeFile(CSVToXMLMain.java:320)	at ModelInterface.ModelGUI2.csvconv.CSVToXMLMain.main(CSVToXMLMain.java:92)Error outputing tree: org.w3c.dom.ls.LSException: java.io.FileNotFoundException: /Users/D3K117/GCAM%20E-M-India/input/gcamdata/xml/hector.xml (No such file or directory)

**Comment by bpbond** [comment]
Haven’t looked at code but it sounds like `run_xml_comversion()` needs to escape a path string it’s sending to java.

**Comment by ssmithClimate** [comment]
@pralitp should I post the fixed .jar here and close the issue?

**Comment by pralitp** [comment]
Github doesn't allow `.jar` files.  But also I would rather just commit the fix and close once merged.  I'll take care of that shortly.

**Comment by amnmalik** [comment]
I am facing the same issue. Both driver() and driver_drake() run but produce empty (0 KB) XML files. When I type in warnings() I get:
Warning messages:

1: In run_xml_conversion(cd) :
  intValueStr nullException thrown while trying to read csv and header files: java.io.FileNotFoundException: java.io.FileNotFoundException: 	at java.io.FileInputStream.open0(Native Method)	at java.io.FileInputStream.open(Unknown Source)	at java.io.FileInputStream.<init>(Unknown Source)	at ModelInterface.ModelGUI2.csvconv.CSVToXMLMain.runCSVConversion(CSVToXMLMain.java:136)	at ModelInterface.ModelGUI2.csvconv.CSVToXMLMain.main(CSVToXMLMain.java:92)
