### ISSUE TITLE
aglu_LB162.ag_prodchange_R_C_Y_GLU_irr does not finish

### ISSUE THREAD

**Issue by felipefeijoo** [JGCRI/gcamdata#1121]
I am running the gcam data system on Linux. All works fine until  I get to the chunk "module_ag_prodchange_R_C_Y_GLU_irr".

The data system stays in this chunk for long time and does not finish. I have waited for at least 40 min and it never ends, and does not provide any error messages. 

![Capture](https://user-images.githubusercontent.com/7244854/60545832-03b53b80-9cea-11e9-8c9e-c18411a05809.PNG)

**Comment by bpbond** [comment]
Can you provide your `sessionInfo()` output please @felipefeijoo ?

**Comment by felipefeijoo** [comment]
@bpbond, this is the output, thanks

![image](https://user-images.githubusercontent.com/7244854/60602513-f3e93600-9d81-11e9-88d5-be03c97060f3.png)

**Comment by bpbond** [comment]
Thanks to detective work by @pralitp...

This seems to be due to a regression in the underlying `dplyr` library, specifically version 0.8.2 - see https://www.tidyverse.org/articles/2019/07/dplyr-0-8-3/. You should be able to update to 0.8.3 and this problem will go away.
