### ISSUE TITLE
ag_trade.xml not being produced

### ISSUE THREAD

**Issue by vsrikrish** [JGCRI/gcamdata#1125]
The current GCAM version on github wants an ag_trade.xml (in configuration_ref.xml), but the master gcamdata branch and default workflow doesn't produce this file.

**Comment by pralitp** [comment]
The version of GCAM you are using includes changes that have not yet been synchronized with this repository.

In general users should not assume that XMLs built from a `gcamdata` which was not included with their version of GCAM is compatible.

You should use in your local copy of GCAM the version in `input/gcamdata`.

If there are features specific to the version on this repository then they will be compatible with the GCAM `5.1.3` release.
