### ISSUE TITLE
Fast pipe?

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#1139]
Given the sheer number of pipes in `gcamdata`

```
gcamdata$ grep -cr '%>%' ./R | cut -d : -f 2 | paste -s -d+  - | bc
18857
```
...seems like this new 'fast pipe' might be worth testing!

https://github.com/moodymudskipper/fastpipe

h/t @ashiklom

**Comment by russellhz** [comment]
I tried this and the normal pipe `%>%` is not consistently faster with fastpipe. The "bare pipe" `%>>%` is noticeably faster but requires substantial code re-writing (`%>>% select(., year)` instead of `%>% select(year)`)
