### ISSUE TITLE
Query regarding input files for industry sector

### ISSUE THREAD

**Issue by ankurmalyan** [JGCRI/gcamdata#1141]
Hi,

I have been looking at the industrial sector of the GCAM model version 4.3. I have following queries regarding that:

1. The non-energy cost in the global tech cost for the industrial energy use for each fuel is considered **3 1975$/GJ**. What is the source behind this cost? Is there any equation that directs this estimation of the non-energy cost for the generalized industrial energy use?

2. Is there any detailed documentation available for the industrial sector of the model?

Thanks a lot. Look forward to a response.

**Comment by pkyle** [comment]
I'm sorry for the delay in responding to this question; unfortunately the answer is itself a bit complex, as would be expected for the industrial sector, the most heterogeneous of the end-use sectors in terms of how energy is used. The key measurement variables in evaluating scenario outcomes are the elasticities of substitution between the different fuels (i.e., the market share of the subsectors within "industrial energy use"), and the price elasticity of industrial output in general (the "industry" sector). The "non-energy" cost of 3 noted in the question is in the "industrial energy use" sector and pertains to the elasticity of substitution between fuels for energy purposes. The specific value chosen, in concert with the sector-level logit exponent, -3, influences the elasticity of substitution between different fuel choices; both of these parameters reflect what we believe to be reasonable assumptions for a sector that is very heterogeneous, consisting of some processes with a high degree of substitutability (e.g., producing steam), and others with a low degree (e.g., operating mining equipment). All else equal, a lower non-energy cost would lead to a higher elasticity of substutition between fuels, as would a higher (i.e. more negative) logit exponent. The enclosed core model proposal addresses the implementation of the non-energy cost in the "industry" sector, but nevertheless addresses some of these issues.
[JGCRI-241Includenon-energyinputcostforindustry-031219-2138-40.pdf](https://github.com/JGCRI/gcamdata/files/3920278/JGCRI-241Includenon-energyinputcostforindustry-031219-2138-40.pdf)
