### ISSUE TITLE
Problems Installing gcamdata on Windows

### ISSUE THREAD

**Issue by RawisWar** [JGCRI/gcamdata#1147]
Hi 
I am having trouble installing gcamdata on my PC. 
I followed the steps outlined in the Wiki 
But when I get the step of Build and Reload I can't find the option in my R studio. 
Thanks in advance. 

![image](https://user-images.githubusercontent.com/34580273/71724140-2b9e6c80-2dfd-11ea-9fc1-3b03b46869f1.png)

**Comment by bpbond** [comment]
It looks like RStudio has tweaked its menu wordings..."Install and Restart" (Ctrl+Shift+B) should do the same thing?

**Comment by pkyle** [comment]
From what I've seen RStudio call it "Install and Restart" for Windows, and "Build & Reload" for Mac. But it might also be a version thing; Hadley mentions it in section 13.7 here: https://r-pkgs.org/src.html
There's also some commentary there about "Load all" (Ctrl+Shift+L) compared with the full "Install and Restart". Load all is much faster.

**Comment by RawisWar** [comment]
Hi 
Thanks for the quick response. 
With the "Install and Restart" option looks like I can load "gcamdata" on my PC now. 
However, I am facing another challenge in creating XML files using gcamdata. 

I tried a simple run to check if it works by changing the name of "nuclear_adv" to "nuclear_adv2" in the chuck file. Then re-runned to generate data system. 

![image](https://user-images.githubusercontent.com/34580273/71729224-23e6c400-2e0d-11ea-82e0-5797df78ed8a.png)
 
However, after the run the nuclear_adv2.xml file wasn't generated.

Any help to solve this problem will be greatly appreciated.

**Comment by pkyle** [comment]
It looks like you still have a `nuclear_adv.xml` in that block of code that you sent. FWIW when you do a find and replace to change the name of the XML file being generated in one of the `zchunk_batch_*.R` files, there should be 6 instances where the replacement happens. It's super easy to miss one or two when replacing manually.
