### ISSUE TITLE
Creating an XML file using a batch of CSV files

### ISSUE THREAD

**Issue by RawisWar** [JGCRI/gcamdata#1157]
Hi 
I am trying to create an XML file using multiple CSVs. For example, I made **major** modifications to the following files :
             
**"L2321.FinalEnergyKeyword_cement_adv"
"L2321.SubsectorLogit_cement_adv"
"L2321.SubsectorShrwtFllt_cement_adv"
"L2321.SubsectorInterp_cement_adv"
"L2321.StubTech_cement_adv"
"L2321.GlobalTechShrwt_cement_adv"
"L2321.GlobalTechCoef_cement_adv"
"L2321.GlobalTechCost_cement_adv"
"L2321.GlobalTechCapture_cement_adv"
"L2321.StubTechProd_cement_adv"
"L2321.StubTechCalInput_cement_adv_heat"
"L2321.StubTechCoef_cement_adv"
"L2321.PerCapitaBased_cement_adv"
"L2321.BaseService_cement_adv"
"L2321.PriceElasticity_cement_adv"**

Does gcamdata have the capability of reading the modified CSV  directly and building the XML file?

Thanks in advance

**Comment by bpbond** [comment]
Sorry for the non-response on this issue. Would feedback on this still be useful?

**Comment by RawisWar** [comment]
@bpbond 
Thanks, I figured it out.

**Comment by panday1995** [comment]
Hi @RawisWar, Could you please explain about how to do that? I am also facing the problem with modifying the transnport sector data. Thanks!

**Comment by LZRGRAY** [comment]
> @bpbond Thanks, I figured it out.

Hi! I am having similar issues. Could you explain if/how xml files can be built using existing csv files?
