### ISSUE TITLE
Shift to GitHub Actions?

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#1159]
Interesting info about the benefits of GitHub actions over Travis and appveyor. Sounds compelling for the data system.
https://www.tidyverse.org/blog/2020/04/usethis-1-6-0/

Compared to Travis-CI, GitHub Actions:

* Provides more resources, i.e. 6 hour build times and 20 concurrent builds instead of 50 minute build times and ~5 concurrent builds.
* Has more complete support for building on Windows and macOS and a more natural way of using Docker containers.
* Doesn’t require any extra authentication because all code is run on GitHub.
* Is considerably easier to customise to provide workflows that we haven’t made easy.

**Comment by bpbond** [comment]
This has to happen sooner rather than later, now, as Travis is moving to an exclusively paid model.

**Comment by russellhz** [comment]
Completed in 60e226db2ff86b704d89b8843b749830dc8bb142
