### ISSUE TITLE
Error while building gcam datasystem on Windows

### ISSUE THREAD

**Issue by Silviameteoro** [JGCRI/gcamdata#1160]
Hi,

Could you please help me  with this error? 

I have made all package installations shown in:

https://github.com/JGCRI/gcamdata/wiki/Getting-Started

Then I navigated to the data system within the GCAM folder (input/gcamdata) and then opened the gcamdata.Rproj and then I tried "Install and Restart"

After this, a warning message saying that the Rtools package was missing appeared. Then I tried to install Rtools and a message saying that this was not available for R version 4.0.2 was raised.

Then I tried driver() already expecting that it would not work as happened...

Is there an alternative to work around this or should I try to downgrade to an earlier R version to have Rtools installed (I am assuming this is the cause of my problem)?

Thanks
![error_gcamdatasystem](https://user-images.githubusercontent.com/24659743/88707791-bec42a00-d0e0-11ea-8199-6daaf84635c1.png)

**Comment by pkyle** [comment]
Can you check which version of dplyr you're running? Just run
`sessionInfo()`
in your R console. That error looks like one that we get if we're running with dplyr 1.0+.

**Comment by Silviameteoro** [comment]
The version shown for dplyr is 1.0.0.

Thank you.

**Comment by pkyle** [comment]
Yeah I'd recommend reverting dplyr to 0.8.5. Here are some instructions: https://support.rstudio.com/hc/en-us/articles/219949047-Installing-older-versions-of-packages
We have developed a version of gcamdata that is compliant with dplyr 1.0+, but I'm not sure when it will be rolled out, and in any case the next few months will be easier to just keep dplyr as the older one.

**Comment by Silviameteoro** [comment]
Hi,

I reverted to dplyr 0.8.5 as suggested following instructions from the link provided. Then I opened the gcamdata.Rproj and tried "Install and Restart" again. This part went better than the first time since there was no warning messages. However when I ran the driver I got to an error again:

....
[1] "- make 0.22"
[1] "module_aglu_LB162.ag_prodchange_R_C_Y_GLU_irr"
Error in left_join_error_no_match(., L162.defaultYieldRate, by = c("year",  : 
  left_join_no_match: NA values in new data columns
In addition: Warning message:
 Error in left_join_error_no_match(., L162.defaultYieldRate, by = c("year",  : 
  left_join_no_match: NA values in new data columns 


Thanks for any advice.

**Comment by pkyle** [comment]
Interesting--I recall a similar error in the process of updating the base year from 2010 to 2015; I just noticed, in the `JGCRI/gcamdata` repo, the last commit is prior to the base year update. Whereas if you clone `JGCRI/gcam-core` and navigate to the `gcam-core/input/gcamdata` directory, that version of the gcamdata package has the base year update, and should run fine. I'm not sure exactly why you're getting this error in your current set-up, but there have been a lot of small changes dealing with tidyr and other package updates, and perhaps the `JGCRI/gcamdata` repo doesn't yet include all of them? Anyway if you can just switch which repo you're using this problem will go away.

**Comment by Silviameteoro** [comment]
Just an update, switching to JGCRI/gcam-core repo makes the driver runs fine.
