### ISSUE TITLE
Accelerating US coal power plant retirement via GCAM Data System

### ISSUE THREAD

**Issue by tsgsteele** [JGCRI/gcamdata#1164]
I'm wondering if there is a way to accelerate coal power plant retirement in the US via the GCAM data system. Each state and power plant vintage seems to have pre-set s-curve shutdown deciders. Is there any way to override these efficiently using the data system?

**Comment by russellhz** [comment]
Hi @tsgsteele, I'm very sorry for the delay in responding to this. Do you still need help on this issue? If so, I can transfer it to the gcam channel

**Comment by tsgsteele** [comment]
Hi,

I'm sorry for the delay, I do still need help with this issue if possible.

Thank you,

Talor

**Comment by pkyle** [comment]
The retirement function parameters are assigned in `inst/extdata/energy/A23.globaltech_retirement.csv`
Note that any changes there will apply to all regions; if you want for the coal-electric power plants to retire in the USA on an accelerated rate, but keep the global rates at their default values, then the process will be more complicated, particularly if this you're intending for this to be done in GCAM-USA.
