### ISSUE TITLE
The Generated XML files can't work with GCAM v5.2

### ISSUE THREAD

**Issue by heishanmao** [JGCRI/gcamdata#1166]
I just download gcamdata GCAM Data System Version 1.0 and build in Rstudio without any modified and get hundreds of  XML files as GCAM inputs.

But. when I copied all generated XML files to gcam V5.2 input\gcamdata.  After running gcam get some errors.
It seems that some XML files are missing.
![Screenshot 2021-02-09 183523](https://user-images.githubusercontent.com/16098881/107442755-97c1c880-6b05-11eb-9864-0ae5503d3a13.png)

just wonder to know, which version of GCAM can work with gcamdata (GCAM Data System Version 1.0)? V5.1? V5.2 or v5.1.1?

and also I noticed that the different number of XML files for each version.  215 for v5.2 .  219 for v5.1.3  217 for V5.1..
So. If I use gacamdata to produce XML files for GCAM V5.2 or others. Do I need to modify something rather than just copy it?

Thank you very much.

**Comment by atmos-project** [comment]
I think you can use the gcamdata.Rproj that comes with the GCAM v5.2 release. This should generate xmls compatible with GCAM v5.2.

**Comment by debibooo** [comment]
hello, I met the same problem as above. I used the gcamdata.Rproj that comes with the _GCAM v5.4_ release, but there were just 207 documents in XML after I run the _driver_, while the original gcam5.4 version includes 226 XMLs.  So I have tried run-gcam.bat to check if it still works with less XMLs, it showed errors happened. Should I only use it to generate alternative XMLs?

**Comment by russellhz** [comment]
@debibooo sorry for the delay - do you still need help on this issue?
