### ISSUE TITLE
Error when building gcamdata

### ISSUE THREAD

**Issue by joneill9** [JGCRI/gcamdata#1167]
I am able to build the GCAM data system, but got the following error when I run the driver: 

[1] "module_aglu_LA100.0_LDS_preprocessing"
Error: L100.Land_type_area_ha is being returned grouped. This is not allowed; please ungroup()

Any ideas what the issue is?

**Comment by joneill9** [comment]
Got this solved. Looking at other issues on here, I thought I'd try reverting to an older version of dplyr. I had issues installing it though, and ended up just restarting R, reinstalling the latest version of dplyr, and trying it again - and it worked this time around.

**Comment by bpbond** [comment]
Glad you get it resolved. Yes, `dplyr` version incompatibilities have been a persistent problem for the data system—good guess.
