### ISSUE TITLE
Error when first building GCAM data system

### ISSUE THREAD

**Issue by stm19950929** [JGCRI/gcamdata#1172]
Assigned data `min(MODEL_BASE_YEARS)` must be compatible with existing data.
Error occurred for column `logit.year.fillout`.
x Can't convert <double> to <character>.
Run `rlang::last_error()` to see where the error occurred.

**Comment by Sh1Yi** [comment]
@stm19950929 
Did you figure out how to solve this? I'm getting the same error.
Thank you very much.

**Comment by pkyle** [comment]
What version of the tibble package are you using? This might relate to a difference between the number of rows of a data table (generally >1) and the length of the vector being filled in (in this case, 1). From what I understand, vectors of length 1  are supposed to (silently) repeat by the number of rows of the data table with no error or even warning message, but it's possible that more recent versions of the package will require explicitly repeating the vector to fill the appropriate number of rows.

**Comment by Sh1Yi** [comment]
> library(gcamdata)
> driver(write_output=FALSE, write_xml=TRUE)
GCAM Data System v5.1
...
[1] "module_energy_L225.hydrogen"
Error: Assigned data `min(MODEL_BASE_YEARS)` must be compatible with existing data.
i Error occurred for column `logit.year.fillout`.
x Can't convert <double> to <character>.
Run `rlang::last_error()` to see where the error occurred.

R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7        tidyr_0.8.3       fansi_0.4.2       crayon_1.4.2      utf8_1.2.1        dplyr_0.8.5      
 [7] assertthat_0.2.1  R6_2.5.1          lifecycle_1.0.1   magrittr_2.0.1    pillar_1.6.4      cli_3.1.0        
[13] stringi_1.6.1     rlang_0.4.11      rstudioapi_0.13   data.table_1.12.0 vctrs_0.3.8       ellipsis_0.3.2   
[19] tools_3.6.0       readr_1.4.0       glue_1.6.0        purrr_0.3.4       hms_1.1.1         compiler_3.6.0   
[25] pkgconfig_2.0.3   tidyselect_1.1.1  tibble_3.1.1 

I tried downgrading tibble to 2.1.3. This error is gone, but a [new error](https://github.com/JGCRI/gcamdata/issues/1155) has appeared. Do i have to update gcamdata? I want to use GCAM v5.1.3.
Any help I will be greatly appreciated.

**Comment by Sh1Yi** [comment]
I downgraded tidyselect to 0.2.5, and then the [new error](https://github.com/JGCRI/gcamdata/issues/1155) had gone.
Now I can build GCAM data system sucessfully!

Thank you for your help!
