### ISSUE TITLE
Error in building data system for the first time

### ISSUE THREAD

**Issue by emmaliulu** [JGCRI/gcamdata#1177]
Here's what I did and what the error message says,

![image](https://user-images.githubusercontent.com/20967190/136714972-f268b411-313c-4128-b3cf-ced961d4405c.png)

I tried the approach as suggested in a similar issue ticket, devtools::install_version("dplyr","0.8.5") but it did not fix the problem.

**Comment by emmaliulu** [comment]
> Hi @emmaliulu could you provide the output of `sessionInfo()` after you get this error?

![image](https://user-images.githubusercontent.com/20967190/136809020-c4993479-a2cf-4281-a3d2-31696714133e.png)

**Comment by 837288251** [comment]
I have met the same problem. 
I've try to download readr 1.4.0, but have the error of "dependency 'BH' is not available for package 'readr'".,the same as installing dplyr 0.8.5. My R version is 4.1.3.
![Uploading 1.PNG…]()
![Uploading 2.PNG…]()

**Comment by russellhz** [comment]
@837288251 have you tried installing BH manually (i.e. `install.packages("BH")`? I'm sorry this has turned into such a long process. Another option is switch your branch to the development branch and then use the `renv` capabilities in that branch (as described here https://github.com/JGCRI/gcamdata/wiki/1.-Getting-Started)

**Comment by 837288251** [comment]
> @837288251 have you tried installing BH manually (i.e. `install.packages("BH")`? I'm sorry this has turned into such a long process. Another option is switch your branch to the development branch and then use the `renv` capabilities in that branch (as described here https://github.com/JGCRI/gcamdata/wiki/1.-Getting-Started)
 
I follow the steps and after"devtools::load_all()", it shows：

 >devtools::load_all()
i Loading gcamdata
Error in `abort_for_missing_packages()`:
! Dependency package(s) 'assertthat','dplyr','tidyr','readr','data.table' not available.
Run `rlang::last_error()` to see where the error occurred.
Warning messages:
1: In (function (dep_name, dep_ver = "*")  :
  Dependency package 'assertthat' not available.
2: In (function (dep_name, dep_ver = "*")  :
  Dependency package 'dplyr' not available.
3: In (function (dep_name, dep_ver = "*")  :
  Dependency package 'tidyr' not available.
4: In (function (dep_name, dep_ver = "*")  :
  Dependency package 'readr' not available.
5: In (function (dep_name, dep_ver = "*")  :
  Dependency package 'data.table' not available.

**Comment by russellhz** [comment]
@837288251 are you using the gcamdata that comes with gcam-core, or did you clone it from this repository? I would suggest cloning from this repository, then you will need to switch to the `develop` branch either under "Current branch" on Github Desktop or by running on the command line `git fetch` and then `git checkout develop` (https://www.atlassian.com/git/tutorials/using-branches/git-checkout)

**Comment by 837288251** [comment]
> @837288251 are you using the gcamdata that comes with gcam-core, or did you clone it from this repository? I would suggest cloning from this repository, then you will need to switch to the `develop` branch either under "Current branch" on Github Desktop or by running on the command line `git fetch` and then `git checkout develop` (https://www.atlassian.com/git/tutorials/using-branches/git-checkout)

Thank you for your advice. Now I have opened the develop branch, but new error occurs. After I use " renv::restore()" , "htmltools" can not be installed.

Error installing package 'htmltools':
=====================================

* installing to library 'C:/Users/83728/AppData/Local/Temp/RtmpkLpDLP/renv-staging-26c46d3b5e95'
* installing *source* package 'htmltools' ...
** package 'htmltools' successfully unpacked and MD5 sums checked
** using staged installation
** libs
Warning in system(paste(cmd, "shlib-clean")) : 'make' not found
Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'htmltools'
* removing 'C:/Users/83728/AppData/Local/Temp/RtmpkLpDLP/renv-staging-26c46d3b5e95/htmltools'
Error: install of package 'htmltools' failed
In addition: Warning message:
curl: (28) SSL/TLS connection timeoutcurl: (35) schannel: failed to receive handshake, SSL/TLS connection failed 
<img width="554" alt="problem" src="https://user-images.githubusercontent.com/90228576/163816534-07660ddd-93d2-4c75-9cec-9d8bea6087f1.png">

**Comment by 837288251** [comment]
> @837288251 you may need to install this and any other needed packages manually with `renv::install("htmltools")`. To install a specific version, you can use `renv::install("htmltools@0.5.0")`. See https://rstudio.github.io/renv/reference/install.html

I successfully installed 'htmltools' package, but new error occurs:
In file included from feedback_arc_set.c:31:
igraph_glpk_support.h:36:10: fatal error: glpk.h: No such file or directory

I have tried renv::install("igraph@1.2.11"), renv::install("igraph@1.2.11",type=“binary”)(as recommanded on the internet) and renv:: install("~/path/to/package“)，but all of them cannot solve the prolem

On the other hand , when I use renv::init( bare = TRUE) , there is a warning that 'The project may be out of sync -- use `renv::status()` for more details'. I don't know whether it matters.

Thank you very much.
<img width="626" alt="problem" src="https://user-images.githubusercontent.com/90228576/164168726-997c6479-0bc3-4c86-991e-e78ea67161c5.png">

**Comment by russellhz** [comment]
@837288251 as a first step, can you try `renv::restore(exclude = c("igraph"))`. igraph isn't necessary for most users.

This (https://github.com/igraph/rigraph/issues/423) may also help some with your issue (I wonder if you have RTools?)

Sorry again for this long install process. Hopefully your troubles will help us make this smoother for future users.

**Comment by 837288251** [comment]
> @837288251 as a first step, can you try `renv::restore(exclude = c("igraph"))`?. igraph isn't necessary for most users.
> 
> This ([igraph/rigraph#423](https://github.com/igraph/rigraph/issues/423)) may also help some with your issue (I wonder if you have RTools?)
> 
> Sorry again for this long install process. Hopefully your troubles will help us make this smoother for future users.

I use `pacman -Sy mingw-w64-{i686,x86_64}-glpk` and 'igraph' was able to installed. However, after that I'm not able to run "renv::restore()".
```
> renv::restore()
The following package(s) will be updated:

# GitHub =============================
- gcamdata.compdata   [* -> JGCRI/gcamdata.compdata@updates-for-readr2.0]

Do you want to proceed? [y/N]: y
Retrieving 'https://api.github.com/repos/JGCRI/gcamdata.compdata/tarball/5a9a5dac5de83c4d91031a1c9b75a5c7e2132695' ...
Warning message:
curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed 
```
I check my internet and try to use some command in Git Bash ,but all of them don't work. I also see someone on the internet said that curl should be update to solve this problem. I don't know whether we can do that.

Don't feel sorry about this. Instead, I should thank for your patience and it's also a studying process for me  to learn more about programming.
<img width="616" alt="problem" src="https://user-images.githubusercontent.com/90228576/164615649-299c3ef7-38b1-4278-b6e9-a7d50f6665a3.PNG">

**Comment by russellhz** [comment]
@837288251 you shouldn't actually need gcamdata.compdata just to run the driver. If that's the only package you're missing, I would suggest trying to run `driver_drake()` now!

**Comment by 837288251** [comment]
> @837288251 you shouldn't actually need gcamdata.compdata just to run the driver. If that's the only package you're missing, I would suggest trying to run `driver_drake()` now!

It works! Xml files were able to generate! Thanks again!!
