### ISSUE TITLE
driver(stop_after) fails to product xml files

### ISSUE THREAD

**Issue by LZRGRAY** [JGCRI/gcamdata#1179]
Hi! I am using driver(stop_after) to produce a set of xml files. The code worked nicely for me before (as recently as 8 hours ago), but it is now throwing out errors that do not seem relevant to the command I am giving. 
For example, I was able to use command: driver(stop_after = "module_GCAMchina_batch_socioeconomics_china_xml") to create the file **socioeconomics_china.xml**. However, 8 hours later when I try to execute the same command, I get the error: 
GCAM Data System v5.1
Found 379 chunks
Found 3918 chunk data requirements
Found 2199 chunk data products
Error in driver(stop_after = "module_GCAMchina_batch_socioeconomics_china_xml") : 
  Unfound inputs not marked as from file: L101.inEIA_EJ_state_S_F, L101.inEIA_EJ_state_S_F, L101.inEIA_EJ_state_S_F, L101.inEIA_EJ_state_S_F, L101.EIA_use_all_Bbtu, L101.inEIA_EJ_state_S_F in module_gcamusa_L132.water_demand_industry, module_gcamusa_LA122.refining, module_gcamusa_LA132.industry_USA, module_gcamusa_LA142.Building_USA, module_gcamusa_LA154.Transport, module_gcamusa_LB123.Electricity

This seems odd since the chunks I am calling to product the xml do not use those files listed in the error report. Is there something wrong with my driver(stop_after) function? It seems it is calling ALL R chunks in gcamdata instead of the ones _needed_ to produce the xml file.

Thank you in advance for your help!

**Comment by russellhz** [comment]
@LZRGRAY sorry for the delay - do you still need help on this issue?
