### ISSUE TITLE
potential bug in FiberCrop production processing in zchunk_LB1321.regional_ag_prices.R

### ISSUE THREAD

**Issue by abigailsnyder** [JGCRI/gcamdata#1180]
This might not be an issue for its intended use, but I've been adjusting zchunk_LB1321.regional_ag_prices.R to get regional price date by year output.  

Something I was seeing in doing this was that US FiberCrop was being backfilled in every year with a default value and I tracked the cause down to a part of the code I hadn't adjusted:
https://github.com/JGCRI/gcamdata/blob/3a1710dc3a40898e1d22e231d062e6f1dd1dca73/R/zchunk_LB1321.regional_ag_prices.R#L150
```
 L1321.prod_kt_ctry_CttnLnt <- filter(L1321.ag_prod_kt_ctry_item, item == "Seed cotton") %>%
      mutate(item = "Cotton lint",
             production = production * aglu.WEIGHT_COTTON_LINT)
```

- the item name (`item`) gets updated but not the `item.code` field, so you have `item="Cotton lint"` and  `item= "Cottonseed"` but with the `item.code` from Seed Cotton in table `L1321.ag_prod_kt_ctry_item`. 

But since there is a subsequent join between that table `L1321.ag_prod_kt_ctry_item` and the prices table (`L1321.prP_ctry_item_75USDkg` on `item.code`: https://github.com/JGCRI/gcamdata/blob/3a1710dc3a40898e1d22e231d062e6f1dd1dca73/R/zchunk_LB1321.regional_ag_prices.R#L174
```
 L1321.ag_prP_ctry_item_75USDkg <- L1321.prP_ctry_item_75USDkg %>%
      left_join(FAO_ag_items_TRADE_pp, by = "pp_commod") %>%
      drop_na(GCAM_commodity) %>%
      left_join(L1321.ag_prod_kt_ctry_item,
                by = c("iso", "item.code", "prod_commod" = "item", "year")) %>%
      # some of the country/crop combinations have no production weights. Drop em.
      drop_na(production)
```
US FiberCrop ended up as NA for all years, dropped, and backfilled with other values despite having plenty of data.  It happens in other regions too obviously, the US is just the easiest place to see it. 

My fix was to add in the correct `item.code` info on the code chunks around L150:
```
L1321.prod_kt_ctry_CttnSd <- filter(L1321.ag_prod_kt_ctry_item, item == "Seed cotton") %>%
      mutate(item = "Cottonseed",
             item.code = (FAO_ag_items_TRADE %>% filter(pp_commod == 'Cottonseed'))$item.code,
             production = production * (1 - aglu.WEIGHT_COTTON_LINT))
```

And then the summations for getting the price multipliers (https://github.com/JGCRI/gcamdata/blob/3a1710dc3a40898e1d22e231d062e6f1dd1dca73/R/zchunk_LB1321.regional_ag_prices.R#L233) had to have `na.rm=T` to run

Anyway, maybe when using the code as it is written in the package, things cancel out and there's no issue. There is at least one upcoming CMP that will need changes to this chunk to output yearly prices over the historical period in addition to everything else, so documenting this now

**Comment by pkyle** [comment]
Nice find, thanks @abigailsnyder !

**Comment by russellhz** [comment]
@abigailsnyder has this already made it into the core?

**Comment by abigailsnyder** [comment]
I have no idea, this is just a bug I identified and fixed in the course of some work I was doing for myself on this branch.

**Comment by russellhz** [comment]
Ok thanks, I will make a pull request from your branch then
