### ISSUE TITLE
Error building gcamdata

### ISSUE THREAD

**Issue by emmaliulu** [JGCRI/gcamdata#1191]
![image](https://user-images.githubusercontent.com/20967190/159566372-d12c1356-9a08-46e9-9876-41ac99fab866.png)

I used the command prompt to build gcamdata system and encountered this error. I also tried using R and got the same error message. Could you help me diagnose the problem?

**Comment by emmaliulu** [comment]
@pralitp

**Comment by russellhz** [comment]
Hi @emmaliulu, I'm guessing this is an issue with package versions (we are working on a fix to this). Can you share you `sessionInfo()` in R when this happens? Also just to check, are you using the latest publicly-available version of GCAM (https://github.com/JGCRI/gcam-core/releases/tag/gcam-v5.4)?

**Comment by emmaliulu** [comment]
@russellhz 
![image](https://user-images.githubusercontent.com/20967190/159981741-00fa1e99-a416-450c-a35d-0b4ce6489527.png)

**Comment by russellhz** [comment]
The issue is most likely cause by `tidyr`. I would suggest going back to version 1.1.4.

**Comment by EngFatemeh** [comment]
I tested the solution you suggested but it didn't work. I used version 1.1.4. of the `tidyr` package. @russellhz 
<img width="1433" alt="script" src="https://user-images.githubusercontent.com/101165513/160202882-06b7f780-b7df-4d38-9e4d-c5cfca351bac.png">

**Comment by russellhz** [comment]
@EngFatemeh can you also send the results of `sessionInfo()` when you try to run the driver?

**Comment by EngFatemeh** [comment]
<img width="929" alt="1" src="https://user-images.githubusercontent.com/101165513/160440510-71c05bc9-f1e0-46a6-a381-52d5f69c935e.png">

**Comment by EngFatemeh** [comment]
@russellhz

**Comment by russellhz** [comment]
Hi @EngFatemeh, I haven't been able to recreate your error on my system with the packages from your `sessionInfo()`. Can you also confirm that you are running the `gcamdata` from the latest publicly-available version of GCAM? One other note is that we've just been testing on R 3.6.3 and R 4.0+.

**Comment by tlongden620** [comment]
Hi @russellhz @emmaliulu @EngFatemeh I also had the same issue. Was able to run gcamdata by changing the version of readr. Bit of trial and error. It ran with readr-1.3.1 and I also did have to use an older tidyr package. Hope this helps.

**Comment by EngFatemeh** [comment]
Yes, I am using the latest GCAM. I tried on R 4.1.2 but it didn't work. However, using readr 1.3.1 solved the error, thanks. @russellhz @tlongden620
