### ISSUE TITLE
Error in 'vec_assign()': ! Can't convert 'replace$element' <double> to match type of 'data$element' <character>.

### ISSUE THREAD

**Issue by 837288251** [JGCRI/gcamdata#1192]
Hi

When I use driver() to build gcamdata system, the error showed after [1] "module_aglu_LA100.FAO_downscale_ctry".
I have tried the steps in #1174,but still doesn't work.

Here is the BackTrace:

Backtrace:
 1. gcamdata::driver()
 2. gcamdata::run_chunk(chunk, all_data[input_names])
      at gcamdata/R/driver.R:295:6
 4. gcamdata::module_aglu_LA100.FAO_downscale_ctry("MAKE", `<named list>`)
 6. tidyr:::replace_na.data.frame(FAO_data_ALL, repl)
 7. vctrs::vec_assign(...)
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/vctrs_error_incompatible_type>
Error in `vec_assign()`:
! Can't convert `replace$element` <double> to match type of `data$element` <character>.
---
Backtrace:
     x
  1. \-gcamdata::driver()
  2.   \-gcamdata::run_chunk(chunk, all_data[input_names]) at gcamdata/R/driver.R:295:6
  3.     +-base::do.call(chunk, list(driver.MAKE, all_data)) at gcamdata/R/driver.R:16:2
  4.     \-gcamdata::module_aglu_LA100.FAO_downscale_ctry("MAKE", `<named list>`)
  5.       +-tidyr::replace_na(FAO_data_ALL, repl) at gcamdata/R/zchunk_LA100.FAO_downscale_ctry.R:274:4
  6.       \-tidyr:::replace_na.data.frame(FAO_data_ALL, repl)
  7.         \-vctrs::vec_assign(...)
  8.           \-vctrs `<fn>`()
  9.             \-vctrs::vec_default_cast(...)
 10.               \-vctrs::stop_incompatible_cast(...)
 11.                 \-vctrs::stop_incompatible_type(...)
 12.                   \-vctrs:::stop_incompatible(...)
 13.                     \-vctrs:::stop_vctrs(...)
 14.                       \-rlang::abort(message, class = c(class, "vctrs_error"), ..., call = vctrs_error_call(call))
 
Thank you very much.

**Comment by russellhz** [comment]
Hello,

The solution should be using tidyr version 1.1.4.

See #1187 

Let me know if that works!

**Comment by 837288251** [comment]
Hello, I've tried R version 3.6.0, 4.0.3 and 4.1.3, but all of them told me that "package ‘https://cran.r-project.org/src/contrib/Archive/tidyr/tidyr_1.1.4.tar.gz’ is not available for this version of R". So I'd like to know which version is suitable for gcam 5.4v now?

**Comment by 837288251** [comment]
I found my way! I use "install.packages("https://cran.r-project.org/src/contrib/Archive/tidyr/tidyr_1.1.4.tar.gz",repos=NULL,type="source")" and install tidyr 1.1.4 successfully. The "vec_assign()"problem was solved.

Thanks so much.

**Comment by russellhz** [comment]
Great! Glad you were able to solve it.

**Comment by BenAGordon** [comment]
Will this issue be fixed in a future update. I believe tidyr is on version 1.2 now.

**Comment by russellhz** [comment]
@BenAGordon we are now using the `renv` package to manage package dependencies. See https://github.com/JGCRI/gcamdata/wiki/1.-Getting-Started#optional-renv----currently-only-on-development-branch-and-gcam-60-release

This will soon be included in the main branch of `gcamdata` as well.

We don't plan to update the code, rather to use `renv` to recommend a set of package versions that work with our code.

**Comment by BenAGordon** [comment]
I thought this was the tidyr page. my apologies. Do you know what the issue is in Tidyr? I can ask them if they plan to fix it.

**Comment by russellhz** [comment]
It looks like they changed the functionality of `replace_na()`. They say "With vctrs, we now ensure that the replacement value is always cast to the type of the column you are replacing in. This ensures that the column types remain the same before and after you replace any missing values."

https://www.tidyverse.org/blog/2022/02/tidyr-1-2-0/#missing-values

Basically, this is more of an issue on our end than theirs, but we've avoided trying to update the code with every tidyverse update by using `renv`
