### ISSUE TITLE
driver() breaks due to replace_na version issue

### ISSUE THREAD

**Issue by junukitashepard** [JGCRI/gcamdata#1198]
I am trying to compile via `driver()` but the script breaks I believe due to a tidyr update that impacts the function `replace_na()`.

`replace_na()` no longer automatically changes an object type, so it needs to be changed manually. This is due to an update to tidyr 1.2.0. 

For example, in the file `zchunk_LA100.FAO_donwcale_ctry.R`, starting at line 271 would need to be updated. The workaround I use now is as follows:

```
# Replace all missing values with 0
numericVarnames <- names(FAO_data_ALL)[!(names(FAO_data_ALL) %in%
                                       c('element', 'countries', 'country codes',
                                         'item'))]
repl <- as.list(rep(0, length(numericVarnames)))
names(repl) <- numericVarnames
FAO_data_ALL[numericVarnames] <- replace_na(FAO_data_ALL[numericVarnames], repl)
```

As `replace_na` is used multiple times in driver(), it may be worth updating all scripts or recommending an olderversion of tidyr.

**Comment by russellhz** [comment]
Thanks for pointing this out. I recommend going back to tidyr 1.1.3 or 1.1.4 We are soon going to be implementing renv in the main branch and GCAM release to manage package dependencies. You can see here all of the package versions that we will be using: https://github.com/JGCRI/gcamdata/blob/develop/renv.lock

**Comment by junukitashepard** [comment]
Perfect. Thanks!
