### ISSUE TITLE
Sourcing Question for CStorage Grading

### ISSUE THREAD

**Issue by ecwood** [JGCRI/gcamdata#1202]
In #616, I saw there was a discussion about CStorage data sources. I noticed that there is no listed source for [A61.Cstorage_curves.csv](https://github.com/JGCRI/gcamdata/blob/main/inst/extdata/energy/A61.Cstorage_curves.csv). In particular, I am curious what the different grades correspond to (e.g. `grade 0`, `grade 1`, ...). If anyone could provide a citation for those different grades, that would be very helpful! (I know there are citations to the first sentence [here](https://github.com/JGCRI/gcam-doc/blob/gh-pages/v5.4/gcam-usa.md#carbon-dioxide-capture-and-geologic-storage), but none of them mention the word "grade").

Thank you!

**Comment by pkyle** [comment]
[CCS Supply Curves.xlsx](https://github.com/JGCRI/gcamdata/files/9117462/CCS.Supply.Curves.xlsx)
Here's an old excel workbook that translates from the resources in Dooley and Friedman to the specific price points used.
