### ISSUE TITLE
repeated lines in energy/OTAQ_trn_data_EMF37

### ISSUE THREAD

**Issue by russellhz** [JGCRI/gcamdata#1215]
lines 1087 and 1088 (Africa, Freight, Rail, All, Liquids, Liquids, CAPEX and non-fuel OPEX, 2005$/vkt) are the same, but with different values after 2040. Presumably 1088 is correct
@pkyle

**Comment by pkyle** [comment]
I can confirm, this was an excel-formula-related error! Line 1088 should be deleted.

**Comment by russellhz** [comment]
Added to PR 267 on stash
