### ISSUE TITLE
Failure to generate XML file

### ISSUE THREAD

**Issue by debibooo** [JGCRI/gcamdata#1218]
Hi, there,
when I first run `driver(write_xml=True)`, no error information but warnings are showing as follows:
> warnings()
warnings：
1: In system2("java", args, stdout = TRUE, stderr = TRUE) :
  running command '"java" -cp "D:/Gcam6/input/gcamdata/inst/extdata/ModelInterface/CSVToXML.jar" -Xmx2g ModelInterface.ModelGUI2.csvconv.CSVToXMLMain C:\Users\PC\AppData\Local\Temp\RtmpC0LMmI\file45d84cb68df "D:/Gcam6/input/gcamdata/inst/extdata/mi_headers/ModelInterface_headers.txt" "xml//no_climate_model.xml"' had status 1033
2: In system2("java", args, stdout = TRUE, stderr = TRUE) :
  running command '"java" -cp "D:/Gcam6/input/gcamdata/inst/extdata/ModelInterface/CSVToXML.jar" -Xmx2g ModelInterface.ModelGUI2.csvconv.CSVToXMLMain C:\Users\PC\AppData\Local\Temp\RtmpC0LMmI\file45d81f2e30b1 "D:/Gcam6/input/gcamdata/inst/extdata/mi_headers/ModelInterface_headers.txt" "xml//disable_climate_model.xml"' had status 1033

As a result, no XML file is output in the _gcamdata/xml_ document.
FYI, my GCAM version is 6.0 and the java version is OpenJDK 18.0.2.1

**Comment by russellhz** [comment]
Hi, I am not totally sure of this error, but it looks like the "status 1033" probably indicates some software malfunction. I would suggest uninstalling and reinstalling java and seeing if that resolves the issue

**Comment by debibooo** [comment]
Thanks a lot. I fixed the error following your suggestion and now it generates the XML file successfully!

**Comment by russellhz** [comment]
Awesome, that's great!
