### ISSUE TITLE
currency year for gcam-usa/EIA_state_energy_prices

### ISSUE THREAD

**Issue by russellhz** [JGCRI/gcamdata#1229]
`module_gcamusa_L226.en_distribution_USA` seems to imply data is in 2009$, but I have not been able to confirm that https://www.eia.gov/state/seds/archive/seper2017.pdf

**Comment by pkyle** [comment]
Just in reviewing this, I find that the original (i.e., prior to our existing versioning) data were downloaded in 2012 and had a dollar year of 2009, and the dollar conversion factor had a year of 2009. The price data were re-downloaded more recently (the commit date was in 2020), but the dollar unit conversion in the code was not updated. It appears that the data year for the prices in gcamdata right now is 2017, not 2009. This update was part of PR150 and CMP305.

**Comment by russellhz** [comment]
looks right, have updated this 2017 in rlh/feature/currency-units on stash
