### ISSUE TITLE
Build Problem 

### ISSUE THREAD

**Issue by zzz1718** [JGCRI/gcamdata#1237]
I'm using R version 3.5.3 When I tried to build and install to make XML files it keep an error

Updating gcamdata documentation
i� Loading gcamdata
Error: 'LEVEL2_DATA_NAMES' is not an exported object from 'namespace:gcamdata'
Execution halted

Exited with status 1.

How I can solve them?

**Comment by ouyang363** [comment]
how did you solve this @zzz1718

**Comment by pkyle** [comment]
I have this same issue and haven't been able to Document in years. Here's a sequence posted internally by @abigailsnyder last year, that might work (I haven't tried it myself; I've modified the commands somewhat for external users, and the specific version of renv might be out of date by now):
* clone gcam-core
* (disconnect from VPN if you are on VPN)
* open gcamdata.Rproj
* install.packages( "https://cran.r-project.org/src/contrib/Archive/renv/renv_0.12.5.tar.gz", repos = NULL, type = "source" )
* renv::init( bare = TRUE)
* renv::restore()
* renv::activate()
* devtools::load_all(".")
And at that point you should be OK to Document.
