### ISSUE TITLE
Maddison_Population 

### ISSUE THREAD

**Issue by Anurag-Dey** [JGCRI/gcamdata#1247]
[zchunk_data_Maddison_population.docx](https://github.com/JGCRI/gcam-core/files/12289891/zchunk_data_Maddison_population.docx)
I am trying to recreate the electricity xml using **a <- driver(stop_after = "module_gcamindia_batch_electricity_xml")** in Rstudio for GCAM 5.2. However, it shows an error while recreating the xml that **Error: Maddison_population is being returned grouped. This is not allowed; please ungroup()**. I have tried to ungroup in the Maddison_population chunk named as **zchunk_data_Maddison_population**. I dont understand why the chunk of code is grouped suddenly and if so why ungroup () is not working. Kindly suggest something related to this error as I am stuck in this error for a while now. Thanks. I have attached the codes for the Maddison chunk and error snapshot.
[zchunk_data_Maddison_population.docx](https://github.com/JGCRI/gcam-core/files/12289906/zchunk_data_Maddison_population.docx)

**Comment by pkyle** [comment]
That error about returning grouped data is something we had in a number of places when the dplyr 1.0 update was rolled out. My guess is that the gcamdata code base you're using isn't dplyr 1.0-compliant, and you'll need to roll back the version that you're using in R:
`devtools::install_version("dplyr", "0.8.6")`

**Comment by Anurag-Dey** [comment]
> That error about returning grouped data is something we had in a number of places when the dplyr 1.0 update was rolled out. My guess is that the gcamdata code base you're using isn't dplyr 1.0-compliant, and you'll need to roll back the version that you're using in R: `devtools::install_version("dplyr", "0.8.6")`

Thank you @pkyle. This worked.
