### ISSUE TITLE
Metadata incomplete for A13.MSW_curves.csv

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#146]
Units and perhaps better description need to be filled in.

**Comment by pkyle** [comment]
Description: Supply curves of municipal solid waste (MSW), inherited from GCAM 3.0.
Units: varied (see below)
maxSubResource (EJ/yr): maximum amount of MSW production in the base year
mid-price (1975$/GJ): price at which half of the maxSubResource is produced
curve-exponent (unitless): shape parameter of S-surve supply function
gdpSupplyElast (unitless): maxSubResource elasticity of GDP
Reference: Luckow, P., M.A. Wise, J.J. Dooley, and S.H. Kim. 2010. Large-scale utilization of biomass energy and carbon dioxide capture and storage in the transport and electricity sectors under stringent CO2 concentration limit scenarios. International Journal for Greenhouse Gas Control 4, 865-877. doi:10.1016/j.ijggc.2010.06.002
