### ISSUE TITLE
Metadata incomplete for states_subregions.csv

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#147]
Units and perhaps better description need to be filled in.

**Comment by pkyle** [comment]
Description: Mapping between state codes, state names, and state groupings found in various inventories relevant for GCAM-USA
Units: NA
grid_region: electricity grid region (n=12)
DIVISION: Census division (n=9)
LRGSTATE: Large states (CA, FL, NY, TX) specifically indicated in 1993-2005 versions of the Residential Energy Consumption Survey (n=4)
REGION: Census region (n=4)
subregion13: Census divisions with 4 large states broken out (n=13)
DIVISION2009: Revised census divisions in 2009 (n=10) Breaks up the Mountain division into Northern (CO, ID, MT, UT, WY) and Southern components (AZ, NM, NV).
subregion9: named census divisions (n=9)
subregion4: named census regions (n=4)
REPORTABLE_DOMAIN: state groupings used in 2009 Residential Energy Consumption Survey, with the greatest degree of geographic resolution (n=27)
subregion27: named reportable domains (n=27)

**Comment by bpbond** [comment]
Thanks.
