### ISSUE TITLE
Metadata incomplete for BEA_pcGDP_09USD_state.csv and BEA_pcGDP_97USD_state.csv

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#148]

**Comment by pkyle** [comment]
Title: GDP by State and Industry, NAICS, Per Capita Real GDP
Units: Chained 2009 US Dollars per capita
Source: Bureau of Economic Analysis, Gross Domestic Product by State, Advance 2013 and Revised 1997-2012.
URL: https://www.bea.gov/regional/histdata/releases/0614gsp/gsp_naics_all_pc.zip

**Comment by pkyle** [comment]
Title: Per Capita Real GDP by State (chained 1997 dollars)
Units: Chained 1997 US Dollars per capita
Source: Bureau of Economic Analysis, Per Capita Real GDP, SIC (1963-1997), All Areas, All Years.
URL: http://www.bea.gov/iTable/iTableHtml.cfm?reqid=70&step=10&isuri=1&7003=1000&7035=-1&7004=sic&7022=10&7005=1&7023=7&7006=xx&7036=-1&7001=11000&7002=1&7090=70&7007=-1&7093=levels

**Comment by bpbond** [comment]
Thanks.
