### ISSUE TITLE
Metadata incomplete for PRIMA_pop.csv

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#149]

**Comment by pkyle** [comment]
Description: 2005-2100 population projections by state
Units: Persons
Source: Scott, M., D.S. Daly, Y. Zhou, J.S. Rice, P.L. Patel, H.C. McJeon, G.P. Kyle, S.H. Kim, J. Eom, and L.E. Clarke. 2014. Evaluating sub-national building-energy efficiency policy options under uncertainty: Efficient sensitivity testing of alternative climate, technological, and socioeconomic futures in a regional integrated-assessment model. Energy Economics 43: 22-33. http://dx.doi.org/10.1016/j.eneco.2014.01.012

**Comment by bpbond** [comment]
Thanks Page.
