### ISSUE TITLE
Metadata for LDS files incomplete Mueller_yield_levels.csv

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#156]

**Comment by pkyle** [comment]
Title: Attainable yield levels by country and basin
Units: tonnes per hectare ("count" is number)
Extended description: Min, average, and max refer to the respective yields observed in grid cells within country, basin, and crop; count is the number of grid cells with harvested area for the given crop, country, and basin.
Source: Mueller, N. D., Gerber, J. S., Johnston, M., Ray, D. K., Ramankutty, N. and Foley, J. A.: Closing yield gaps through nutrient and water management, Nature, 490(7419), 254–257, doi:10.1038/nature11420, 2012. Geospatial data processed by Yannick Le Page.

**Comment by bpbond** [comment]
Thanks!
