### ISSUE TITLE
Change test_timeshift to do a 1-year time shift

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#159]
This will involve addressing #23

**Comment by rplzzz** [comment]
Aren't we doing this already?

**Comment by bpbond** [comment]
Not for `FUTURE_YEARS`, which is only shifted by 5 years. This is a weakness; see #23 .

**Comment by rplzzz** [comment]
Hmm.  We probably need to sit down with Kate and figure out exactly what we want to support in terms of changing the historical and future years.  My guess is that most of the data we produce won't be robust to arbitrary changes.  Still, I think we want to get everything converted first, then tackle this as an enhancement to the mk. 1 system.

**Comment by bpbond** [comment]
This is basically superseded by #388 - closing.
