### ISSUE TITLE
Metadata incomplete for resource_water_share.csv

### ISSUE THREAD

**Issue by swd-turner** [JGCRI/gcamdata#165]
Need source for "1995 US data" for this file...

# File: resource_water_share.csv
# Title: Fresh and saline water share and consumption to withdrawal ratios based on **1995 US data**
# Units: Unitless
# Source: ????
# Comment: Assumes 95% of Middle East water use for resource prodution from saline water

**Comment by skim301** [comment]
We need to ask Mohamad or Page what the original source of that data is how 95% was chosen for Middle East.

**Comment by pkyle** [comment]
I had nothing to do with this file, either collecting the data for it or keying it into the csv table...hoping @mihejazi knows?

**Comment by mihejazi** [comment]
I am not sure who generated this file. I believe the first two columns came from the Davies et al 2013 paper with Page and Jae. I recall that the 95% assumption was made for the middle east along with a couple of other GCAM regions in the paper.  the paper should have all the citations (if any). In term of how the 0.425 was calculated, I suspect it was based on the USGS estimate for the US in 1995. The same case for the last two columns. The last year the USGS  produced both consumption and withdrawal estimates for the electricity sector was in 1995.

**Comment by bpbond** [comment]
@swd-turner you'll work with @mihejazi to get the metadata updated and commit an update? Then we can close this issue. Thanks.

**Comment by swd-turner** [comment]
Ok, we'll resolve this shortly.
