### ISSUE TITLE
Possible mistake in original chunk L110.water.demand.primary

### ISSUE THREAD

**Issue by swd-turner** [JGCRI/gcamdata#179]
Output for this chunk ("L110.water_demand_primary_R_S_W_m3_GJ") is uniform across all regions... does not reflect different fresh/saline fractions for Middle East (see input file resource_water_share.csv). This seems to be caused by a merging error in the original code.

I've coded a fix in the updated chunk and maintained the old behavior under the OLD_DATA_SYSTEM_BEHAVIOR trap.

**Comment by skim301** [comment]
Good catch. The saline fraction should be different for Middle East. Looks like the new code has caught that.

**Comment by skim301** [comment]
I think we can close the issue since you have a fix.
