### ISSUE TITLE
Incomplete metadata for A17.tradbio_curves.csv

### ISSUE THREAD

**Issue by russellhz** [JGCRI/gcamdata#192]
File: A17.tradbio_curves.csv
Title: Supply curves of traditional biomass, inherited from GCAM 3.0 
Units: ? (1975$ ?)
Description: ?
Reference: ?

**Comment by pkyle** [comment]
Title: Traditional biomass renewable resource supply curves, inherited from GCAM 3.0
Units: available: unitless multiplier; extractioncost: 1975$/GJ
