### ISSUE TITLE
Replacement for `match`

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#194]
>rpl [10:08 AM] 
>If we’re going to use `distinct` and `join`, we might want to roll them into a single utility function.

Yes - currently the wiki says use these two to replicate behavior of `match` but we should provide a function?

**Comment by rplzzz** [comment]
I'm indifferent here, as you might have guessed from the fact that I argued for a utility function here and against it in issue #288.  I guess one advantage to having a utility function is that when we eventually want to retire that functionality, we can easily mark the utility as deprecated and get warnings everywhere it is used.  That's assuming, of course, that we don't think there is ever a case outside of backward compatibility where we would want to have this behavior.

In any case, this seems like a good end-of-day project.  I'll knock it out, and you can see what you think of it.

**Comment by bpbond** [comment]
Ok - thanks.


On Apr 25, 2017, at 4:22 PM, Robert Link <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm indifferent here, as you might have guessed from the fact that I argued for a utility function here and against it in issue #288<https://github.com/JGCRI/gcamdata/issues/288>. I guess one advantage to having a utility function is that when we eventually want to retire that functionality, we can easily mark the utility as deprecated and get warnings everywhere it is used. That's assuming, of course, that we don't think there is ever a case outside of backward compatibility where we would want to have this behavior.

In any case, this seems like a good end-of-day project. I'll knock it out, and you can see what you think of it.

**Comment by rplzzz** [comment]
Here's what I wrote when we discussed it in #287 

> I'm a little leery of having several different variations on wrappers around left_join. Probably what we need are some option arguments. For example:
>
> * .ONE_TO_ONE: Error if multiple matches on the RHS.
> * .FIRST_ONLY: Include the first match only
> * .NO_NA: Assert no NA values in the new columns.
>After excluding the combinations that don't make sense, that subsumes six possibilities. Of course, then we have to come up with test data to test all of the possible success and failure modes for all of those possibilities, which will most likely take longer than developing the function itself (which is probably why people are so tempted to skimp on tests.)

I started to work on this yesterday, and the code is actually pretty easy to do.  Writing documentation to explain it all so that someone unfamiliar with what we were doing wouldn't be utterly confused was actually taking longer.  Writing tests will be a bit tedious too, as we'll have a lot of cases to cover.  Maybe I'll push the code up as a PR, and we can get someone else to polish up the docs and tests.

**Comment by bpbond** [comment]
>we can get someone else to polish up the docs and tests

Yes. Thanks for taking a swing at this; sorry to I've been unavailable so much last few days.

**Comment by rplzzz** [comment]
Ok, I'll see if I can scare up a few minutes over the weekend to take care of this.
