### ISSUE TITLE
A51.min_coeff.csv needs metadata

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#200]
Title, Units, and hopefully Description and Source?

**Comment by bpbond** [comment]
Also while I have you on the line, so to speak: line 40 in `L151.ctrl_R_en_S_T.R` subsets to only 2005:

```R
L151.nonghg_ctrl_R_en_S_T <- melt( L111.nonghg_tgej_R_en_S_F_Yh,
                                   id.vars=c( "GCAM_region_ID", "supplysector", "subsector", "stub.technology", "Non.CO2" ),
                                   measure.vars = "X2005",   # subsetting 2005 only
                                   variable.name = Y, value.name = "curr_coeff" )
```

Why? I'd like to add some comments explaining at this point.

**Comment by pkyle** [comment]
I'm not the one who developed/implemented the method (I did shorten the number of steps), but I believe that what is going on here is that the EDGAR emissions inventory only goes up to 2008, so for calculating emissions coefficients, 2005 is the final base year. These steps calculate the "reduction" required to get from the 2005 observed emissions coefficients (for each region / technology / emissions species) to the exogenous minimum coefficient for each technology / emission species.

**Comment by pkyle** [comment]
Title: minimum (i.e., fully controlled) emissions coefficients by technology and emissions species, for non-greenhouse gases
Units: kg per GJ
Source: check with Kate, I really don't know

**Comment by bpbond** [comment]
@kvcalvin do you know the source of this file's data? Also, does anyone know what units are?

```
# File: A51.min_coeff.csv
# Title: Minimum (i.e., fully controlled) emissions coefficients by technology and emissions species, for non-greenhouse gases
# Units: NA
supplysector,subsector,stub.technology,SO2,NOx,CO,BC,OC,NMVOC
elect_td_trn,elect_td_trn,elect_td_trn,,,,,,
electricity,biomass,biomass (conv),0.1163,0.0282,0.0057,0.0024,0.0054,0.0008
electricity,biomass,biomass (IGCC CCS),0.001,0.027,0,0,0,0
electricity,biomass,biomass (IGCC),0.001,0.027,0,0,0,0
```

**Comment by kvcalvin** [comment]
@bpbond This file is derived from something in the old GCAM3 (that I don't know much about) and used to limit the GDP controls on pollutant emissions. 

Units: TgXXX / EJ, where XXX is the particular gas (e.g., TgSO2)
Description: Minimum emissions coefficient for various technologies and gases. Emissions coefficients decline with GDP until these levels are reached, after which no further declines are possible.
Source: GCAM3 emissions files (e.g., SO2 are from NonCO2_energy_input.xls, SO2_calcs tab, table starting at row 509)

**Comment by bpbond** [comment]
Thanks!
