### ISSUE TITLE
left_join_error_no_match could throw spurious errors

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/gcamdata#208]
The `left_join_error_no_match` operation detects non-matches by checking the newly created columns for `NA`.  However, we have some input tables, notably the SSP database, that have legit `NA` entries.  In theory, matching an `NA` entry in a join operation of this sort should not be an error.  However, it's also not clear that this will come up in practice.  Perhaps matching an `NA` value from a table like that is a sign that you aren't getting the data you thought you were.

We should at least be aware of the possibility.  If it becomes an issue we could test for non matches explicitly using `anti_join`, and if the anti-join is empty then we allow the left-join to go through, irrespective of missing values (since we know those will have been actual features in the right-side data set.)

**Comment by bpbond** [comment]
Good point. Right, `left_join_error_no_match` is extremely restrictive and won't always be applicable.

**Comment by rplzzz** [comment]
I actually looked into this.  It turns out that `left_join_error_no_match` doesn't actually work by looking for `NA` values; it looks for a change in the number of rows.  I'm not sure it's 100% foolproof, but it definitely doesn't have the problem I described above, and it seems to be working ok in practice.

**Comment by bpbond** [comment]
Yes. As I remember it does two checks: making sure the number of rows doesn't change, and that no NAs are brought in by the join.
