### ISSUE TITLE
Maddison_population.csv empty column

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#22]
The `socioeconomics/Maddison_population.csv` file has an empty column, way out between 2008 and 2030. This causes `readr::read_csv` to throw a warning. Can we remove this column? Because it has no column name, I can't force a skip.

**Comment by pkyle** [comment]
This was the dataset exactly as downloaded from the source; there's no reason to keep the blank column (i.e. feel free to delete it).

**Comment by bpbond** [comment]
Thanks @pkyle . The thing is, if we do that, then the code will break if someone re-downloads it in the future...hmm.

**Comment by pkyle** [comment]
True! I just re-downloaded it a second ago, and while an additional year (2008) is available, there's still an empty column between 2008 and 2030.

**Comment by bpbond** [comment]
Useful link, thanks @rplzzz ! I think the first option makes sense, coupled with a chunk dedicated to this particular dataset (as we've talked about before, see #28 ). This will be a good test of that dedicated-chunk approach.

**Comment by bpbond** [comment]
Ended up just defining the column names explicitly. This will break if the file format changes, but here here that's probably a good thing, as this code `module_data_Maddison_population` is explicitly tied to this file.
