### ISSUE TITLE
`gcam-usa_LA100.Socioeconomics_makedata` and FUTURE_YEARS

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#23]
`gcam-usa_LA100.Socioeconomics_makedata` is not robust to anything except a 5-year change in FUTURE_YEARS, because the future population data used there are 2010, 2015, etc. So a 1-year shift in FUTURE_YEARS means it doesn't intersect with the data years, and in turn `approx_fun` fails (see code below, currently lines 118-127 in `module-gcam-usa.R`.

Basically, I think we'd like to interpolate the future population data to a 1-year timestep.

```R
  # Future population by scenario. Right now just one scenario.
  PRIMA_pop %>%
    # reshape
    gather(year, population, -state) %>%
    mutate(year = as.numeric(year),
           population = as.numeric(population)) %>%
    # interpolate any missing data from end of history into future
    filter(year %in% c(max(HISTORICAL_YEARS), FUTURE_YEARS)) %>%
    group_by(state) %>%
    mutate(population = approx_fun(year, population)) %>%
```

**Comment by pkyle** [comment]
Totally agreed; when I first set this up, the interpolation function was quite slow and would have taken a very long time to write out the future years in one-year increments. Another aspect is that for debugging purposes, writing out all years as columns is kind of impractical. But I agree, FUTURE_YEARS should be all future years.

**Comment by bpbond** [comment]
We talked about this at meeting last week (which was totally my screwup that you weren't invited to, Page–sorry). Let's sit down and take a look at code, and talk to whoever else we need to, and get this interpolating to 1-year FUTURE_YEARS. I'll assign this to me to follow up.

**Comment by rplzzz** [comment]
Sounds good.

**Comment by bpbond** [comment]
This can be closed, now, given new timeshift test.
