### ISSUE TITLE
L101.Population hard-coded 2100 value

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#234]
This file has a line

```
if( "X2100" %in% X_future_years && "X2100" %!in% names( L101.Pop_thous_GCAM3_RG3_Y ) ){
	printlog( "Extending GCAM 3.0 scenario to 2100 using SSPbase population ratios by GCAM 3.0 region")
```

Presumably we'd like to change this hard-coded 2100 value to a constant? Do we want a more general mechanism to extend to some arbitrary end date?

**Comment by pkyle** [comment]
We already don't use the "GCAM3" socioeconomics scenarios any more; hard to see the value in improving the methods of extending GCAM3's socioeconomics from 2095 to 2100, but if this would be a more broadly applicable method then it could be helpful elsewhere.

**Comment by d3y419** [comment]
agree with pkyle. we're keeping GCAM3 for legacy reasons only. we hope we can do away with them once GCAM4 (GCAM5?) is "stable".
that said, i would very much like a generic ability to extend modeling to 2117. but that's probably beyond the dsr mandate.

**Comment by bpbond** [comment]
OK, closing this. Thanks.
