### ISSUE TITLE
$ Conversions

### ISSUE THREAD

**Issue by kvcalvin** [JGCRI/gcamdata#243]
Currently, we use a series of individual $ conversions to go from one year to another (e.g., `CONV_1990_2010_USD`, `CONV_1990_1975_USD`). We should consider a different way. Maybe a function that takes in start & final year?

**Comment by bpbond** [comment]
Agreed--that seems an obvious solution. Where do these conversion numbers come from? @pkyle

**Comment by pkyle** [comment]
It's all from the Bureau of Economic Analysis GDP Deflators. Attached to this comment (note that the attached file was updated in 2014, and as such might have slightly different numbers for all years; not sure). But yeah a function that uses this lookup table could be pretty useful!
[BEA_GDP_Deflator_1929-2014.xlsx](https://github.com/JGCRI/gcamdata/files/914032/BEA_GDP_Deflator_1929-2014.xlsx)

**Comment by bpbond** [comment]
Perfect. Thanks, Page.
