### ISSUE TITLE
GCAM-USA input file NREL_us_re_capacity_factors does not have source information

### ISSUE THREAD

**Issue by gokuliyer** [JGCRI/gcamdata#245]
This file comes from an NREL database (as the name suggests). The source information is not available readily available. This relates to PR 

#238.

**Comment by gokuliyer** [comment]
@aarony2j : Please check if you can find the source for this file. It seems we've lost track of the file.

**Comment by pkyle** [comment]
I just tried for a minute to find it and failed--I did find the source of the corresponding dataset NREL_us_re_technical_potential.csv, and it is: Lopez, A. et al. (2012). "U.S. Renewable Energy Technical Potentials: A GIS-Based Analysis." NREL/TP-6A20-51946. Golden, CO: National Renewable Energy Laboratory. http://www.nrel.gov/gis/docs/us_re_technical_potential.xlsx

**Comment by gokuliyer** [comment]
Exactly! I found the other one too. Thanks anyway. We'll dig deeper on the NREL_us_re_capacity_factors file.

**Comment by pkyle** [comment]
Capacity factors can be calculated from Tables A1-A4 of this report: http://www.nrel.gov/docs/fy15osti/64503.pdf
CapFac = Generation / ( Capacity * 8.766 )
But the numbers I get when I do that are a little different than the ones in the table. So yeah, I really don't know who downloaded this, or where from. My oldest timestamp on the file is October 29, 2013, but I don't have a record of who made it.

**Comment by pkyle** [comment]
Wow, I just saw in that technical potential table, they list GWh and GW! I had not noticed that. See the equation above, and calculate the capacity factors--if it's the same numbers as are in the table, then we have our answer! Note that the 8.766 might also be 8.76, depending on how they count for the leap day every four years

**Comment by aarony2j** [comment]
I checked HI, and it's different. 3725/(2*8766)=0.212, which is different from the table

**Comment by pkyle** [comment]
@aarony2j I just double checked and the #s are the same--you need to do the calc in the excel workbook tho. The values are truncated at 0 decimal points, so there are aggregated rounding errors if you just work from the csv. In the example above, Hawaii should be 1.667, not 2.
I'd say for the source we can just cite the technical potential document and list the equation.

**Comment by aarony2j** [comment]
Oh, that's great. I missed seeing the excel file. Thanks.

**Comment by pralitp** [comment]
It sounds like this got resolved, should we close this issue?
