### ISSUE TITLE
LA143.HDDCDD.R

### ISSUE THREAD

**Issue by russellhz** [JGCRI/gcamdata#253]
Already have much of this code ready to go

**Comment by bpbond** [comment]
OK, I will push up the file skeleton for you.

**Comment by bpbond** [comment]
```R
   return(c(FILE = "common/iso_GCAM_regID",
             FILE = "energy/GIS_ctry",
             "L101.Pop_thous_GCAM3_ctry_Y",
             "i"))
 ```

Something weird happened with parsing this file obviously. FYI.

**Comment by bpbond** [comment]
OK, see  ca85cad.

**Comment by russellhz** [comment]
@bpbond thanks for setting this up. How do we want to deal with these hddcdd input files? In the old data system, the input files are in a GIS folder in the energy system. The code retrieves them using a list in a for loop and binds them together.

**Comment by bpbond** [comment]
Hmm. I guess it doesn't matter, although are the GIS files going to change regularly, such that "we do not know their names or how many there are"? 

Anyway, either way (hardcoded names or loop as now) is fine with me, as long as the chunk returns accurate information when queried for its input dependencies.
