### ISSUE TITLE
US GHG animal methane emissions does not have Source information

### ISSUE THREAD

**Issue by rhoesly** [JGCRI/gcamdata#259]
inst/extdata/emissions/EPA_FCCC_AG_2005.csv give emissions estimates (mostly methane) for the US, 2005 for animal production by animal type. It's likely from EPA Inventory of U.S. Greenhouse Gas Emissions and Sinks (UNFCCC submissions) 2005, but I can't find that specific table anywhere on the web.

**Comment by rhoesly** [comment]
@pkyle @kvcalvin remember this source/any guidance?

**Comment by kvcalvin** [comment]
@rhoesly: I'll send you the original Excel file.

**Comment by bpbond** [comment]
Can this issue be closed?
