### ISSUE TITLE
Intermittent test failures

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#272]
We're seeing intermittent test failures--intermittent from machine to machine, not in time--that we think may have to do with different versions of the `readr` package (I'm on 1.0.0, while people like @rplzzz and @kvcalvin are on 1.1.0).

**Comment by bpbond** [comment]
Seems like we're getting bitten by tidyverse/readr#645

**Comment by rplzzz** [comment]
I have a fix that I'll push up as soon as this telecon is over.  It involves scanning the entire file on read-in, which is obviously not ideal.  I haven't done detailed timing, but it seems pretty slow.  I'm wondering if a better solution would be to see if `write.csv` (instead of `write_csv`) produces valid output.  If so, then by using that to do our output we could continue to use `read_csv` with its default scan length.

**Comment by bpbond** [comment]
OK, thanks. I bet it's slow. Does your fix involve scanning _every_ file? As we discussed, one thing that might help would be a `FLAG_SCAN_ENTIRE_FILE`.

**Comment by bpbond** [comment]
We could also force people to use `readr` 1.0.

**Comment by rplzzz** [comment]
Yes it does, so that's a possibility, but I still think writing data with base R might work for us.  Are there any specific warts in `write.csv` we need to watch out for (other than row numbers)?

Forcing people to use 1.0 isn't a great idea, IMO.  Forced downgrades are always a pain..

**Comment by bpbond** [comment]
No, that would be a last resort, I agree.

AFAIK the biggest issue with `write.csv` will be speed; it's significantly slower than `write_csv`.

**Comment by rplzzz** [comment]
Maybe a `protect_float` argument to our write wrapper that causes it to use base R?

**Comment by bpbond** [comment]
Or our write routine could check for integer-ish numeric columns and change them to `int` before writing?

**Comment by bpbond** [comment]
>Maybe a protect_float argument to our write wrapper that causes it to use base R?

Note this would also depend on a flag mechanism (`FLAG_WRITE_BASE_R`).

**Comment by rplzzz** [comment]
Right, I figured that out when I went to implement the other solution.  We don't write each chunk individually; we call a function that writes them in batch.

**Comment by bpbond** [comment]
Fixed in #278
