### ISSUE TITLE
HDDCDD Metadata - References

### ISSUE THREAD

**Issue by russellhz** [JGCRI/gcamdata#279]
For the HDDCDD files, this is how I'm currently doing the metadata. Should I list the reference as CCSM3? Do we know exactly how/where these files were generated (I'm guessing it was someone at JGCRI)?:

File: population_weighted_CDD_CCSM3x_A2.csv
Title: CCSM3 A2 Cooling Degree Days
Units: Fahrenheit Degree Days
Description: Cooling Degree Days by Country
Reference: Unknown

Also, for GIS_cntry.csv, do we have a reference? Metadata below

File: GIS_ctry.csv
Title: GIS country iso codes
Units: NA
Description: Mapping between iso codes and country names in GIS data
Reference: Unknown

**Comment by bpbond** [comment]
Note this is re #253 and #277

**Comment by pkyle** [comment]
This was the output of a script from Yuyu Zhou; the code is no longer within the domain of JGCRI. From my understanding, you're correct that this is from the CCSM3 climate model, whose data were posted in the CMIP3 archive. I don't think there's an appropriate reference; all of the papers I have that used this data and these methods were for US-specific analysis, and the one study that would have used it globally is the one that was never submitted, and that you've been helping with. That study uses different underlying source data (CMIP5) and different methods too.

**Comment by pkyle** [comment]
In other words, I don't have any more info for you to add to the header of the file.
