### ISSUE TITLE
Years as characters or doubles

### ISSUE THREAD

**Issue by abigailsnyder** [JGCRI/gcamdata#280]
4 of my inputs in LB122.LC_R_Cropland_Yh_GLU are non-integers.

As character:
 L100.FAO_fallowland_kha 
 L100.FAO_CL_kha 
 L100.FAO_harv_CL_kha 

As double:
L120.LC_bm2_R_LT_Yh_GLU

**Comment by bpbond** [comment]
There's a fix for the first three on PR #276 (to be merged shortly) and hopefully that will fix your fourth example too.
