### ISSUE TITLE
Beware - FAOSTAT disaggregating countries that we consider as a single ISO code

### ISSUE THREAD

**Issue by abigailsnyder** [JGCRI/gcamdata#288]
This references the issue @pkyle mentioned on the dsr slack channel on 4/24/17. Tagging @bpbond, I don't know that there's anyone to 'assign' to fix this, so much as it's something everyone should keep an eye out for when working with FAO data. 

This is more of a beware that the old DS handles this wrong in some code and that you must take an extra step to handle this correctly. 

**You might have this error if:**
You have aggregated FAO country/iso data to the level of `GCAM_region_ID` and your calculations match the old DS output everywhere except regions 2 and 13.

The particular chunk of code this arose in for me is `LB122.LC_R_Cropland_Yh_GLU.R`. 

**Example Input Files This Applies to:**
L100.FAO_fallowland_kha
L100.FAO_CL_kha
L100.FAO_harv_CL_kha

These files all include columns: `countries` (actual country name), `country.codes` (a three digit identifying code), and `iso` among other identifying information.

**Old Code example:**
(Part of) One FAO data table is being joined to another via a `match` using `iso` code:

`L122.cropland_cropped_ctry <- data.frame( iso  = L100.FAO_CL_kha$iso, cropland = L100.FAO_CL_kha[[ X_fallowland_year ]] )`

`L122.cropland_cropped_ctry$cropped <- L100.FAO_harv_CL_kha[[ X_fallowland_year ]][ match( L122.cropland_cropped_ctry$iso, L100.FAO_harv_CL_kha$iso ) ]`

**Issue:**
For the `iso` codes eth, sdn, and bel, there are two FAO country entries in each data table.

Taking sdn as an example, there is a row of data for `countries = Sudan` and a row of data for `countries = Sudan (former)` in each FAO data table. Both of these entries have the same `iso = sdn`. In the following `match` by `iso` code only:
`match( L122.cropland_cropped_ctry$iso, L100.FAO_harv_CL_kha$iso )`
there are two potential matches for `iso = sdn` in `L100.FAO_harv_CL_kha` on the right for each `sdn` row in `L122.cropland_cropped_ctry` on the left. 
The reason we no longer use `match` is because when there are multiple potential matches, the first one gets given to everyone: the information corresponding to `countries = Sudan` from `L100.FAO_harv_CL_kha` on the right gets given to the rows for BOTH `countries = Sudan` and  `countries = Sudan (former)` in` L122.cropland_cropped_ctry`.

This is not correct and not what we want - we want  `countries = Sudan` information to be matched with `countries = Sudan` information, and `countries = Sudan (former)` information to be matched with `countries = Sudan (former)` information.

**Actual way to do right in new data system:**
There are two ways to do this correctly:
1. Translate `match` by `iso` to `left_join` by `c("iso", "countries")` or by `c("iso", "country.codes")` so that the information gets joined correctly. I _think_ this will work no matter what you want to do with the joined, FAO country level information.
2. For applications where you are ultimately just aggregating from country level to GCAM region level, you may be able to just add a step to aggregate the individual FAO tables you work with from the `iso-countries` level to the `iso` level before doing any joins and calculations. Beware that order of operations will matter in doing aggregation-join-computation combinations and you will be on your own to make sure it's correct since there's no old DS output to compare to.

**Handling matching old data system:**
You will obviously need to use the 
`    if(OLD_DATA_SYSTEM_BEHAVIOR) {
       ... code that replicates old, incorrect behavior
     } else {
       ... new code with a fix
     }`
structure. Per Ben's comment on DSR slack channel on 4/24/17, if the old DS code is definitely wrong and you are very confident about that, you don't want to spend a lot of time translating code that will be deleted in the end.

I don't know if this will be the case, but I was concerned that if I copy and pasted the original DS code, including a `match` usage,  then I might not be able to pass all the tests and checks at the end since `match` is forbidden. So at least _some_ translation of the incorrect code seemed like a safe route.

I spent a while following the "Name that Function" page's recommendation of doing a combination of `distinct` and `right_join` to replicate the behavior of `match` when it comes to multiple potential matches. I had no luck getting it to work and didn't want to invest substantial time in figuring it out. 

Therefore, my work around was to translate the code the correct way (since that work has to be done within the `else` portion of the `OLD_DATA_SYSTEM_BEHAVIOR` flag) and then, for matching the old data system, manually overwrite the problematic values. For example:
`# MAKING MATCH OLD SYSTEM:`

 `# Update the Ethiopia, Sudan and Belgium rows so that calculations match the old, incorrect DS:`

 `mutate(cropped = if_else(iso == "eth", 11772, if_else(iso == "sdn", 4086, if_else(iso == "bel", 747, cropped)))) %>%`

where each of those numbers is the value that gets assigned to both rows for each `iso` in the old DS. 

This is an ugly and terrible way to do it and may not make it through the review process. But since there were only three places it had to be done, the code will ultimately be deleted, and I couldn't successfully replicate `match`. I cut my losses and moved on.

**Comment by rplzzz** [comment]
Forgive me if I'm just being dense, but it seems like we are _way_ overcomplicating this.  In this case we have multiple entries for a single country (as we define it) in the table we're joining, so we _have_ to aggregate.  The old code used the implicit behavior of match or merge to aggregate by taking the first entry encountered.  New code should replicate that behavior by using `first` as the aggregating function.  For example:
```R
rslt <- group_by(joined_data, iso) %>% summarise(value = first(value))
```
When we turn off backward compatibility, we can replace `first` with `sum` or `mean`, as the case may be, to correct the bug in the old version.

Am I missing something?

**Comment by abigailsnyder** [comment]
Nope, I was not aware of that option.

**Comment by bpbond** [comment]
This is tied to #194 - and yes, it occurs again and again throughout the data system code.

**Comment by abigailsnyder** [comment]
@bpbond  relating to 194, that would definitely be helpful in terms of making Matching the Old DS easier.

I should rewrite this at some point to emphasize that this issue is about why the old DS does the join wrong (by `match`) and the way to do the join in the new DS correctly.

In other words, the `match` error occurs often throughout the data system, but I think that the specifics of how it's wrong will vary depending on the actual input data that is being operated on. Which means that the fix to do it correctly in the new DS (e.g. what we _wanted_ the `match` to do in the old DS) will also vary depending on the specific data. we're operating on.

**Comment by bpbond** [comment]
>the specifics of how it's wrong will vary depending on the actual input data that is being operated on

Yeah, agreed. Can we relocate all these `match` calls in the new data system? Again citing #194, can/should we have a `match_proxy` function that implements a `first` or `distinct` approach, and lets us easily come back to this later in each function?

**Comment by abigailsnyder** [comment]
I think the `match_proxy` is a great idea, but maybe we should update the tests to restrict its use to ONLY within
`if(OLD_DATA_SYSTEM_BEHAVIOR){ ... } `
That way, the chunk author will also have to do it the correct way for the future in the `else{ ... }` portion of the flag

**Comment by bpbond** [comment]
That would be great, if we're willing to do the upfront work.

**Comment by pkyle** [comment]
![lumbergh](https://cloud.githubusercontent.com/assets/20807787/25392812/b0e9dcba-29a7-11e7-9f85-d50ae0dd9fb0.png)

**Comment by rplzzz** [comment]
@abigailsnyder I'm not sure what you mean by "match joins the data incorrectly".  It sounds like the original code chose the columns to join by poorly, but it is behaving in a predictable way that should be easy enough to replicate with a join and aggregate approach. If I'm understanding your example correctly, you might have to `group_by(iso, iso-countries)` (instead of just by `iso`) in the aggregation step, but that seems like a small change.  

I'm not a fan of the `match_proxy` approach.  I get that it would make it easy for us to change the behavior when we turn off backward compatibility, but it would be at the cost of introducing a custom function that someone reading the code has to go look up when they encounter it.  I'm also _really_ not a fan of creating utility functions whose semantics change over time because users can't really be sure what it's doing this week.  Wouldn't it be better just to document this programming idiom in the Name That Function guide?

**Comment by bpbond** [comment]
https://github.com/JGCRI/gcamdata/wiki/Name-That-Function#match

**Comment by abigailsnyder** [comment]
@rplzzz You are basically right. I'm just really struggling to get into words.
I've attached an excel spreadsheet with some dummy numbers trying to clarify what I'm explaining badly.

In that spreadsheet there's

>  if(OLD_DATA_SYSTEM_BEHAVIOR){
>       code to produce old DSR table
>        In theory, a combo of distinct + right_join as in https://github.com/JGCRI/gcamdata/wiki/NameThat-Function#match
> } 

You are correct that it is predictable and that something like Ben's solution under https://github.com/JGCRI/gcamdata/wiki/Name-That-Function#match. Absolutely should be easy.

But I spent about an hour and a half trying the solution under https://github.com/JGCRI/gcamdata/wiki/Name-That-Function#match different ways and could not for the life of me get it to work. Possibly because I had already spent a good amount of time tracing back what the issue was and my brain was just fried.  So I just manually over-wrote the handful of values to match the old DS and moved on. 

This issue is just to give a heads up that there's some quirks with FAOSTAT data. In the case of this chunk, the old DS script was written before any of the data picked up quirks and therefore originally worked as intended. With the more updated data, it behaves in a predictable way, but no longer does the calculations as intended. 



[IssueDummyExample.xlsx](https://github.com/JGCRI/gcamdata/files/955689/IssueDummyExample.xlsx)

**Comment by rplzzz** [comment]
Ok, it sounds like we are converging on a solution.

Also, shouldn't the ISO code for "Sudan (former)" be SSD?  Are there any other former Sudan regions besides South Sudan?

**Comment by abigailsnyder** [comment]
Yeah, I have it totally working and the old/new flags set up fine. It's just ugly because I couldn't get Ben's solution to work. 

re the ISO codes, I have no idea.

**Comment by pkyle** [comment]
This one is worse than other countries that have changed boundaries and/or ISO codes over time, for several reasons. One, because it happened so recently (2011), nearly all of our source data doesn't have it disaggregated. Two, the "united" country (Sudan, sdn) has both the same name and the same ISO code as the northern half after the split. This is different from Serbia and Montenegro (scg together; srb and mne apart). We have a few options for handling it; given that we wouldn't ever put these in separate GCAM regions, I don't see a whole lot of value in re-constructing the disaggregation for all of our datasets back to 1971, the way we do for Former USSR or Yugoslavia. I'd probably recommend just calling them both SSD and aggregating all quantity variables before data processing, but I'm also open to other options.

**Comment by rplzzz** [comment]
Thanks, Page.  I will add this to my list of reasons why I am skeptical of secession movements.
