### ISSUE TITLE
Input file A_fuel_conv.csv: Source for fuel-specific conversion factors?

### ISSUE THREAD

**Issue by aarony2j** [JGCRI/gcamdata#293]
Any idea the source for these conversion factors?
![image](https://cloud.githubusercontent.com/assets/26774951/25408237/56226534-29db-11e7-8971-3f791fc5e795.png)

**Comment by pkyle** [comment]
This is just a table of unit conversions, from billion btu (HHV) to EJ (LHV). For fuels only indicated in terms of electricity output, there's no LHV conversion, and it's just 1.0551e-6. For the others, I can't really give a specific source; I think I used 0.905 for natural gas, 0.94 for oil and derived fuels, and 0.965 for coal. It's hard to tell exactly with the rounding.
Particularly for coal and oil (and derived fuels), the variety of "grades" means that there is no single conversion factor that can be cited. I also don't know that there's any value to citing specific data sources for unit conversions, but if we do want one, a simple on-line search should suffice.

**Comment by aarony2j** [comment]
Thanks, Page. Those numbers fit the data, and I filled in the rest as you can see in the picture below. It's not obvious to me where to source those numbers (i.e., 0.905, 0.94, 0.965). If you have a suggestion, I'll take it. But it may be good enough to at least explain how the conversion factors were determined.
![image](https://cloud.githubusercontent.com/assets/26774951/25411117/de0a1cd2-29e8-11e7-8809-87ed5f5269e7.png)

**Comment by pkyle** [comment]
OK, here's one (of many possible) source with LHV and HHV of fuels: http://hydrogen.pnl.gov/sites/default/files/data/lower_and_higher_heating_values.xls
The basic engineering explanation for the difference is that the LHV:HHV difference is determined by the ratio of H2O to CO2 in the combustion flue gases, and as such the ratio scales with the hydrogen:carbon ratio of the fuel. Higher hydrogen content means lower LHV:HHV. 
Note that our specific assumptions differ from the values in that table; they are legacy values from before I started working here (in 2006).
Note also that our actual processing methods scale the energy quantities such that [I think] the specific values assumed here don't actually matter. You could test that out by, when you're done processing the chunk, just set every value in the table to 42 and see if the results are the same.

**Comment by aarony2j** [comment]
This is all very helpful information. Thanks for sharing.
