### ISSUE TITLE
Error being thrown in tests for current master

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/gcamdata#295]
The current master branch (4ffab50) throws an error while running its tests:
```
DONE ===========================================================================
Error in left_join_error_no_match(., L101.Pop_thous_GCAM3_ctry_Y, by = c("iso",  : 
  left_join_no_match: NA values in new data columns
```
For some reason this isn't causing any of the tests to fail.  Perhaps it's happening during some setup in the testing code that isn't actually being subjected to an `expect` call?  We should investigate the cause.

**Comment by bpbond** [comment]
The error is occurring in line 124 of `LA143.HDDCDD`, under the timeshift test:
```R
    # Add population data and region data
    L143.wtHDDCDD_scen_ctry_Y <- L143.HDDCDD_scen_ctry_Y %>%
      # Join with population data converted to long format
      left_join_error_no_match(L101.Pop_thous_GCAM3_ctry_Y,
                               by = c("iso", "year")) %>%
```

I haven't look at the relevant data frames in detail but pretty clearly when `HISTORICAL_YEARS` and/or `FUTURE_YEARS` get changed there are NAs in this step. I think we need to do two things:

1. Ask @russellhz to take a look at this chunk again. In particular, there probably needs to be an interpolation step to ensure that we have data for all years? Russell, the time shift test is changing these years variables and re-running the chunks, trying to find (as it did here) fragility.
2. Figure out why no 'real' error is getting thrown in `test_timeshift.R`. This is being run inside of a `with_mock` call, which may be causing odd effects. I tried putting an `expect_silent` inside it no luck; am out of time at the moment, but can come back to this later.

**Comment by rplzzz** [comment]
Yeah, I had to do some extra work to get the time shift test to work properly (the problem is 2011, for which we typically don't have data as it is neither a historical year, nor a future year).

Also, in that code snippet you posted, we are joining with `L101.Pop_thous_GCAM3_ctry_Y`, which seems really weird, as I don't think these are GCAM3 scenarios.  We should have another look at that too.

**Comment by russellhz** [comment]
L101.Pop_thous_GCAM3_ctry_Y gets read in with historical years 1971:2010 by 1 year and 2015:2100 by 5 years. The HDDCDD data begins with all years from 1971:2100. It later gets trimmed to match the population file years with 
`filter(year %in% c(HISTORICAL_YEARS, FUTURE_YEARS))`

In the code that writes L101.Pop_thous_GCAM3_ctry_Y, it is filtered the same way. 

I would think the time_shift would shift the incoming population file and it wouldn't be a problem?

**Comment by rplzzz** [comment]
That's what we need to find out.

**Comment by russellhz** [comment]
Here's what I think may be the problem, although I don't necessarily know enough about the testing system to say for sure.

1. LA143.HDDCDD.R gets its population data from L101.Pop_thous_GCAM3_ctry_Y, which is read in with the default `HISTORICAL_YEARS, FUTURE_YEARS`

2. L101.Pop_thous_GCAM3_ctry_Y gets written in L101.Population.R. One file it uses is `"temp-data-inject/L100.Pop_thous_SSP_ctry_Yfut"`, which is read in with 2015:2100 by 5 future years. I'm thinking that since this is a temporary data file, the time_shift can't work here to change its years. 

I'm not sure if this would cause the error and it seems surprising that it would only come up with the HDDCDD chunk.

**Comment by rplzzz** [comment]
So, first thing, using temp-data-inject for L100.Pop_thous_SSP_ctry_Yfut should no longer be necessary, as that chunk seems to be up and running.  We should get rid of the temp data.

Second thing, why are we using the GCAM3 population, when we're not using it for anything else?  We may be stuck with it for now for backward compatibility, but this seems like something we should flag for fixing going forward.

**Comment by russellhz** [comment]
It looks to me like L100.Pop_thous_SSP_ctry_Yfut is written by zchunk_L100.Population_downscale_ctry.R, which is not completed right now.

I think you are right, we should switch out of L101.Pop_thous_GCAM3_ctry_Y. Of course, pretty much all of the HDDCDD code is currently irrelevant, as it uses CMIP3 data.

**Comment by rplzzz** [comment]
My mistake.  I glanced at that file and for some reason thought it had been completed.  Not sure why.

As to the GCAM3 and CMIP3 data, we should just flag it to update once the conversion is all done.  I'm going to guess that it's using the old population data because nobody noticed it when we updated, and we don't want it to happen again.

We still need to figure out what to do about the time shift, though.  I expect this to come up a lot because the time shift produces 2011 as a historical year, which often doesn't exist in our data.  One possibility is to allow the join to produce missing values and then interpolate.

**Comment by bpbond** [comment]
Re temp-inject-data and completed chunks, the driver will let us know (via a nice red message) when that occurs.

>One possibility is to allow the join to produce missing values and then interpolate.

This is the obvious one that occurs to me, yeah.

**Comment by bpbond** [comment]
@russellhz It would be great to get this resolved soon, since it's throwing an "error" (tests don't formally fail, but a message pops up) on everyone's branches at this point.
