### ISSUE TITLE
Order of "Rows in x but not y:"

### ISSUE THREAD

**Issue by ssmithClimate** [JGCRI/gcamdata#298]
In the testing script, I got the following:

Rows in x but not y: 6919, 6914, 6902, 6898, 6893, 6889, 6881, 6833, 6829, 6818, 6809[...]. Rows in y but not x: 6646, 6628, 6586, 6570, 6502, 6484, 6474, 6444, 6426, 6410, 6390[...]. 

Is x the new or the old data?

Also, how is this counting rows. Rows 6919, for example, is actually the same (up to first 3 digits) in both, so its not missing!

**Comment by bpbond** [comment]
Not the greatest error message, I agree. At this point it's usually easiest to load the relevant data frames directly and take a look at them, e.g.

```R
driver() -> x
x[["chunk_output"]]
y <- readr::read_csv("tests/testthat/comparison_data/emissions/chunk_output.csv")
y
```

And then compare their dimensions, columns types, summaries, etc. I'm back in the office Friday and happy to help if useful.

**Comment by bpbond** [comment]
@ssmithClimate I'm closing this but re-open if necessary.
