### ISSUE TITLE
How are the tables in LA100.FAO_downscale_ctry getting their flags?

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/gcamdata#299]
Here is the code that creates (one of) them:
```R
    L100.FAO_fallowland_kha %>%
      add_title("FAO fallow land area by country, year") %>%
      add_units("kha") %>%
      add_flags(FLAG_PROTECT_FLOAT) %>%
      add_precursors("aglu/FAO_fallowland_kha_RESOURCESTAT", "aglu/AGLU_ctry") ->
      L100.FAO_fallowland_kha
```
However, the flags line of the output file produced is:
```
NO_XYEAR FLAG_LONG_YEAR_FORM FLAG_PROTECT_FLOAT
```

Here's what the table's flag situation looks like just before write:
```
Browse[2]> cn
[1] "L100.FAO_fallowland_kha"
Browse[2]> get_flags(cd)
[1] "NO_XYEAR FLAG_LONG_YEAR_FORM" "FLAG_PROTECT_FLOAT"
```

Where were these flags added, and why are we getting them as a character vector, instead of the flat string normally produced by `add_flags`?

**Comment by bpbond** [comment]
It happens up above in the file, lines 235-244:

```R
    # Re-split into separate tables for each element
    for(i in unique(FAO_data_ALL_5yr$element)) {
      legacy_name <- paste0("L100.FAO_", i)
      filter(FAO_data_ALL_5yr, element == i) %>%
        add_comments("Downscale countries; calculate 5-yr averages") %>%
        add_legacy_name(legacy_name) %>%
        add_flags(FLAG_NO_XYEAR, FLAG_LONG_YEAR_FORM) ->
        df
      assign(legacy_name, df)
    }
```

Here the code has finished operating on all the tables, that are bound together into one big d.f., and at this point splits them apart and back into separate objects, assigning the basic flags and info as it goes.

**Comment by bpbond** [comment]
Closing this, but re-open if necessary @rplzzz .
