### ISSUE TITLE
Metadata: A42.inc_elas.csv

### ISSUE THREAD

**Issue by russellhz** [JGCRI/gcamdata#318]
Need source and units (sounds like unitless is probably simplest)

File: A42.inc_elas.csv
Title: Building sector income elasticity
Units: pcgdp_90thousUSD: Thousand 1990$; **inc_elas:**
Description: Aggregate buildings sector income elasticity as a function of per-capita GDP 
**Source: unknown**

**Comment by d3y419** [comment]
unitless (% change in service demand / % change in income)
