### ISSUE TITLE
missing non-CO2 emissions in EPA, but exists in EDGAR

### ISSUE THREAD

**Issue by d3y419** [JGCRI/gcamdata#327]
https://github.com/JGCRI/gcamdata/pull/256
https://github.com/JGCRI/gcamdata/pull/309

recurring issue in non-CO2.

```
      # Compute sector emissions.
      # If these are zero, then reset all fuel em_factors to 1. Why? From Kate: I don't totally
      # remember, but I think there was a specific case where this was required. Essentially,
      # we will later scale these emissions to match EDGAR totals.
      # If there is a zero here, but positive emissions in EDGAR, then the scaling won't work.

mutate(em_factor = if_else(sector_emissions == 0, 1, em_factor)
```

looks like we set emissions in each sector using EPA,
then scale everything by EDGAR.

but if EPA value is zero, but EDGAR value is positive, then the total doesn't add up to EDGAR.
so we set some arbitrary value for EPA, in the hopes that EDGAR value will overwrite this. 

I think this method may still work with new projects using EPA or CEDS as the total emission scaler. but maybe someone else has a better idea.

**Comment by pkyle** [comment]
Huh, yeah this is probably worth a look though I won't have a chance to do this in any detail, at least not this week. If anyone has time/motivation, the thing to look for is EPA categories within EDGAR categories that have a mix of data-derived emissions factors and default emissions factors (1s). An example just from a quick look is GCAM_region_ID == 1, Non.CO2 == CO, year == 2005, EDGAR_agg_sector == "industry_energy". Note that this won't be available until the L111 chunk is processed. Anyway the "cement" sector is getting a default coef of 1 whereas the data-derived industrial energy coefs are < 0.1; the net effect is that the cement sector is assigned the majority of US industrial sector emissions.

**Comment by rhoesly** [comment]
Was adding me to this issue a nudge to get me to look at it? I'm happy to, I just need to know how much time/effort to allocate....

**Comment by ssmithClimate** [comment]
Our plan after DSR is complete is to calibrate GCAM to CEDS instead of EDGAR, so this issue will go away then since we will be using data by country directly and not starting from US EPA data.

**Comment by bpbond** [comment]
Can this issue be closed? Or should it be tagged as milestone 1.1 or 2?

**Comment by ssmithClimate** [comment]
The issue still exists, so probably can't be closed. I don't know what milestones are so can't comment on that...

**Comment by bpbond** [comment]
Thanks. Based on your comment above ("Our plan after DSR is complete...") I'm assuming this can be safely tagged as v1.1 though.

**Comment by ssmithClimate** [comment]
Sounds good!
