### ISSUE TITLE
Maddison population data cleaning

### ISSUE THREAD

**Issue by swaldhoff** [JGCRI/gcamdata#349]
The chunk that reads and cleans the Maddison population data (zchunk_data_Maddison_population.R) seems to be reading the column headers as data, so there is an entry for "Country" with population values equal to the years in the data set. It doesn't really matter for the end results, because "Country" will get dropped since it has no iso code, but it's probably worth fixing the file.

**Comment by bpbond** [comment]
Good catch--thanks. I'll commit a fix to `master`.

**Comment by bpbond** [comment]
Just as a followup - the fix was not to fix the _file_, which (presumably) comes from some external source in that format, but rather the _code_ to handle it.

**Comment by swaldhoff** [comment]
Good point. I should have said code, not file!
