### ISSUE TITLE
Maddison population data - Total Former USSR

### ISSUE THREAD

**Issue by swaldhoff** [JGCRI/gcamdata#350]
This chunk also removes the country entries with "Total" in the name, but this drops the Total Former USSR, which is needed for disaggregating the component countries in years prior to 1950.

**Comment by bpbond** [comment]
Ah crap, that's absolutely my fault. DOUBLE good catch.

**Comment by bpbond** [comment]
Just to be sure -- of all the subtotals ("Total ..."), there's one ("Total Former USSR") that we DO want to keep?

**Comment by swaldhoff** [comment]
I probably would have done the same thing if I was cleaning it as a stand alone file. It wouldn't be obvious that we'd want to keep aggregate country/regions.

**Comment by swaldhoff** [comment]
Yes, just "Total Former USSR".

**Comment by bpbond** [comment]
Stupid file. OK, thank you!

**Comment by swaldhoff** [comment]
Thank you!
