### ISSUE TITLE
Speed up the driver by adding a `run_only_to` capability?

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#379]
As our list of active chunks grows, the driver is getting slower, and I suspect this is increasingly taking a toll on folks' productivity. (Start the driver, go get coffee...) I've been thinking about ways to speed it up and, more generally, the development process.

One idea: if someone is working on chunk XX, it would be great to be able to tell the driver "run only the chunks necessary to make XX work, and then stop", e.g. `driver(run_only_to = "XX")`. The driver would use the dependency tree to identify the chunks necessary to get for XX to run, and execute **only** them.

The driver would run much more quickly, and its output (the `x` in `driver() -> x`) would be smaller (it's currently almost 650 MB), speeding up the build-and-reload step as well.

Thoughts @rplzzz @abigailsnyder @kvcalvin @pralitp @rynacui others ?

**Comment by kvcalvin** [comment]
This sounds like a good idea to me. Another thing that would be good is to only need to test one chunk at a time, since that is also taking longer.

**Comment by bpbond** [comment]
@kvcalvin good idea. The run_only_to mechanism, by itself, would speed up testing (as only the chunks that ran would be tested) but we could go further.

**Comment by rplzzz** [comment]
As of the latest master, on my workstation a full driver run takes 51 s, with 17 s of that being data output.  The test suite takes 68 s, with 45 s of that  being the time shifting test.  Neither of these totals seems long enough to me to warrant putting any significant effort into customizing the run process.  One thing that might be a quick win would be to make it possible to disable the time shift test, since we're ot even sure it does what we want it to, but beyond that I wouldn't put a huge amount of effort into it.

**Comment by rplzzz** [comment]
Profile reports:

http://rpubs.com/Robert_Link/prof-driver-6dfc286
http://rpubs.com/Robert_Link/prof-test-6dfc286

**Comment by abigailsnyder** [comment]
I see both sides. For now, it's on the cusp of not _too_ bad in terms of the time.  I see on slack that we can skip the time shift test to speed things up. Maybe this is enough for now and we can revisit the driver when more chunks are committed? I'd say once the driver run starts taking more like 2-3+ minutes, that hits the awkward spot of a long time sitting and waiting but not long enough to do anything else.  As an additional note, you don't have to run the driver _that_ many times while translating a piece of code. So I wouldn't expect it to impact productivity that frequently?

**Comment by bpbond** [comment]
Agreed @rplzzz @abigailsnyder . Thanks. OK, I put the note on Slack about skipping timeshift, which hopefully will help. Otherwise, we can leave this for now.

Multiple driver runs probably only really start becoming an issue late in the game, when you have a running chunk but are trying to figure out why its outputs are failing tests.

**Comment by abigailsnyder** [comment]
ah, the most fun time in DSR
