### ISSUE TITLE
test_timeshift needs to fail correctly!

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#388]
Currently it doesn't - prints an error message with no context at end of testing. Very confusing.

**Comment by rynacui** [comment]
In #389, it seems very annoying because the entire data set needs to be extended back before 1971, which are not used at all, just to allow the `timeshift`.

**Comment by bpbond** [comment]
This really goes to a question @rplzzz  and others have asked--what exactly do we want the timeshift test to be testing? Right now it adds 1 to `HISTORICAL_YEARS`, `AGLU_HISTORICAL_YEARS`, and `FAO_HISTORICAL_YEARS`, and 5 to `FUTURE_YEARS`, and ensures things run without error.

@kvcalvin and others does this make sense? The goal is to ensure some degree of temporal flexibility, but is the right way to test it?

**Comment by rplzzz** [comment]
I think we should defer this for now.  Get everything converted into a code base we can work with, and then we can figure out what is supposed to happen in time shifting, rejigger the tests accordingly, and see which modules aren't doing it right.

**Comment by bpbond** [comment]
To clarify, are you suggesting we disable the timeshift test entirely for now, at least until v1?

**Comment by rplzzz** [comment]
As long as it's not causing failures we don't know (i.e., haven't yet decided) how to fix, I don't see any harm in leaving it in.

**Comment by bpbond** [comment]
It is, however, creating more work for people to address (see @rynacui comments above), when we're not sure if that work is necessary or not.

**Comment by rplzzz** [comment]
Well, then, let's just skip those tests for now, and we can circle back and make fixes once we've figured out how it's supposed to be working.

**Comment by bpbond** [comment]
@kvcalvin thoughts on disabling time shift for now?

**Comment by bpbond** [comment]
I worked on Jill's #353 a bit to make it pass timeshift and have to say--I've strongly swung back to keeping this test, albeit in a modified form. It was not hard to make the code handle it, and makes it _a lot more robust_.

That said, I think @rynacui is right above, that's there's no point in asking the code to handle _arbitrary_ shifts. But at the very least, it should handle changing from `HISTORICAL_YEARS` of 1971-2010 and `FUTURE_YEARS` 2015-2100 (as now) to 1971-2011 and 2020-2100, respectively. This will expose a lot of hardcoded assumptions and logic.

**Comment by kvcalvin** [comment]
@bpbond: I tend to agree with your latest position. Part of the motivation for DSR was that we couldn't get a annual hindcast to work in the old data system, something that is a deliverable this FY. I think it would be a bad thing if at the end of this we still couldn't do that. So, I support the one year shift test. For the `HISTORICAL_YEARS`, I think what you propose is right -- see if 1971-2011 works. For `FUTURE_YEARS`, I'd suggest something similar -- would 2016-2096 work? I would say that we don't need to test post-2100 --- that is likely to fail and not really on our radar.

**Comment by bpbond** [comment]
I think ensuring chunks can handle 1971-2011 (historical) and 2016-2096 (future) sounds good. We can say by default you should use, if necessary, `approx_fun(..., rule = 2)` which will extend the time series using the last value. This still leaves unresolved many questions, but hopefully will be a good step and doable for V1.

I'll start a branch.

**Comment by bpbond** [comment]
@rplzzz I've been trying to make a `complete_yearvalue_data` function, a convenience function to make dealing with timeshift easier: it would take a tibble `d` and a `year_range`, (i) `complete` the tibble putting NAs into `value`, and (ii) interpolate out `value` to any missing years. So if `AGLU_HISTORICAL_YEARS` gets extended to 2011, and the data only go to 2010, this would extend the data in a sensible way. Data can have any structure as long as there's `year` and `value`.

The NSE part of tidyr (because I want to use `nesting` with not-predefined columns) has been tying me in knots though. Any suggestions?

```R
complete_yearvalue_data <- function(d, year_range) {
  groupvars <- setdiff(names(d), c("year", "value"))
  dots <- lapply(groupvars, as.symbol)

  # Can't figure out how to make standard-eval complete_ and/or nesting_ work here
 d %>%
    complete(year = year_range, nesting_(dots)) %>%   # doesn't work
    arrange(year) %>%
    group_by_(.dots = dots) %>%  # works fine
    mutate(value = approx_fun(year, value, rule = 2))
}
```

**Comment by rplzzz** [comment]
@bpbond @kvcalvin I think we're still getting it wrong.  On further thought, the main source of our problems is that we are making `HISTORICAL_YEARS` do double duty as "the years that can be found in the historical data" in some parts of the code and "the years that will be treated by GCAM as historical" in others.  This is an error because those two are not always one and the same. (And a similar argument applies to `FUTURE_YEARS`.  

Expecting the code that processes the historical data to pretend that 2011 is available in the data when it isn't is not a reasonable thing to do.  In particular, extrapolating with `rule = 2` will not produce a time series that matches smoothly at the boundary between history and future; it will have a hitch at 2011.  

What we should do instead is to have code that handles raw inputs produce a time series from the existing historical and future scenario data.  It can then interpolate and filter as necessary to produce a time series with all of the years GCAM is expecting in it.  

As to the test that we use to verify this behavior, it should be something that we might actually do, such as set up the backtesting runs.  Kate's problem that started this project was, if I remember correctly, that 2005 was special in some data sets, and the processing failed if 2005 was not in the output.  The test as we have designed it now won't catch that because 2005 and 2010 are still in `HISTORICAL_YEARS`.  The time shift test should be something like 1971-1990 as GCAM-history and 1991-2010 as GCAM-future.  (If you really want to stress test the system you could make the GCAM-future go out to 2050, which would reveal any problems with GCAM-future comprising both historical and scenario data).

Finally, whatever we decide the test scenario should be, I'm not convinced that the current test suite is working correctly.  It's possible to get error messages without the test registering as a failure.  Also, I'm not convinced that most of the existing modules will pass the test I've described above, even if they can pass the current one.  The question is, if we fix up the test now, including putting in a sensible time shifted scenario, what is our strategy for handling modules that were previously thought to be done but which start failing when we include a sensible time shift test?

**Comment by rplzzz** [comment]
@bpbond Let me see what I can do with it.  To be honest, I've not had good success with `complete` in any circumstance, and the documentation for that function is maddeningly vague.  (Pro-tip:  if you're going to describe a function as "a wrapper around" some other functions, you should at least give the equivalent sequence of calls to the other function.)  We might be better off just to forget about `complete` and use `crossing`, `nesting`, and `join` directly.

**Comment by bpbond** [comment]
>the main source of our problems is that we are making HISTORICAL_YEARS do double duty
>What we should do instead is to have code that handles raw inputs produce a time series from the existing historical and future scenario data.

I basically agree. Right now no chunk can be confident of what years are, or aren't, in its input data. We'd like a layer/step that guarantees that all data are complete throughout (e.g.) `HISTORICAL_YEARS` and smoothly transition to `FUTURE_YEARS`. Any subsequent chunks then don't have to worry about this issue.

>It's possible to get error messages without the test registering as a failure. 

Yeah, I've fixed this in a branch.

>Let me see what I can do with it. To be honest, I've not had good success with complete in any circumstance, and the documentation for that function is maddeningly vague.

Thanks for looking. Agreed, `tidyr` documentation is very irritating.

**Comment by bpbond** [comment]
Brainstorming...we could require that all chunk outputs be tagged with a TIME_COVERAGE attribute that specifies what period (`HISTORICAL_YEARS`, etc.) it's guaranteed to cover. The test code could then check that data exist for every year in that period. That would force the initial handling chunk for any data to handle gaps.

**Comment by kvcalvin** [comment]
Good point @rplzzz. I guess when I was specifying the years I wanted to test. I meant that I wanted to ensure that the model will write out correct data for those years. That does put a different burden on the input data. I think in addition to the capabilities you point out I would also add that we need GCAM to have inputs to run annually to your list.

I agree that we probably don't need the model to extrapolate outside of the historical years, but we would want to be able to choose a different set of calibration years in the range defined by the historical data.

**Comment by kvcalvin** [comment]
Oh, and you are probably right that the current code wouldn't pass any test we come up with. I'd still be inclined to implement as soon as possible and have one of us fix the failing chunks. Then, we can force all future chunks to pass from the outset. This seems easier than us having to go through all 150 chunks at the end.

**Comment by bpbond** [comment]
Kate and I met about this, and have the following proposal:

* Chunks have to handle `HISTORICAL_YEARS` set to 1971-1975 and `FUTURE_YEARS` set to 1976-2000. This change to the `timeshift` test would address the hindcasting problem that was one of the big impetuses behind DSR, and doesn't require that chunks extrapolate beyond the end of history. We would need to make this change in a branch and then go through and fix chunks that fail this.

* Chunks have to produce annual data. This is trickier, both to detect and to reconcile with our `oldnew` test. So it might wait until after V1, i.e. until after we cut loose from the old data system.

**Comment by rplzzz** [comment]
To reconcile old-new testing with annual data, we just need to filter the new data set to just the years contained in the old before we run the test.

To detect failure to produce annual data, we need a new test, but there are two ways to go about it.  We could check to see that every year from 1971 - 2100 is in the year column.  E.g,
```
reqyrs <- seq(1971, 2100)
expect_true(all(reqyrs) %in% df$year)
```
This will pass as long as there is _something_ for each year.  It doesn't, however, verify that there is something for each category of id variables for each year.  To do that you would have to complete the data frame over years and check for any missing, but then we have to allow for the possibility that some categories are _supposed_ to be missing.  

I'd say the first version is a good start.  If a module produces some output for each year, then absent some willful attempt to circumvent the test, it's probably doing what we want.

**Comment by bpbond** [comment]
>we just need to filter the new data

It's not that simple, because there are datasets that aren't in the year/value long form, and may be in unpredictable forms. Could be done though.

>I'd say the first version is a good start.

Yes. It's not worth checking the full factorial for every year, particularly when there may well be edge cases when combinations are missing for some (valid) reason.
