### ISSUE TITLE
Some GCAM inputs have bad line endings.

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/gcamdata#39]
For example: [A12.U_curves](https://github.com/JGCRI/gcam-data-system-OLD/blob/master/energy-data/assumptions/A12.U_curves.csv).  You can't see it in the github interface, but this file has <CR> line endings (like you would find in Mac OS 9 and previous).  It also doesn't have a final newline. Where possible, when we encounter these we should convert to unix line endings (<LF>) and a final newline.

**Comment by bpbond** [comment]
When we're all done with the first translation effort, a simple script should be able to scan all the input files, read, and re-write them with standardized line endings.

**Comment by bpbond** [comment]
Note we may want to re-compress files using a standardized modern algorithm while we're at it. See discussion in #490 .

**Comment by bpbond** [comment]
Addressed by #860 .
