### ISSUE TITLE
Why are regular tests w/ round() failing on differences < 10^-9

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#391]
@rplzzz in #387 

>We should open a separate issue to figure out why the regular tests are failing on this one. I'm also a little concerned that changing the tests to signif instead of round causes so many other modules to fail.

We've seen this a lot. Tiny differences, but failure. Also, the `signif` versus `round` question.

**Comment by bpbond** [comment]
For example: in the new `L100.IMAGE_an_Feedfrac_ctry_C_Sys_Fd_Y.csv` file, this line gets written:

>Pork,Mixed,FodderHerb_Residue,bdi,9,1999,0.46349999999999997

The corresponding number in the old data system file is 0.4635. Rounding to three decimal places produces 0.463 and 0.464 respectively, causing a test failure.

**Comment by bpbond** [comment]
Or take Kate's `L124.nonco2_tg_R_grass_Y_GLU` example in #403 . The biggest difference between the old and new values is tiny, but the biggest difference between the rounded values is much larger. 

```
> summary(comb$value - comb$old.value)
      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
-4.974e-14 -8.700e-19  0.000e+00 -4.660e-18  8.700e-19  4.974e-14 

> summary(comb$round - comb$old.round)
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
0.00e+00 0.00e+00 0.00e+00 9.53e-08 0.00e+00 1.00e-03 
```

For example, here's one row

```
> comb[40836,]
# A tibble: 1 × 9
  GCAM_region_ID Land_Type    GLU  year Non.CO2  value old.value round old.round
           <int>     <chr>  <chr> <int>   <chr>  <dbl>     <dbl> <dbl>     <dbl>
1             19 Grassland GLU051  1973   NMVOC 0.0065    0.0065 0.007     0.006

> (comb$value - comb$old.value)[40836]
[1] 8.673617e-19
```

The numerical difference between the raw values is _tiny_ (they're written in the files as 0.0065 and 0.006500000000000001 respectively) but that's enough to cause a rounding difference and then failure using `expect_equivalent`. (These files also fail a call to `all.equal(..., tolerance = 1e-3)`.)

**Comment by bpbond** [comment]
It doesn't help to truncate the decimals in `L124.nonco2_tg_R_grass_Y_GLU` before writing it out; the test still fails.

I'm wondering if we should roll our own version of `all_equal` that (i) sorts the two data frames being compared, (ii) ensures they have identical dimensions, (iii) for each column in A verifies that it's identical with the corresponding in B (if non-numeric), or the difference/relative difference is below some small amount (if numeric).

**Comment by bpbond** [comment]
Basically, no matter the tolerances involved, with a big enough data set there will always be some pair of numbers that fall on either side of any rounding line.

**Comment by rplzzz** [comment]
@bpbond I understand why rounding before comparing causes spurious failures.  I don't understand why `all.equal` is failing; it seems to work for me.
```
> x1 = 0.0065
> x2 = 0.006500000000000001
> x2-x1
[1] 8.673617e-19
> all.equal(x1,x2, tolerance = 1e-3)
[1] TRUE
```
Strangely `all_equal` doesn't work.  I don't know why that would be.
```
> dplyr::all_equal(x1,x2, tolerance = 1e-3)
[1] "Rows in x but not y: 1. Rows in y but not x: 1. "
```
One issue may be that `all_equal` doesn't seem to support the `tolerance` parameter, but I don't know what the default tolerance is.  Surely it's got to be bigger than 1e-18.
