### ISSUE TITLE
Circle back to L100.Population_downscale_ctry

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#402]
Lines 104-124 in this chunk reshape the data several times and use hard-coded years to fill in missing values.  It seems like there should be a way to do this more cleanly and robustly.

**Comment by russellhz** [comment]
Is a for-loop OK here? @d3y419 wrote a fairly compact (5-10 lines of code) one that works. I can't think of any other painless way to do it, since we need to first fill in 1990, then use that corrected 1990 value to fill in 1850, etc down to 1700.

**Comment by bpbond** [comment]
Go for it. More important, I think, is to remove the hard-coded years.
