### ISSUE TITLE
Hydro - replacing values in 2020 in favor of calculating them

### ISSUE THREAD

**Issue by aarony2j** [JGCRI/gcamdata#406]
<update> This issue is about two things (and are described in further detail below) regarding the PR #404 (LA.118.Hydro):
1) deciding whether 2020 should be dropped before interpolating future values
2) whether to use the regional detail of A18.hydro.ouput to calculate values (which is how its done now) instead of using the global total and using the country allocation already determined (I think that's what Sonny inferred)
@pkyle it'd be nice to get your input on this...thanks!

----
Ben suggested I open an issue on this so we can revisit whether 2020 values should be dropped in favor of calculating hydro potentials. They would be replaced by interpolating between 2010 and whatever future value is available. The justification in the original comments was that 2020 values are generally lower than 2010 in many regions.

Below is the old code. What do you think?

#Interpolate any between years, and use the final year as a proxy for years thereafter
**#Drop 2020 because it is lower than 2010 in many regions**
L118.out_EJ_RG3_elec_hydro_Y <- L118.out_EJ_RG3_elec_hydro_Y[ names( L118.out_EJ_RG3_elec_hydro_Y ) != "X2020" ]
L118.out_EJ_RG3_elec_hydro_Y <- gcam_interp( L118.out_EJ_RG3_elec_hydro_Y, future_years, rule = 2 )[
      c( "region_GCAM3", X_final_historical_year, X_future_years ) ]

**Comment by skim301** [comment]
Also, I find it odd that we have a bottom up approach to calculating hydropower production, but then continue to match old GCAM 3.0 values.

**Comment by skim301** [comment]
sorry wrong button

**Comment by aarony2j** [comment]
Are you saying to use the global value from A18.hydro and allocate it according to the country's global share instead of its region share? That makes sense to me.

Also, here's the table in question if it helps with the decision process of whether to drop 2020. (or maybe its a moot point if the global value is used) Here's the global value (2020 is lower than 2010)
````2010`   `2020`  `2035`   `2050`   `2065`   `2080`   `2095`
*    <dbl>    <dbl>   <dbl>    <dbl>    <dbl>    <dbl>    <dbl>
1 12.37494 12.13006 13.9882 15.84634 17.70448 19.56262 21.42076```

Here's the full table by region:
```region_GCAM3    `2010`    `2020`     `2035`     `2050`     `2065`     `2080`     `2095`
*                <chr>     <dbl>     <dbl>      <dbl>      <dbl>      <dbl>      <dbl>      <dbl>
1               Africa 0.3795408 0.3267648 0.65408832 0.98141184 1.30873536 1.63605888 1.96338240
2         Australia_NZ 0.1338588 0.1409616 0.16244575 0.18392990 0.20541406 0.22689821 0.24838236
3               Canada 1.2653280 1.3947259 1.47335809 1.55199030 1.63062251 1.70925472 1.78788693
4                China 2.7473616 2.6617521 2.97499724 3.28824243 3.60148762 3.91473281 4.22797799
5       Eastern Europe 0.2930544 0.2451996 0.28816790 0.33113621 0.37410451 0.41707282 0.46004112
6  Former Soviet Union 0.8793180 0.9743107 1.16415625 1.35400182 1.54384739 1.73369296 1.92353853
7                India 0.4119264 0.4017153 0.59156082 0.78140639 0.97125196 1.16109753 1.35094310
8                Japan 0.2959632 0.2815596 0.29105188 0.30054416 0.31003643 0.31952871 0.32902099
9                Korea 0.0132552 0.0132228 0.02271508 0.03220736 0.04169963 0.05119191 0.06068419
10       Latin America 2.6318450 2.6104191 2.99285089 3.37528263 3.75771437 4.14014612 4.52257786
11         Middle East 0.0641268 0.0763020 0.17122478 0.26614757 0.36107035 0.45599314 0.55091592
12      Southeast Asia 0.3714264 0.3074832 0.44986738 0.59225155 0.73463573 0.87701990 1.01940408
13                 USA 0.9441576 0.9808092 0.99391457 1.00701994 1.02012530 1.03323067 1.04633604
14      Western Europe 1.9437766 1.7148312 1.75779950 1.80076781 1.84373611 1.88670442 1.92967272```

**Comment by bpbond** [comment]
AUGH! MY EYES! ...I put those numbers into a table for sanity's sake.

**Comment by aarony2j** [comment]
lol. i tried using backticks and then stopped trying...

**Comment by pkyle** [comment]
Yeah, the basic method here involves jumping through hoops in order to preserve prior GCAM assumptions; hydro's always been a bit of an after-thought. The reason why the 2020 values are lower than the present-day is that I estimated them in about 2008, based on dams that were actively under construction at the time and large enough to have references on-line. Anyway going forward there are a lot of different methods that would be an improvement and could be considered here.

**Comment by aarony2j** [comment]
Thanks. So for the downscaling, do you think its best if we remove the intermediary and calculate country share from global data?

And for 2020, should I calculate 2020 values with more recent data? If not, what's the next step?

**Comment by pkyle** [comment]
No, I don't think I'd do that--for now I'd say just replicate the method that's there, and just leave a note that it's something we should take a second look at, and maybe suggest an alternative or two? For coming up with hydropower projections, I would want to do more than just downscale global assumed energy generation to countries on the basis of economic/technical potential and present-day production. It isn't as if all countries develop at the same rate.
And we should also make a point of including the massive dams currently under construction into the near-term (e.g. Grand Inga, Lower Mekong).

**Comment by aarony2j** [comment]
@skim301 Hi Sonny. As a reviewer of LA.118.Hydro #404, what exactly do I need to do to wrap this up? I'm under the impression that the code for now should replicate the old method (i.e., exclude 2020 values, downscale to region). Should I include a note in the comments of the chunk to take a second look at it later? Thanks.

**Comment by bpbond** [comment]
Can/should this issue be closed?

**Comment by skim301** [comment]
Yes, lets close the issue for now. The DSR code has been committed with previous behavior.
