### ISSUE TITLE
LA1321.Cement - AJS

### ISSUE THREAD

**Issue by aarony2j** [JGCRI/gcamdata#407]

**Comment by aarony2j** [comment]
@bpbond Hi Ben, can you make this file(s) available? Thanks!

**Comment by aarony2j** [comment]
@bpbond This was a bit confusing. Can you make available LA1321.Cement from GCAM-USA? You released LA1321.cement from Energy. Thanks!

**Comment by bpbond** [comment]
Sorry about that!

**Comment by bpbond** [comment]
I have you currently working on LA114.wind-energy; is that incorrect? I mean, is that "in progress", is this, or both? Thanks. -B

**Comment by aarony2j** [comment]
Thanks. Yeah, I'm still doing wind, but I had started cement in the meantime yesterday before wind was assigned. Would you rather not have me work on two at once? Maybe I need to be more diligent on getting an upnext ready to go, because I'd rather not have downtime when I have time and interest to work  on this.

**Comment by bpbond** [comment]
No, whatever works for you is fine!
