### ISSUE TITLE
Missing units and source for A23.globalinttech.csv

### ISSUE THREAD

**Issue by swd-turner** [JGCRI/gcamdata#415]
Sixth column appears to be a cost. Assume it's USD, but need to know year (difficult to discern from chunk #410 on the old data system as the cost variable doesn't seem to be used there).

Also, is there a source for these assumptions?

```
# File: A23.globalinttech.csv
# Title: Electricity sector intermittent technology information
# Units: ?? for 'backup.capital.cost', Unitless for 'backup.capacity.factor', Unitless for 'capacity.limit'
# Source: ??
supplysector,subsector,technology,electric.sector.name,trial.market.name,backup.capital.cost,backup.capacity.factor,capacity.limit,minicam.energy.input,minicam.non.energy.input,flag
electricity,wind,wind,electricity,renewable,36,0.05,0.35,backup_electricity,backup-cap-cost,BackupEnergy
electricity,solar,PV,electricity,renewable,36,0.05,0.25,backup_electricity,backup-cap-cost,BackupEnergy
electricity,solar,CSP,electricity,renewable,36,0.05,0.25,csp_backup,backup-cap-cost,BackupEnergy
elect_td_bld,rooftop_pv,rooftop_pv,electricity,renewable,36,0.05,0.25,backup_electricity,backup-cap-cost,BackupEnergy
```

@bpbond can you assign the relevant person?

**Comment by pkyle** [comment]
All of these parameters are just GCAM assumptions; there's no external source.
backup.capital.cost: Unit: 1975$/kW/yr. Description: Annualized capital cost per kW of backup capacity that intermittent renewable technologies may be required to purchase to ensure electricity supply reliability.
backup.capacity.factor: Unitless. Description: assumed capacity factor of purchased backup capacity.
capacity.limit: Unitless. Description: mid-point of backup capacity requirement curve, an s-curve describing the amount of backup capacity required per unit of installed capacity of the given technology.

**Comment by swd-turner** [comment]
Thanks!

**Comment by bpbond** [comment]
Sounds like this can be closed.
