### ISSUE TITLE
Update state-level data for value of cement shipments?

### ISSUE THREAD

**Issue by aarony2j** [JGCRI/gcamdata#416]
Regarding chunk LA1321.Cement in GCAM-USA, the state allocation is calculated to be in proportion to the value of cement shipments. The data is from 2008, and I thought we might as well update it.

However, I was surfing through the industry data from the U.S. Census Bureau, but couldn't find where the data came from. @pkyle or @gokuliyer can you help me with that. Is this even worth it?

**Comment by rplzzz** [comment]
If it were me, I'd defer changes of this sort until after the translation is complete.  Also, note that any such change will require a core model proposal.

**Comment by bpbond** [comment]
FWIW I agree, and am putting this in the "Version 2.0" milestone for now. Up to you all though!

**Comment by pkyle** [comment]
Agreed that it's not necessary for the present endeavor, but for the state-level value of shipments, I think @rhoesly would know where specifically on the Census website (if an updated dataset is available), as she's working on implementing the detailed US industrial module.

**Comment by pkyle** [comment]
Also FWIW, the value of shipments of NAICS 3273 might not be the best way to do this--there are only something like 20 cement factories in the whole US, whereas concrete mixing plants are ubiquitous (there's even one in DC!). So we've probably got the cement manufacturing energy mis-allocated with the current approach, and if you just google cement factories in the US, that might be better/quicker.
