### ISSUE TITLE
LA1321.Cement (gcam-usa)

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#421]
Somehow an issue didn't get created when @aarony2j started this. Just for completeness, opening this.

**Comment by aarony2j** [comment]
what about this issue? #407 Maybe because I had it "up next"?

**Comment by bpbond** [comment]
Argh.

**Comment by bpbond** [comment]
Re-opening and assigning to @kdorheim .

**Comment by bpbond** [comment]
I can't believe I screwed this up AGAIN. Closing.
