### ISSUE TITLE
Units in GFED forest fire data are unknown.

### ISSUE THREAD

**Issue by rhoesly** [JGCRI/gcamdata#426]
I have no idea what the units are.

In practice this is OK, because the data system uses GFED emissions to derive a percentage of forest fire (vs deforestation) of total emissions, then uses that percentage on RCP data (a different file) to estimate emission factors. 

Comparison of GFED data in the system to other forest fire data yields no answer. Below is a figure comparing GFED data in the gcam system to Van Marle et al 2016 (update forest fire emissions) for Indonesia, BC, deforestation emissions. Van Marle data is shown in kt BC.  The two data sets clearly estimate the same trend, but are on different axes. There is no clear conversion from Van Marle data to GFED data. GCAM data is, on average over the trend, 400 times the value of Van Marle data. It's clearly not a metric conversion, and units of BC verses units of BC as C are usually very similar.

![deforestation](https://cloud.githubusercontent.com/assets/13525812/26369680/6301d5ca-3fc3-11e7-809c-e062df256608.png)

**Comment by rhoesly** [comment]
@ssmithClimate @kvcalvin

**Comment by ssmithClimate** [comment]
Correct. We actually still use GFED, but its updated data in file:
`FILE = "emissions/CEDS/GFED-CMIP6_LUC_emissions",`
(CEDS is anthropogenic not including fires.) That LULUC file is generated exogenously by a chunk of code that is in a separate JIRA repository. (I believe that repo has the name LULUC in it.)
