### ISSUE TITLE
Downscaling IEA "other" countries should use energy statistics instead of population

### ISSUE THREAD

**Issue by ssmithClimate** [JGCRI/gcamdata#437]
Routine currently downscales IEA "other" country (e.g. OtherAsia, etc.) energy to individual countries using population. Either CDIAC or UN energy statistics can be used to do this more accurately. Downscaling fossil fuel consumption using CDIAC has already been implemented in the CEDS project (and downscaling using UN energy data will be added soon, including production statistics). Consistent downscaling of secondary energy (e.g. electricity, refining) would need to be added, and then this could then be ported to GCAM after the DSR is finished.

Also, Puerto Rico is inconsistently treated in the IEA energy data (which has a small impact on calibrating GCAM-USA energy use). We will try to correct for this in CEDS as well.

**Comment by rplzzz** [comment]
I've renamed this, since it pertains to a future enhancement, rather than to converting this file to the new system.

**Comment by russellhz** [comment]
Moved this to JIRA (JGCRI-439) and closing here
