### ISSUE TITLE
Need to clearly distinguish the kinds of time series chunks are producing

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#455]
Right now we conflate two things: historical time series and time series that match `HISTORICAL_YEARS`. Generally we want to produce continuous historical (small h) time series early in the data system, and only filter to the GCAM HY later on. 

For example, currently `L100.GDP_hist` filters its output (historical GDP) to HY, but this causes downstream problems if, for example, our definition of HY changes.

**Comment by pkyle** [comment]
The intention behind `HISTORICAL_YEARS` was to set common years that could potentially be model calibration years in GCAM. Wasn't intended to be all historical years in a general sense. So maybe just a problem of naming and/or documentation? The reason why the Big Bang is in 1971 is that it's the first year that the IEA has stats on developing nations.

**Comment by bpbond** [comment]
Hey @pkyle in your view are these expanded comments correct, in terms of how they define these time constants? cc @abigailsnyder @pralitp 

```R
 # Historical years for level 1 data processing. All chunks are required to 
# fill this period, i.e. producing annual data that covers this entire span.
HISTORICAL_YEARS        <- 1971:2010

 # Future years for level 1 data processing. A few chunks use this to 
# produce future data, e.g. 21st century XXX
FUTURE_YEARS            <- 2011:2100

# Calibrated periods in the model. Only level 2 chunks should reference these
MODEL_BASE_YEARS        <- c(1975, 1990, 2005, 2010)

# Future (i.e. not calibrated) periods in the model.  Only level 2 chunks 
# should reference these
MODEL_FUTURE_YEARS      <- seq(2015, 2100, 5)
MODEL_YEARS             <- c(MODEL_BASE_YEARS, MODEL_FUTURE_YEARS)
```
Are these comment (above) correct, in terms of defining the difference

**Comment by pkyle** [comment]
# Historical years for level 1 data processing. All chunks that produce
# historical data for model calibration are required to cover this entire span.

# Future years for level 1 data processing, for the few chunks that
# produce future data (e.g., population projections)

**Comment by pkyle** [comment]
Ha, that's hard to write comments that start with a `#`! That means something in Markdown!
