### ISSUE TITLE
Remove FLAG_NO_TESTs once we jettison old data system as baseline

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#457]
E.g. in `L100.GDP_hist` - see #456 .

**Comment by bpbond** [comment]
Removed this NO_TEST in #456. But the larger issue still applies; we'll also want to remove FLAG_SUM_TEST too I think.

**Comment by bpbond** [comment]
This involved removing ALL old comparison data, including outputs no longer produced by the data system.

**Comment by kdorheim** [comment]
For this issue will we also remove the FLAG PROTECT FLOAT?

**Comment by bpbond** [comment]
Yes I think so.
