### ISSUE TITLE
May want to use 2000 SAGE cropland and pasture dataset

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#461]
Which is consistent with cropland data layer.

Per phone conversation with Alan Di Vittorio.

**Comment by russellhz** [comment]
@bpbond @kanishkan91 has this already been done in Morai? Can we close this issue?

**Comment by bpbond** [comment]
I don't know, so will defer to Kanishka.

**Comment by kanishkan91** [comment]
@russellhz Yes. This has been completed. Refer to the updated inputs to moirai here - https://github.com/JGCRI/moirai
