### ISSUE TITLE
'set.market' parameter of write_to_all_regions

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#463]
Hey @pkyle the `write_to_all_regions` function has a `set.market` parameter:

```R
 write_to_all_regions <- function( data, names, has.traded=F, apply.to = "selected", set.market = F ){
  ...
  if ("market.name" %in% names ) data_new$market.name <- data_new$region
  if( has.traded==T){
    if( set.market==T){
      data_new$market.name <- data_new$region
    }
    data_new <- set_traded_names( data_new, apply.to )
  }
```

So `market.name` is going to be set to `region` regardless of the value of `set.market`? What's the intended logic here? Thanks.

**Comment by pkyle** [comment]
Sorry this is confusing. Basically, set.market tells the function whether to add an additional column called "market.name" to the table, and if used, the market names will be set to the region names at the time that this is called. Note that this is performed before the `set_traded_names` function is called; that latter function will re-set every region name to the USA. In the end, when this is used, the table will have the region column set to "USA" in every row, whereas the market.name column will loop through the 32 regions.

**Comment by bpbond** [comment]
OK, thanks.
