### ISSUE TITLE
Metadata for LA154.transportation_UCD.R data

### ISSUE THREAD

**Issue by russellhz** [JGCRI/gcamdata#477]
I'm just looking for sources here. 

1. UCD_techs.csv & 2. UCD_ctry.csv : UC Davis? This has minicam stuff so I'm not sure if it's directly from them

3. calibrated_techs_trn_agg.csv

**Comment by pkyle** [comment]
The sources are the same for both--these are exogenous mapping files that we created for processing data developed by researchers at the UC Davis Institute for Transportation Studies for the GCAM model between 2011 and 2013. Just cite Mishra et al. 2013: Mishra, G.S., Kyle, P., Teter, J., Morrison, G.M., Kim, S., and Yeh, S. 2013. Transportation Module of Global Change Assessment Model (GCAM): Model Documentation, Research Report UCD-ITS-RR-13-05, Institute of Transportation Studies, University of California, Davis. https://itspubs.ucdavis.edu/wp-content/themes/ucdavis/pubs/download_pdf.php?id=1884

**Comment by bpbond** [comment]
@russellhz please close this issue when appropriate.
