### ISSUE TITLE
Revisit hardcoded 2010 year in L242.ssp34_pasture

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#502]
See discussion in #501

**Comment by kvcalvin** [comment]
@bpbond: the same chunk of code that exists in `L242.ssp34_pasture` with the hard-coded `2010` exists in my current chunk (L243.bio_trade_input). I may tackle this problem as a part of this chunk.

**Comment by russellhz** [comment]
Addressed in #1186
