### ISSUE TITLE
Remove data when max_reduction <= 0 in L201.en_nonco2?

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#511]
This chunk has the following comment in lines 130-131:

```R
    # Remove rows where we only have a value for one of max.reduction or steepness
    # TODO: is this what we want or should we raise an error? [from original code]
```

but then it does something else, filtering for positive values of `max_reduction` only:

```R
    L201.nonghg_max_reduction %>%
      full_join(L201.nonghg_steepness,
                by = c("region", "supplysector", "subsector", "stub.technology", "year", "Non.CO2", "ctrl.name")) %>%
      na.omit %>%
      # No need to include a GDP control when the max.reduction is zero
      filter(max_reduction > 0) ->
      L201.nonghg_gdp_control

    L201.nonghg_max_reduction <- select(L201.nonghg_gdp_control, -steepness)
    L201.nonghg_steepness <- select(L201.nonghg_gdp_control, -max_reduction)
```

Exactly the same logic is applied to the `L201.nonghg_max_reduction_res` and `L201.nonghg_steepness_res` outputs in lines 196-206 as well.

What should be happening here? Should an error be raised, or silently filter the data as now?

**Comment by pkyle** [comment]
@bpbond I never saw this, because of the timing of the change in my email account (I think I made the change a few hours after you opened this issue). Do you want for me to look into it, or is this code already committed so no need?

**Comment by bpbond** [comment]
Hey, thanks. The code was committed in #516 but question still stands–is the comment right, or the code, and what do we want to happen?

**Comment by pkyle** [comment]
Hard to say what is best here...the decision does have significant consequences for emissions/climate, but what we've got right now is reasonably defensible. What's happening is that different base datasets were used to generate the two parameters of the emissions control function (max-reduction and steepness). One of the two (steepness) omitted traditional biomass whereas the other included it. So the na.omit() call removes the control functions for traditional biomass use.
The problem with that approach is that reducing BC from cookstoves is and has been a significant priority in the international development community for the last decade, and these coefficients are likely falling in many places from the adoption of cleaner burning stoves. And as cookstoves account for something like 30% of global BC emissions, the question of whether we do or don't zero out the control functions is not trivial.
The flip side is that the assumed "max-reduction" levels, should we implement this function just by assigning a generic "steepness" level, are currently indefensible. BC, the key nonco2 here, has a max-reduction level of 100%, way higher than the cleanest burning cookstoves. But it's also unclear that GDP is really the correct driver of the change in the coefficients. In fact, the inverse might be true b/c development agencies tend to focus their programs on the poorest areas. Anyway, if we ever do activate these control functions on traditional biomass, we'll need to get something defensible for a max-reduction on BC and OC (the other gases aren't as important), look at and evaluate the output. Core model proposal.

**Comment by rplzzz** [comment]
To answer the question that Ben actually asked, I believe the code is actually doing what the comment says, albeit in a not quite obvious way.  If either steepness or max.reduction is missing in a row, that will trip the na.omit, causing the row to be dropped.  Thus, only rows that have both will be kept, as advertised.

The code _also_ drops rows where max.reduction == 0, which wasn't mentioned in the leader comment, but is explained in a comment further down.  

I think the lesson here is that the comment at the beginning of a pipeline call should explain _everything_ that the pipeline does and its purpose.  Inline comments in the pipeline should be used sparingly, if at all, and _only_ to note the purpose of a stage in the pipeline that contributes to the stated function of the pipeline in a non-obvious way.

**Comment by russellhz** [comment]
Closing this here - now a JIRA issue at JGCRI-440
