### ISSUE TITLE
duplication of EDGAR years

### ISSUE THREAD

**Issue by cahartin** [JGCRI/gcamdata#513]
in `constants.R` there are `EDGAR_YEARS` and `EDGAR_HISTORICAL` both with the same year range 1971:2008. 

Should they be different? If not, then do we need both?

**Comment by pkyle** [comment]
This is one data object named differently. I'd probably remove the object EDGAR_HISTORICAL and switch all uses of it in the code (looks like there's only one) to EDGAR_YEARS

**Comment by bpbond** [comment]
Corinne, could you fold this into #512 please? Search for any other uses of `EDGAR_HISTORICAL` in the system and change.

**Comment by cahartin** [comment]
@bpbond sure!

**Comment by cahartin** [comment]
addressed in #512
