### ISSUE TITLE
How to handle ag prod change levels for hindmost runs?

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#514]
@rynacui said in #505 :

>There is a section in L2051 for hindcasting runs: when the model's final base year is less than the final historical year, compute the ag prod change levels that will return the known yields during the historical time period.
It is not affecting the current outputs, just want to check whether we keep this part or not?

And then @kvcalvin tagged @rplzzz asking

>How do we want to handle things like this for hindcast purposes?

**Comment by kvcalvin** [comment]
Following up on this: for the two papers we have on hindcasting (one published and one under review), this is something we actually varied in the paper. We ran cases where the yields were set to match historical observations and cases where we forecasted future yields.
