### ISSUE TITLE
Data system output list getting large

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#522]
`driver() -> x` now results in a very large list, ~1.5 GB, and the data system rewrite is only half-ish done. Although this can be filtered for a task at hand (`x <- x[my_chunk("DECLARE_INPUTS")]`) it's a resource drain on the computer, and slows down e.g. building and reloading.

Most data objects are small but some are not:

![sizes](https://user-images.githubusercontent.com/1956468/27968458-1174d9e4-6315-11e7-81f5-cb7508963d94.png)

```
                              object      size
                               <chr>     <dbl>
1   L181.LC_bm2_R_C_Yh_GLU_irr_level  31774696
2              L101.EIA_use_all_Bbtu  34464936
3                  L100.FAO_ag_Imp_t  38558816
4               ag_Fert_IRR_MGMT.xml  41161368
5       L121.nonco2_tg_R_awb_C_Y_GLU  42106672
6                     energy/en_OECD  54737488
7     socioeconomics/SSP_database_v9  71300456
8                        EDGAR_gases  75422696
9  L1211.nonco2_tg_R_awb_C_Y_GLU_IRR  91842328
10                 energy/en_nonOECD 145154456
```
Possibilities:
1. Use factors in the largest tables. If they're heavily repetitive text that might save a lot.
2. Allow chunks to mark input data for deletion after being used. This would help with the IEA data in the list above.
3. Allow the driver to delete `FLAG_INPUT_DATA` objects that will no longer be used. This seems straightforward and would take care of four of the five biggest objects.
4. Data system backend could compress the largest objects. This would be transparent for the chunks, and apply to objects that are (i) large and (ii) accessed infrequently. https://stat.ethz.ch/R-manual/R-devel/library/base/html/memCompress.html
5. Data system backend could cache large objects on disk. This seems wasteful and slow.

Thoughts @rplzzz @pralitp @kvcalvin ?

**Comment by pralitp** [comment]
Huh, I was just thinking about this mostly around the compressing option.  About as far as I got is I should test this out and see the pros and cons (memory saved vs speed lost).

The delete options seem more likely to become more problematic (what if a user wanted to inspect those tables after the driver was done for instance) and so are more a secondary option in my opinion.

**Comment by bpbond** [comment]
@pralitp Thanks. I was thinking about the delete option particularly w.r.t. `en_nonOECD`, `en_OECD`, and `SSP_database_v9`, three of the five largest object, each of which is used exactly once by a single chunk and then never again.

**Comment by bpbond** [comment]
P.S. On my laptop it takes 4.6 seconds to `memCompress` a 1 GB object.

**Comment by bpbond** [comment]
I tested option no. 3 above, having the driver delete input files once they're no longer needed. This reduces the driver's current output from 1.5 GB to 1.1 GB. Nice, but not a panacea.

[prune.patch.zip](https://github.com/JGCRI/gcamdata/files/1133722/prune.patch.zip)

**Comment by rplzzz** [comment]
I have some ideas on this. We could talk about it if you're around today.

**Comment by bpbond** [comment]
After talking with @pralitp and @rplzzz , seems like the best option is to have the driver, by default, return no data at all. Users can request data be retained and returned (e.g. `return_data = c()`, `return_inputs_of = c()` and `return_outputs_of = c()`). Something like that. With this is place, the driver will be free to delete objects as it goes, i.e. when it knows they're no longer going to be needed (option 3 above, but applied universally).

**Comment by bpbond** [comment]
Presumably if a user uses the current `stop_before` option, that would imply `return_inputs_of` the same chunk by default; if they use the `stop_after` option, that implies `return_outputs_of`. So there's a logical symmetry there.

**Comment by bpbond** [comment]
This will improve things a lot. Here's the memory usage of the driver's data store over a run, for four cases: current (original), pruning file inputs as they become unnecessary, pruning all inputs as they become unnecessary, and pruning both input and outputs. In this last case, at the end of the run the data store is empty by definition.

![prune](https://user-images.githubusercontent.com/1956468/28070761-0f6091d4-661c-11e7-939f-7b5abe239cea.png)

**Comment by pralitp** [comment]
This looks great.  Given you put in the hooks to save the tibbles users explicitly want to keep around I say just go with prune_input_and_outputs.

One question though.  Did you take any precautions against cleaning up the `XML` objects too early?  If you recall we decided to not actually run the XML conversion in the batch chunks and instead do so in `save_chunkdata` only if the `write_outputs` was set to `TRUE` in the call to the `driver()`.

**Comment by bpbond** [comment]
@pralitp I think this is still OK, the way it done, but we'll see. Thanks.
