### ISSUE TITLE
Change column headings with "-" to "_" and spaces to "_"

### ISSUE THREAD

**Issue by CLynchy** [JGCRI/gcamdata#523]
Not important, but annoying?
Column headings in almost all the inst/extdata/emissions/EDGAR/ .csv files have dashes and spaces.  The examples are in `EDGAR_NOx.csv` and column headings are "IPCC-Annex" and "World Region".

Shouldn't the dash and space in the column headings be an underscore?  If I make changes to these files, I can't run the driver because other chunks use these files in their imperfect forms.

To get around calling these column headers in my chunk, I use the back-tick?

**Comment by bpbond** [comment]
Back tick: right, that's how to deal with this.

The problem with changing the column names by hand is that these aren't our files: they come from the [EDGAR database](http://edgar.jrc.ec.europa.eu), and if/when we get new versions in the future, don't want folks to have to figure out the hard way that we made fiddled with them. So, as much as it's a drag, need to deal with these issues programmatically.
