### ISSUE TITLE
Units/Source for A32.max_reduction.csv and A32.steepness.csv

### ISSUE THREAD

**Issue by russellhz** [JGCRI/gcamdata#526]
Don't know source for either of these.

Units:
-A32.max_reduction.csv: Is this max possible emissions intensity reduction? Does 80 mean 80% reduction or reduce to 80% of current?
-A32.steepness.csv: percent reduction per year?

**Comment by russellhz** [comment]
@kvcalvin @ssmithClimate @pkyle Not sure who the right person is for the emissions stuff

**Comment by bpbond** [comment]
In the recently merged ( #516 ), here's the header we gave `A51.steepness.csv`:
```
# File: A51.steepness.csv
# Title: Steepness of emissions reduction by supply sector, subsector, technology, and gas
# Units: Percentage
# Source: Internal
```

I _think_ 80 means 80% reduction, but you're absolutely right that this should be clarified. Also, what's the difference between A32.steepness and A51.steepness?

**Comment by pkyle** [comment]
A32.max_reduction: Maximum possible emissions intensity reduction, in percentage (i.e., 80 means 80% reduction from the base-year emissions coefficient).
A32.steepness: shape parameter of s-curve function that reduces the emissions coefficient as a function of the per-capita GDP. Note that you might want to correct this in the corresponding file A51.steepness (it's not a percentage).
Source (for both): Internal GCAM assumptions; sulfur reductions based on Smith et al. 2005, Future Sulfur Dioxide Emissions, Climatic Change 73, 267-318. DOI: 10.1007/s10584-005-6887-y

**Comment by pkyle** [comment]
@bpbond the two files are for urban and industrial process emissions (A32), and for all other emissions-producing activities (A51), including combustion-related emissions in industry. They correspond with the code chunks that are using them. The tables could potentially be merged (same column names) but I can't guarantee that the L232 and L251 code chunks would work correctly.

**Comment by bpbond** [comment]
@pkyle thanks. When you say A51 is "not a percentage" then what are its units?

**Comment by pkyle** [comment]
Here's the function, from gdp_control.cpp:
reduction = 1 - ( 1.0 / ( 1.0 + ( currGDP - baseGDP ) / mSteepness ))
The GDP parameters are in thousand 1990 US Dollars, and the resulting "reduction" is unitless, so I guess the units here are the same the GDP (thous 1990 USD)
