### ISSUE TITLE
Handling Basin Names in AgLU level 2 files

### ISSUE THREAD

**Issue by abigailsnyder** [JGCRI/gcamdata#531]
Hi all,
As we're working on the AgLU level 2 files, the issue of basin identification has come up. 

The level 1 data has basin identifiers like GLU007.
The level 2 data has basin identifiers like PacArctic.

So right now, we have to either join in the `basin_to_country_mappings` table for each relevant output (like Ryna's 2052 chunk), or we have to call the `replace_GLU` function. It seems like we should be consistent and choose one option.

This, however, has raised some additional questions for me, partially based on some of my experience testing the integration branch:
which type of identifier do we want to use, informative names or numbers? The more informative names are definitely more helpful for interpretation of results, but the GLU007 style basin names are easier for regular expression matching.

The competition nests in the land allocation system rely on the column AgProductionTechnology that has entries that look like Corn_PacArctic_IRR_hi. Therefore, with old DS style outputs, we have to separate on the underscores to extract basin, irrigation, and management information for different aggregations of interest (eg all Irrigated Corn in each Region). 

 `dplyr::separate` and regular expression matching both can do this (with varying degrees of ease), but with basin names like PacArctic, separation has to occur on the underscores (because basin names all vary in length and makeup). That means the crops Root_Tuber, biomass_grass, and biomass_tree get separated as well and if statements have to be used. (Crop names is a whole other issue I am going to open next for version 2). 
With names like _GLU007, separating out basin, irrigation, and management information is a little more straightforward.
In other words, basin names like PacArctic make for nicer to _understand_ GCAM outputs, but GLU007 makes for nicer to _process_ GCAM outputs

We are primarily concerned with "how do we do this right?" now that we're rewriting the data system (and still early in the aglu level 2 files). 

AgProductionTechnology columns can't be changed. So for me, the happy medium would be names like PacArctic for intuition and then, under an `if(OLD_DATA_SYSTEM_BEHAVIOR)`, add columns with separated out basin, irrigation, and management information. 
We would then have columns like
``` AgProductionTechnology   Basin   Irr   Mgmt```
``` Corn_PacArctic_IRR_hi   PacArctic IRR hi ```

Whether that would actually carry through to GCAM outputs is beyond me. 

So version 1 action item:
- [ ] decide how to handle the Basin Names in AgLU level 2 files (a join or the `replace_GLU` function)

- [ ] decide whether we want to output additional Basin, Irr, Mgmt columns in the level2 files. A key factor in this decision is whether that would carry through to GCAM ouputs. Or if the additional columns will break the xml files. Possibly a question for version 2.

**Comment by kvcalvin** [comment]
@abigailsnyder: I understand action item #1, but am not sure I understand #2. Did you want these extra columns to go into GCAM (and eventually to the GCAM database)? Or is this just for the level 2 files?

**Comment by abigailsnyder** [comment]
@kvcalvin for #2, I think we want these extra columns to go into GCAM (and eventually to the GCAM database). Right now, any aggregation of GCAM outputs to different combinations of region - basin - irrigation - management require separating out the AgProductionTechnology by either `dplylr::separate` or regular expression matching. With the crops Root_Tuber, biomass_grass, and biomass_tree right now, this is  super annoying to do. Having the additional columns for basin, irrigation, and management information can make post processing of outputs a lot easier, especially until those crop names are ultimately changed.

**Comment by kvcalvin** [comment]
Okay, that makes sense. But, I think we'll want this for version 2. Right now, GCAM wouldn't be able to read that in or do anything with it. It would probably be simple code to add, but it would require C++ code.

**Comment by abigailsnyder** [comment]
Got it. Ok  then just item 1 for now - we should all be consistent with how we handle the translation from Level 1 basin identifiers (GLU07) to Level 2 basin identifiers (PacArctic)

**Comment by rynacui** [comment]
I think there are also cases where the basin names include the underscore? But I could be wrong...Anyway, I feel the same pain of using `dplyr:separate` in the integration branch...
