### ISSUE TITLE
L2521.MAC_an identical to L252.MAC_an

### ISSUE THREAD

**Issue by russellhz** [JGCRI/gcamdata#546]
L2521.MAC_an is supposed to be created in zchunk_L2521.MACC_IRR.R. It is literally a copy of L252.MAC_an, which will come from chunk_L252.MACC.R

Do we need to carry this through?

**Comment by bpbond** [comment]
So (to make sure I understand): L252.MACC.R creates `L252.MAC_an`, which is then read by  L2521.MACC_IRR.R and written out, without change, as `L2521.MAC_an`. A comment in this latter says "these still need to be written out here" with no other information.

@pkyle Is there a reason we need to keep this duplication? Also cc'ing @kvcalvin

**Comment by kvcalvin** [comment]
@bpbond: I think this is because the animal MAC curves are put in the same xml as the ag MAC curves, which are modified in L2521. We are reading in the animal MAC curve so we can write it to the appropriate batch file. I would think this is unnecessary in the new system.

**Comment by pkyle** [comment]
Yeah that's correct--I just checked the batch_all_aglu_emissions.xml (emissions-processing-code/xml-batch in the old data system) and the following CSV files are combined in the same XML file:
		<headerFile>../_common/headers//ModelInterface_headers.txt</headerFile>
		<csvFile>../emissions-data/level2//L211.AWBEmissions.csv</csvFile>
		<csvFile>../emissions-data/level2//L211.AGREmissions.csv</csvFile>
		<csvFile>../emissions-data/level2//L211.AnEmissions.csv</csvFile>
		<csvFile>../emissions-data/level2//L211.AnNH3Emissions.csv</csvFile>
		<csvFile>../emissions-data/level2//L211.AGRBio.csv</csvFile>
		<csvFile>../emissions-data/level2//L211.AWB_BCOC_EmissCoeff.csv</csvFile>
		<csvFile>../emissions-data/level2//L211.nonghg_max_reduction.csv</csvFile>
		<csvFile>../emissions-data/level2//L211.nonghg_steepness.csv</csvFile>
		<csvFile>../emissions-data/level2//L252.AgMAC.csv</csvFile>
		<csvFile>../emissions-data/level2//L252.MAC_an.csv</csvFile>
		<outFile>../xml/emissions-xml//all_aglu_emissions.xml</outFile>
So, when we split out irrigated and rainfed in the ag emissions XML file, the animal ("an") files have to be copied too.

**Comment by bpbond** [comment]
Excellent! Thanks, both of you. Yay eliminating duplication.

**Comment by russellhz** [comment]
I am also coming across this with `L2111.AnEmissions` and `L2111.AnNH3Emissions` being identical to `L211.AnEmissions` and `L211.AnNH3Emissions`. These L2111 outputs are also inputs to `L2112.ag_nonco2_IRR_MGMT.R`, where they are just copied through again. 

`L2521.MAC_an` is also an input to `L2522.ag_MACC_IRR_MGMT.R`, where it is copied again.

Are we just removing this convention altogether because of our xml batch scripts?

**Comment by kvcalvin** [comment]
@bpbond: It seems like this file is part of a triplet and only the last (L2522) should be implemented in DSR.

**Comment by bpbond** [comment]
It does seem like it but (as we did in aglu) a clear, explicit decision needs to be made about how we're handling these triplets.

**Comment by kvcalvin** [comment]
If it helps make that decision, the xml files generated by L2521 won't run in GCAM without the files in aglu we decided not to make.

**Comment by bpbond** [comment]
@russellhz Is this clear guidance?

**Comment by russellhz** [comment]
Maybe? I had just been keeping the first one that was created (i.e. keeping only `L252.MAC_an`) and not any of the duplicates.

**Comment by bpbond** [comment]
@russellhz close this?

**Comment by cahartin** [comment]
@bpbond and @russellhz  what did we decide to do with this file? `L252.MACC`? it hasn't been converted yet.

**Comment by russellhz** [comment]
We decided to just use the first version of any copied output. So we would only use `L252.MAC_an`

**Comment by cahartin** [comment]
thanks! so then no need to edit `L252.MAC`? are we deleting that one?

**Comment by russellhz** [comment]
I'm not sure if we're on the same page here (all the names look the same, it's confusing for me to figure out what refers to what)

There is one repeated output in `L2521.MACC_IRR.R` and another in `L2522.ag_MACC_IRR_MGMT.R` that we don't need to create, but otherwise everything should be translated the same as normal.

**Comment by cahartin** [comment]
@russellhz thanks, i think i read the thread wrong.

**Comment by kvcalvin** [comment]
@bpbond: I'm assuming this one was fixed since GCAM runs, but please confirm.

**Comment by bpbond** [comment]
👍
