### ISSUE TITLE
A_MACC_TechChange.csv metadata needed (Units & Source)

### ISSUE THREAD

**Issue by russellhz** [JGCRI/gcamdata#548]
Here's what I currently have for the metadata. Is the tech change parameter just lowering the marginal abatement cost?

# File: A_MACC_TechChange.csv
# Title: MAC curve technology change parameters
# Description: Specifies SSP-specific tech change parameters for the MAC curves
# Units:?
# Source:?

**Comment by pkyle** [comment]
I wasn't the author of this file (@kvcalvin) but from looking at the C++ code, it looks like the tech change increases the portion of emissions abated for a given carbon price, with a maximum reduction rate of 100% (i.e., zero emissions). The data read in are unitless; it's just an annual increase in emissions reduction rates. See the last 15 lines of mac_control.cpp (in the integration/water-ssp branch).

**Comment by pkyle** [comment]
Oh and for source, it's just an exogenous assumption. So, whatever we're writing for assumptions that don't have a source I guess.

**Comment by kvcalvin** [comment]
There is actually more information on source. These rates were calibrated to match a paper. I'll look for the citation (I remember putting it in the commit message, but I guess we don't see those now).

**Comment by kvcalvin** [comment]
Here is the article: http://www.sciencedirect.com/science/article/pii/S1462901106001316

**Comment by pkyle** [comment]
Cool, thanks @kvcalvin !

**Comment by russellhz** [comment]
Thanks @pkyle and @kvcalvin!

I am just going to commit these changes with my pull request for #552
