### ISSUE TITLE
Why does set_water_input_name get very slow with larger data?

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#556]
See @rynacui 's comment in #551 

https://github.com/JGCRI/gcamdata/pull/551#discussion_r128099697

**Comment by russellhz** [comment]
I was not able to replicate this issue on my system (windows + R 4.1) or on pic with R 3.6 and 4.0, so I am going to close this. We could combine the function calls Ryna initially separated because of the slowdown, but they go to three separate outputs, so doesn't seem particularly important
