### ISSUE TITLE
Should emissions/A_regions be labeled as unitless?

### ISSUE THREAD

**Issue by russellhz** [JGCRI/gcamdata#559]
The `bio_N2O_coef` column seems like it should have a label. Maybe something/Mt?

This data is used in `L211.AGRBio` and `L2111.AGRBio` (which is why I was looking at A_regions for units)

**Comment by kvcalvin** [comment]
It does seem like it should have a unit. @pkyle - while I am guessing I added this, I have no recollection. Was there something like it in GCAM3 (which is what I was drawing from)?

**Comment by pkyle** [comment]
Those coefs are kgN2O per GJ of bioenergy crop. The USA value is estimated from the fertilizer application rates and yields in Adler et al. 2007 (Ecological Applications, 17(3), 2007, pp. 675–691), assuming that 2.25% of fertilizer-N is volatilized as N2O (from Davidson 2009; DOI: 10.1038/NGEO608). The other 14 regions are indexed to the USA based on their relative average N2O coefs, across all crops.

**Comment by cahartin** [comment]
thanks @pkyle !
