### ISSUE TITLE
L245.water.demand.municipal

### ISSUE THREAD

**Issue by mihejazi** [JGCRI/gcamdata#572]
@bpbond Could you please make sure this file is available for Sean to work on? Thanks.

**Comment by bpbond** [comment]
I made #571 as "in progress" and when that's done (it's super short, should take an hour) Sean can move on to this (longer and trickier file).

**Comment by bpbond** [comment]
Sean - not sure if you've done a 200-level file yet. Note that we're not, as in the original data system, generating the `logit_fn_tables` here, so there are parts of this chunk you can skip over. Talk to me, Russell, Pralit, Abigail if you have questions. Thanks!
