### ISSUE TITLE
Investigate codecov performance problems

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#581]
As noted in #580 , where it was disabled, the code coverage step of the CI (called from `coverage.R`) has gotten unusable; it's essentially never terminating, now, slowing everything down and resulting in false errors everywhere.

**Comment by bpbond** [comment]
FYI @rplzzz @kvcalvin @pralitp - and thoughts welcome.

**Comment by rplzzz** [comment]
Only thing I can think of is to run the coverage test locally and see if it finishes in a reasonable length of time.
