### ISSUE TITLE
Revisit method to set bio tree yields according to estimated forest primary productivity

### ISSUE THREAD

**Issue by rynacui** [JGCRI/gcamdata#594]
In #589  `L201.ag_For_Past_bio_input`, starting at line 209, a method to set bio tree yield according to estimated forest primary productivity is commented out, and "kept in case this issue is addressed".

For now, this part is ignored in the translation. Keep the code for later assessment:

`# the method below, commented out, would use carbon density-derived assumptions of forest yields in each land use region`
`# the problem with this method is that it isn't indexed to the value of agricultural land, unlike the assumed unmanaged land`
`# values (and also unlike the bio grass crop yields, which are derived from ag crop yields).`
`# This means that in places where ag land (and therefore unmanaged land) has low value, the bio tree crop profit rates are`
`# comparatively very high, and gain very high market share.`
`# the code to set bio tree yields according to estimated forest primary productivity is kept in case this issue is addressed`
`if( FALSE ){`
  `#Add info to table on bioenergy tree yields`
  `L123.For_Yield_m3m2_R_GLU$yield <- L123.For_Yield_m3m2_R_GLU[[X_final_historical_year]]`
  
  `#This contains zeroes in places without any logging in the final historical year. replace with an assumed minimum value`
  `L123.For_Yield_m3m2_R_GLU$yield[ L123.For_Yield_m3m2_R_GLU$yield == 0 ] <-
    min( L123.For_Yield_m3m2_R_GLU$yield[ L123.For_Yield_m3m2_R_GLU$yield != 0 ] )`
  
  `#Also need to re-set yields in places where roundwood production compared with available forest land returns unrealistically high yields`
  `# could happen either from bad data, or from places with unsustainably high logging rates in the final historical year`
  `L123.For_Yield_m3m2_R_GLU$yield <- pmin( L123.For_Yield_m3m2_R_GLU$yield, quantile( L123.For_Yield_m3m2_R_GLU$yield, probs = 0.8 ) )`
  `L201.ag_bioTreeYield_GJm2_R_GLU <- L123.For_Yield_m3m2_R_GLU[ c( R_C_GLU, "yield" ) ]`
  `L201.ag_bioTreeYield_GJm2_R_GLU$Yield_GJm2 <- L201.ag_bioTreeYield_GJm2_R_GLU$yield * AvgWoodDensity_kgm3 * WoodEnergyContent_GJkg`
  `L201.ag_bioTreeYield_GJm2_R_GLU <- add_region_name( L201.ag_bioTreeYield_GJm2_R_GLU )`
  `L201.ag_bioTreeYield_GJm2_R_GLU[[C]] <- bio_tree_name`
  `L201.ag_bioTreeYield_GJm2_R_GLU[[agsubs]] <- paste( L201.ag_bioTreeYield_GJm2_R_GLU[[C]], L201.ag_bioTreeYield_GJm2_R_GLU[[GLU]], sep = crop_GLU_delimiter )`
  
  `#Match in the supply sector second, in case it's a different commodity (as opposed to a different subsector)`
  `L201.ag_bioTreeYield_GJm2_R_GLU[[agsupp]] <- A_AgSupplySubsector[[agsupp]][ match( L201.ag_bioTreeYield_GJm2_R_GLU[[C]], A_AgSupplySubsector[[agsubs]] ) ]`
  
  `#Biomass tree yields`
  `L201.AgYield_bio_tree$yield <- round( L201.ag_bioTreeYield_GJm2_R_GLU$Yield_GJm2[
    match( vecpaste( L201.AgYield_bio_tree[ c( reg, agsupp, agsubs ) ] ),
           vecpaste( L201.ag_bioTreeYield_GJm2_R_GLU[ c( reg, agsupp, agsubs ) ] ) ) ],
    digits_calOutput )`
  `L201.AgYield_bio_tree <- L201.AgYield_bio_tree[ names_AgYield ]`
`}`

**Comment by rynacui** [comment]
#589

**Comment by russellhz** [comment]
Moved to JIRA (JGCRI-443)
