### ISSUE TITLE
L161.SSP2_EF drops region 25

### ISSUE THREAD

**Issue by russellhz** [JGCRI/gcamdata#596]
#576 
Regions in L161.SSP2_EF are assigned emissions factors based on income level and policy in the following categories:
1. Highmed income and strong policy
2. Highmed income and weak policy
3. Low income

Policy is applied based on elec_coal emissions factor.
Region 25 is the only highmed income region with no elec_coal emissions factor, so it gets dropped from the output since it does not fit into any of the 3 categories above.

How should this be handled in the new data system?

**Comment by pkyle** [comment]
Forwarding to @kvcalvin (I did neither emissions nor SSPs)
My one note that I can contribute (maybe irrelevant and maybe not) is that this is the Venezuela+ region, which has abundant coal, but most of their power comes from hydro, and they've never built a single coal power plant. They use coal for industrial purposes, and they export it. As for the strength of the policy in the future, depends on how the revolution plays out!

**Comment by bpbond** [comment]
Since Kate's not back for 3-4 weeks, though, why don't we replicate old data system (dropping region 25) until then. I'll flag this is a bug and assign to her.

**Comment by kvcalvin** [comment]
Hmm...I'll have to think about what to do here. My memory is that the SSP protocol said to divide countries based on their coal emissions factor. I'll look back to see if there was any guidance on what to do when there wasn't a coal emissions factor. But, for now, replicating core and flagging this as an issue seems right.

**Comment by bpbond** [comment]
Do we want to fix this for version 1? Or punt to version 2?

**Comment by pkyle** [comment]
I'd say punt--just in checking the model output, coal_elec in Venezuela+ accounts for less than 0.001 Tg/yr of all of the major primary non-CO2s (SOx, NOx, CO, BC). That's for the reference scenario; would be less in a policy scenario. Given the magnitudes involved, I can't really see anyone nailing us on having the "wrong" emissions factor here.

**Comment by kvcalvin** [comment]
I agree with Page. The EF arose from following the SSP protocol and changing it will have a pretty small effect. I think we can deal with this in the next round.

**Comment by bpbond** [comment]
Sounds good--thanks.

**Comment by kvcalvin** [comment]
This one was fixed in #1016
