### ISSUE TITLE
Trucks in China - size classes

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#602]
Email from @sypnl August 3, 2017: 

>We recently looked at transport results for China and found that two types of size classes co-exist for trucks (see below). This is because in the UCD model size classes for Hong Kong and Macau are different from mainland China, so when you merge these three regions into China, there are different types of size classes in the China region. Other large regions with multi-countries might also have this problem. This doesn’t bother us after we found out why, however it might confuse others. I’m not sure if you want to fix this in the DSR process, but think it would be helpful to let you know. 

Freight | Truck | Truck (>14t)
-- | -- | --
Freight | Truck | Truck (0-2t)
Freight | Truck | Truck (0-6t)
Freight | Truck | Truck (2-5t)
Freight | Truck | Truck (5-9t)
Freight | Truck | Truck (6-14t)
Freight | Truck | Truck (9-16t)

**Comment by d3y419** [comment]
or more generally, we may want to consider simplifying this. 
I suggest we model this with small/medium/large trucks for all regions.
