### ISSUE TITLE
LA114.wind needs some cleanup

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#606]
Comments originally by @rplzzz :

1. The functions on lines 173 and 209 are way too long to be anonymous functions.  They should be pulled out and documented.

2. We should also consider pulling the inner functions at the beginning of the chunk out and documenting them.  They don’t make closures, so there isn’t really any reason to define them inside of the chunk.

3. ~Some of the inner functions make local data frames for no good reason.  As a result, we do a lot of gc in this chunk.~ (This is being handled in #604 )

4. Long-term: do we really need to create this data at all?  All of it can be calculated analytically, so maybe the best thing is to just have other chunks call those functions as required.

**Comment by russellhz** [comment]
Closing this, as none of these comments seem to apply to the latest version (mostly done in ebd927f1111dba504c0fe239077565a1caf220fd, but also in other commits as well). As to the last point about whether it needs to be done at all,  the output is used in two downstream chunks and I don't see how it would be more transparent to move all of the calculation into module-helpers functions.
