### ISSUE TITLE
Sources for LA161.Cstorage input data

### ISSUE THREAD

**Issue by aarony2j** [JGCRI/gcamdata#616]
Hi @pkyle. Can you help with sourcing the input data of this chunk? Or recommend someone who can? This was brought up in Aaron - L261.Cstorage #608.

I'll try and paste the tables here. (Sorry in advance for the formatting.) Some may be easy like share weight of 1 because there are no alternatives (last three tables). Thanks.

File: A61.rsrc_info.csv 
Title:   Carbon storage resource info 
Units: MtC   for output unit; 1990$/tC for price unit; unitless for capacity factor

resource | resource_type | market | output-unit | price-unit | capacity.factor | subresource
--- | --- | --- | --- | --- | --- | ---
offshore carbon-storage | unlimited-resource | global | MtC | 1990$/tC | 0 | 
onshore carbon-storage | depresource | regional | MtC | 1990$/tC |   | onshore carbon-storage

File: A61.sector.csv
Title:   Carbon storage supplysector info 
Units: MtC   for output unit; 1990$/tC for price unit; unitless for logit exponent

supplysector | output.unit | input.unit | price.unit | logit.exponent | logit.type
--- | --- | --- | --- | --- | ---
carbon-storage | MtC | MtC | 1990$/tC | -6 | absolute-cost-logit

File: A61.subsector_logit.csv
Title:   Carbon storage subsector logit exponents
Units:   Unitless for logit exponent

supplysector | subsector | logit.exponent
--- | --- | --- 
carbon-storage | onshore carbon-storage | -6
carbon-storage | offshore carbon-storage | -6

(Maybe this is because there is no alternative? No source needed, only an explanation?)
File: A61.subsector_shrwt.csv
Title:   Carbon storage subsector shareweights
Units:   Unitless for share weight

supplysector | subsector | year.fillout | share.weight
--- | --- | --- | ---
carbon-storage | onshore carbon-storage | start-year | 1
carbon-storage | offshore carbon-storage | start-year | 1

(same as above)
File: A61.globaltech_coef.csv
Title:   Carbon storage global technology coefficient
Units:   Unitless

supplysector | subsector | technology | minicam.energy.input | 1971 | 2100
--- | --- | --- | --- | --- | ---
carbon-storage | onshore carbon-storage | onshore carbon-storage | onshore carbon-storage | 1 | 1
carbon-storage | offshore carbon-storage | offshore carbon-storage | offshore carbon-storage | 1 | 1

(same as above)
File: A61.globaltech_shrwt.csv
Title:   Carbon storage technology shareweight
Units:   Unitless

supplysector | subsector | technology | 1971 | 2100
--- | --- | --- | --- | ---
carbon-storage | onshore carbon-storage | onshore carbon-storage | 1 | 1
carbon-storage | offshore carbon-storage | offshore carbon-storage | 1 | 1

**Comment by pkyle** [comment]
None of these tables have any data source, or require an explanation different from any other generic sector, resource, or technology in the model. If you want to maintain consistency with what others have written for other sectors, you can just check what people have been writing for this sort of information (just scan the input data for the relevant strings, e.g., "shrwt", "rsrc_info", "sector"). One thing to note here is that the "coef" parameter, or input-output coefficient, is often used to indicate some sort of transformation, and in those cases typically has a number other than 1. Here these are "pass-through" technologies; there is no transformation, so the IO coef is 1.

**Comment by bpbond** [comment]
Why assigning this to me @aarony2j ?

**Comment by aarony2j** [comment]
Thanks @pkyle . @bpbond , I didn't see any better ways other people have addressed these tables. The couple files I've seen with logit data have no source. Is it okay to leave as is? Or please suggest what to do.

**Comment by bpbond** [comment]
I think fine to leave as is.
