### ISSUE TITLE
VERSION 1 CHECKOFF - MODELTIME

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#619]
Verify that

- [x] new data system produces exactly same `modeltime` XML files as old data system
```
batch_hector.xml
batch_magicc.xml
batch_modeltime.xml
```
- [x] structure of files matches

- [x] contents of files matches (we assume true for data, based on `oldnew` test)

- [x] GCAM runs with these files substituted in

**Comment by bpbond** [comment]
This and socioeconomics are the two areas already done, and because they're small, they're handy test cases. I'm assigning (if I may) this to us as the DSR XML lead and modeltime lead, respectively. (Modeltime was the very first thing done in DSR, before we had teams or leads.)

**We'd like to declare them officially done for Version 1**: producing exactly the same XML files as the old data system. (Not exactly: we have made some changes, there's numerical precision issues, etc.) I'm hoping that Pralit has time to check the XML files, and work with me to resolve any problems.

**Comment by pralitp** [comment]
@bpbond, given these files are exactly the same do we really need to run them through GCAM or can we just mark this good to go?

**Comment by bpbond** [comment]
@pralitp Up to you. I was just thinking that's the acid test, so to speak. But you're in charge of this final certification process, and if you think not worth it, fine.

**Comment by pralitp** [comment]
Maybe for just these.  For other modules it will definitely make sense to run them through GCAM.

**Comment by bpbond** [comment]
Makes sense to me.

**Comment by bpbond** [comment]
Reopening so @kdorheim can get some practice at this.

**Comment by kdorheim** [comment]
Results from the model time run-xml-tests.py 
``` 
### oldfile: ../old-xml/modeltime.xml    newfile: ../new-xml/modeltime.xml
1 file tested.
0 missing output files.
0 file discrepancies.
```

**Comment by bpbond** [comment]
Why did it only test one file but three are listed above?

**Comment by kdorheim** [comment]
There is only one xml file in 
```
gcam-core/input/gcam-data-system/xml/modeltime-xml
```

**Comment by bpbond** [comment]
@pralitp has wisdom to share here

**Comment by pralitp** [comment]
For _legacy_ reasons the `hector.xml` and `magicc.xml` got saved to a different location just outside the old `gcam-data-system`.  You can find then in the GCAM repository in `input/climate`

**Comment by pralitp** [comment]
@kdorheim, as I typed that I realized that you need to get those files from, exactly the right revision of GCAM.  Instead of explaining that I've just attached them
[climate_xmls.zip](https://github.com/JGCRI/gcamdata/files/1790330/climate_xmls.zip)

**Comment by kdorheim** [comment]
@pralitp thanks for the xml files but why can't I compare with the xmls from the stash core? @bpbond and @rplzzz I thought decided it was okay to compare with the xmls from the latest core on stash, is that not correct?

**Comment by pralitp** [comment]
Oops, I think I am stepping on some toes.  I guess you were told that in which case: please do use the version from the latest Core.  I hope you were also told that you can expect to see differences in that case though?

With regards to this issue, you will see in `hector.xml` the hector end year is `2100` in the file you have but `2300` on the latest stash core.

**Comment by kdorheim** [comment]
No stepping on toes, I'm just confused. 

We do see the change in the `hector.xml`  when we run the xml tests.

**Comment by kdorheim** [comment]
There are discrepancies between the old and new data system model time xmls. @bpbond since you have been identified as the the expert for `modeltime` could you please see the pdf in the attachment  for xml check results, the xmls that are causing the issues are included in the zip folder.

[modeltime.zip](https://github.com/JGCRI/gcamdata/files/1793988/modeltime.zip)

**Comment by bpbond** [comment]
Thanks @kdorheim . Re the difference in end year, I assume we want to change `modeltime.HECTOR_END_YEAR` to be 2300 to match the stash core (?).

More generally, that's a nice PDF report you sent--informative and easy to read. If there are a lot of discrepancies, the Python script output format will start to get hard to read (as opposed to having everything in a table), but I guess we can cross that bridge when we come to it.

**Comment by kdorheim** [comment]
With #877 the model time xmls now pass the xml test. 

```
 run-xml-tests.py ../old-xml/modeltime-xml ../new-xml/modeltime
3 files tested.
0 missing output files.
0 file discrepancies.
```

**Comment by kdorheim** [comment]
Now with #876 the old new xml model time xml test pass. 
```
python3 run-xml-tests.py ../old-xml/modeltime-xml ../new-xml
3 files tested.
0 missing output files.
0 file discrepancies.
```

**Comment by bpbond** [comment]
👏 🎉

**Comment by kdorheim** [comment]
@bpbond GCAM ref runs with without error! You may now have the honors of closing this issue.

**Comment by bpbond** [comment]
And now, for the FOURTH time, ...
