### ISSUE TITLE
HFC emissions Guus Velders citation - SSP2_GV

### ISSUE THREAD

**Issue by rhoesly** [JGCRI/gcamdata#630]
Does anyone know the citation for the Guus Velders HFC emission inventory? I'm having trouble locating a citation or website
Data includes:
HFC historical emission 1990 - 2012. 
The file notes that the scenario is SSP2_GV

file in data system: 
emissions-data/level0/HFC_Inventory_GV.csv

**Comment by pkyle** [comment]
This is from @kvcalvin, although she's on vacation. Just searching for the string "Velders" the following link came up elsewhere in the data system. Maybe sufficient? http://www.sciencedirect.com/science/article/pii/S135223101530488X

**Comment by ssmithClimate** [comment]
I don't know for sure if the data is the data from this paper, or from an update of this, but I suspect this is the correct reference. 

For the record, there's some very nice new work (including MAC curves) from IIASA that we should consider incorporating into GCAM when we get a chance:
Global emissions of fluorinated greenhouse gases 2005–2050 with abatement potentials and costs (Purohit & Höglund-Isaksson 2017)

**Comment by kvcalvin** [comment]
@bpbond Can we close this one?

**Comment by bpbond** [comment]
Yup, thanks.
