### ISSUE TITLE
Missing units for emissions constants

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#632]
```R
emissions.LOW_PCGDP <- 2.75
emissions.COAL_SO2_THRESHOLD <- 0.1
```

@russellhz It looks like you added these? If yes, can you track down units? Thanks.

**Comment by russellhz** [comment]
emissions.LOW_PCGDP : Thousand 1990 USD
emissions.COAL_SO2_THRESHOLD: Tg/EJ (here it is referring to Tg SO2 per EJ of coal electricity)
