### ISSUE TITLE
Need help with L231.proc_sector assumption file units

### ISSUE THREAD

**Issue by russellhz** [JGCRI/gcamdata#637]
`module_emissions_L231.proc_sector` reads in a bunch of assumption files with no units or sources. The ones I'm not sure about:

- Cost: `A31.globaltech_cost`
- Coefficients: `A31.globaltech_coef`
- Efficiency: `A31.globaltech_eff` and in energy `A32.globaltech_eff`
- Other: `A31.rsrc_info`

- Logit and shareweight: I've been listing these as NA/Unitless

**Comment by ssmithClimate** [comment]
I don't have anything to add on these files. Logit and share weight are, indeed, unitless (so use that instead of NA).

**Comment by bpbond** [comment]
Thanks, Steve.
