### ISSUE TITLE
adjust `left_join_error_no_match` for level 2 chunks

### ISSUE THREAD

**Issue by abigailsnyder** [JGCRI/gcamdata#640]
One thing I've noticed with level 2 chunks is that we have to carry a column `logit.type` whose values are all NA whenever we're creating a logit-related output.

Therefore, for these logit related tables, we can't use `left_join_error_no_match`, often simply due to the `logit.type` column.  There's obviously ways to work around it, but is there any way `left_join_error_no_match` can be updated to ignore NA in `logit.type` so that the more restrictive join can be more seamlessly used in the level 2 chunks?

**Comment by rplzzz** [comment]
Easiest thing to do would be to add argument like `na.allowed` to `left_join_error_no_match`.

**Comment by bpbond** [comment]
Yeah, or an `ignore_columns = "logit.type"` one.
