### ISSUE TITLE
Code coverage performance regression has been fixed

### ISSUE THREAD

**Issue by pralitp** [JGCRI/gcamdata#645]
@bpbond and @rplzzz I received notification on `jimhester/covr` that the performance degradation we were seeing in the latest version has been fixed (was issue 274 there).   This is related to #581, and was worked around by specifying covr version 2.2.2 in #590.  We could in principal use the latest version again if we so choose although there doesn't appear to be any pressing need at the moment.

**Comment by bpbond** [comment]
Thanks! Up to you; from my point of view, feel free to defer to V1.1.
