### ISSUE TITLE
Go through constants.R and clean things up

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#647]
Make sure everything in right section, has module prefix (`energy.xxx`), has good comments. Use git blame to assign issues as necessary.

**Comment by pralitp** [comment]
We should think broadly about these and see if there are is a way to reduce the number of these as it seems many are duplicative.  Also `energy.DIGITS_INCELAS_IND` is definitely duplicated as it is defined in 3 separate places in `constants.R`.

**Comment by bpbond** [comment]
Hi @kdorheim - this seems like an easy thing, at least the first part (cleanup) does. The second part will require more thought, so if necessary we can open a separate issue for it. OK to take on? Thanks.

**Comment by kdorheim** [comment]
@bpbond can do!

**Comment by kdorheim** [comment]
Do the `Time constants` need to be time.XXX ?

**Comment by bpbond** [comment]
Yeah, I like that idea personally. Should we collapse `time` and `modeltime` into a single prefix?

**Comment by kdorheim** [comment]
Do we want to include sources for constants other than years or digits?

**Comment by bpbond** [comment]
What do you mean? Documentation?

**Comment by kdorheim** [comment]
Do the conversion constants such as `CONV_BIL_MIL` need a prefix?

**Comment by bpbond** [comment]
I don't think so. If they all begin with `CONV_` that's unambiguous.

**Comment by kdorheim** [comment]
Should I remove time shift conditions from file or will we remove that latter? 

``` # Uncomment these lines to run under 'timeshift' conditions
# HISTORICAL_YEARS <- 1971:2005       # normally 1971:2010
# FUTURE_YEARS <- seq(2010, 2100, 5)  # normally seq(2015, 2100, 5)
# BASE_YEARS <- c(1975, 1990, 2005)   # normally (1975, 1990, 2005, 2010)
# MODEL_YEARS <- c(BASE_YEARS, FUTURE_YEARS) ```

**Comment by kdorheim** [comment]
PV constants currently have their own section. Should I give them energy.XXX prefix and move to energy section?

**Comment by bpbond** [comment]
Time shift - ugh, no later.

What's "PV"? Anyway yes please.
