### ISSUE TITLE
L2233.electricity_water update attributes

### ISSUE THREAD

**Issue by swd-turner** [JGCRI/gcamdata#648]
`L2233.electricity_water` to be updated with improved attributes once upstream inputs are available from #517

**Comment by swd-turner** [comment]
Also batch_xml files to be updated and enabled at this point. Note, following files are passed straight from L223 into batch_electricity_water.xml:

"L223.ElecReserve"
"L223.EQUIV_TABLE"
"L223.StubTechCapFactor_elec"
"L223.SubsectorInterp_elec"
"L223.SubsectorInterpTo_elec"
"L223.SubsectorLogit_absolute-cost-logit"
"L223.SubsectorLogit_elec"
"L223.SubsectorLogit_relative-cost-logit"
"L223.SubsectorShrwt_nuc"
"L223.SubsectorShrwt_renew"
"L223.SubsectorShrwtFllt_elec"
"L223.Supplysector_absolute-cost-logit"
"L223.Supplysector_elec"
"L223.Supplysector_relative-cost-logit"
"L223.StubTech_elec"

**Comment by swd-turner** [comment]
Attributes updated and committed to #798

**Comment by bpbond** [comment]
Thanks @swd-turner - closing.
