### ISSUE TITLE
Exogenous share-weights that are specific to each region and fuel

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#668]
In #633 @pkyle said:

>Ignoring (i.e., not including) the code for processing the non-existent A25.subsector_interp.csv file certainly doesn't hurt; it looks like I meant to exclude subsector share-weight interpolation from this sector entirely, and intentionally omitted the CSV file and readdata() statement, but messed up by including those lines of code...which didn't end up doing anything because their preceding if() conditions were both false.

>Having this functionality but not exercising it seems a waste of effort. To the extent that we want to allow share-weight interpolation for hydrogen production, it ought to be region-specific. This data/code method writes share-weight interpolation rules equally to all regions, a capability that doesn't strike me as all that necessary. Right now in the model we don't regionally differentiate energy prices; instead, calibrated share-weights carried forward bring price effects into the future decisions. In the current approach, because hydrogen production is not calibrated, and each fuel costs just about the same in each region, all regions have (more or less) equal shares of the different fuel options in future periods. That's not ideal. If we ever start focusing on hydrogen in the future, we will need inter-regional differences in fuel (feedstock) market shares, and one easy way to get that will be to read in exogenous share-weights that are specific to each region and fuel.

**Comment by russellhz** [comment]
Addressed in #1190
