### ISSUE TITLE
L226.en_distribution A26 assumption sources

### ISSUE THREAD

**Issue by cwroney** [JGCRI/gcamdata#690]
We have missing sources for assumption files used for L226.en_distribution in A26.globaltech_cost and for the backup efficiencies in A26.globaltech_eff. Page noted for the former that it is from the miniCAM model inputs, but we're not sure of the sources for the miniCAM inputs themselves. 

Background from Page: 
> In general, these are the energy delivery cost adders, or the difference between producer prices and delivered energy prices to different consumer groups. The unit is 1975$/GJ, and the source for most of the items is the pre-2006 MiniCAM model inputs. Values of zero indicate that delivery costs are included elsewhere in the chain.
> A26 also includes some grid reliability (backup) related costs. The backup_electricity cost represents the variable O&M cost of a gas turbine (levelized capital and fixed O&M costs are accounted elsewhere). No such cost is included here for csp_backup, because the turbine costs are already accounted in the primary electric technology costs.

**Comment by bpbond** [comment]
@cwroney Please close this when appropriate.
