### ISSUE TITLE
GCAM USA states object

### ISSUE THREAD

**Issue by russellhz** [JGCRI/gcamdata#691]
In almost every GCAM-USA script I've seen so far, there is an object `states` with all 51 state abbreviations. Rather than add that huge list to the constants file, I've just been using `unique(some_input_object$state)`. This hasn't been an issue, but I suppose it is possible that at some point all 51 states might not be in an input file.

Is this the correct behavior, or is it worth making a constant with all the states?

**Comment by bpbond** [comment]
I think we'd like a constant with all state names. As you say, we'd like to be able to catch situations where not all states are represented in some input.

**Comment by bpbond** [comment]
@gokuliyer Any comments on having a canonical list of `states`?

**Comment by russellhz** [comment]
I did make a `gcamusa.STATES` object in the chunk I am currently working on. It's really not space consuming at all. It's just the abbreviations

**Comment by gokuliyer** [comment]
The states_subregions.csv has the list of states. A constant would be good as well. Programatically, I guess both would serve the same purpose?

**Comment by russellhz** [comment]
There are some chunks that don't currently use states_subregions.csv, but do use the `states` object
