### ISSUE TITLE
module_socioeconomics_L100.GDP_hist missing @details

### ISSUE THREAD

**Issue by kvcalvin** [JGCRI/gcamdata#703]
I was randomly looking at gcamdata files today (don't ask) and discovered that the `@details` section hasn't been filled out for `module_socioeconomics_L100.GDP_hist`. This should probably be fixed.

**Comment by bpbond** [comment]
My first reaction was, hey, don't assign this to me, assign it to whichever lazy person didn't fill in that information! And then...yeah. This chunk is kind of an historical artifact, one of the first ever done.

**Comment by kvcalvin** [comment]
I figured as much. I am also surprised I found it...I just randomly clicked on a file to figure out how to structure the Roxygen information and this is the file I picked.

**Comment by bpbond** [comment]
@kvcalvin By the way, note that if in RStudio you put your cursor inside of a function, and then click the little "magic wand" icon at the top of the pane, and select "Insert Roxygen Skeleton"...magic!

**Comment by kvcalvin** [comment]
Good to know. Although, if I had done that, I wouldn't have found this little issue.

**Comment by rplzzz** [comment]
@bpbond Does the skeleton generated that way use the `@details` tag?  If so, that doesn't seem to be the recommended way to organize doc blocks.  See: http://r-pkgs.had.co.nz/man.html

**Comment by kvcalvin** [comment]
No.

```
#' Title
#'
#' @param aRegionName 
#' @param aChoiceFnAbove 
#' @param aPeriod 
#'
#' @return
#' @export
#'
#' @examples
```

**Comment by bpbond** [comment]
Ah. Right. The `@param` lines are useful anyway.

**Comment by kvcalvin** [comment]
I've been adding it to mine though...seems useful.
