### ISSUE TITLE
Handle temp-data-inject tracebacks for land input 2-3-4-5 files

### ISSUE THREAD

**Issue by abigailsnyder** [JGCRI/gcamdata#729]

**Comment by abigailsnyder** [comment]
Be sure to use trace utility so @bpbond has demonstration material

**Comment by kvcalvin** [comment]
So, I've gone through all of the land input files and these are the `temp-data-inject` files that still exist. I think what we want to do next is create each of them _without_ using any new `temp-data-inject` files.

```
"temp-data-inject/L223.LN3_MgdAllocation_bio"
"temp-data-inject/L223.LN3_MgdAllocation_crop"
"temp-data-inject/L223.LN3_LeafGhostShare"
"temp-data-inject/L223.LN3_LeafIsGhostShareRel"
"temp-data-inject/L2241.LN4_Logit"
"temp-data-inject/L2241.LN4_HistMgdAllocation_crop"
"temp-data-inject/L2241.LN4_MgdAllocation_crop"
"temp-data-inject/L2241.LN4_HistMgdAllocation_bio"
"temp-data-inject/L2241.LN4_MgdAllocation_bio"
"temp-data-inject/L2241.LN4_MgdCarbon_crop"
"temp-data-inject/L2241.LN4_MgdCarbon_bio"
"temp-data-inject/L2241.LN4_LeafGhostShare"
```

**Comment by kvcalvin** [comment]
I have removed `temp-data-inject/L223.LN3_LeafGhostShare` and `temp-data-inject/L223.LN3_LeafIsGhostShareRel` on the branch `aglu-traceback`.

**Comment by bpbond** [comment]
I removed the actual `temp-data-inject/` files as well. Looked at the legacy name issue; this can be solved but I'm not sure it's worth doing. What about keeping a list of renames we want to do (e.g. L2242.LN4_NodeIsGhostShareRel -> L2242.LN4_GhostShareRelativeToDominantCrop) once we hit v1?

**Comment by kvcalvin** [comment]
That's fine. It isn't critical if it is hard. I can switch mine back

**Comment by bpbond** [comment]
No, wait, hang on. Duh. Let me try something.

**Comment by bpbond** [comment]
So the simplest solution is just to rename the comparison data file (in `tests/testthat/aglu`) when you rename the data object–i.e. the two names should match. We've already done this, so let's keep doing it.

**Comment by kvcalvin** [comment]
Woohoo! 5 more `temp-data-inject` files now gone. The remaining files are:
```
"temp-data-inject/L223.LN3_MgdAllocation_bio"
"temp-data-inject/L223.LN3_MgdAllocation_crop"
"temp-data-inject/L2241.LN4_MgdCarbon_crop"
"temp-data-inject/L2241.LN4_MgdCarbon_bio"
"temp-data-inject/L2241.LN4_LeafGhostShare"
```

**Comment by bpbond** [comment]
🎉 Nice!

**Comment by kvcalvin** [comment]
Two more files removed! Remaining files:

```
"temp-data-inject/L2241.LN4_MgdCarbon_crop"
"temp-data-inject/L2241.LN4_MgdCarbon_bio"
"temp-data-inject/L2241.LN4_LeafGhostShare"
```

I'm hoping to finish these today so that land will be done.

**Comment by kvcalvin** [comment]
@bpbond: I have updated to remove the remaining `temp-data-inject` files from the land DSR. The updated project (see branch `aglu-traceback`) still fails the oldnew test on one table for a small number of rows. I think this has to do with bioenergy yield differentiation between hi/lo input, but I couldn't get my fix to work. Additionally, the code probably needs some cleaning/commenting.

**Comment by bpbond** [comment]
@abigailsnyder Is this something you'd be willing and able to take on, at your convenience?

**Comment by abigailsnyder** [comment]
I'll add it to the list @bpbond.
Nearish the top wrt dsr tasks.

**Comment by bpbond** [comment]
Thank you! 👏

**Comment by kvcalvin** [comment]
Can we close this?

**Comment by bpbond** [comment]
Funny, I was just looking at this issue and wondering the same thing.
