### ISSUE TITLE
put protected land code in their own chunk after land input 5

### ISSUE THREAD

**Issue by abigailsnyder** [JGCRI/gcamdata#730]
collect protected land steps from land input 2, 3, 4, 5 and put all in one chunk

**Comment by bpbond** [comment]
Is this correctly tagged for Version 1? Or is it a Version 2 development?

**Comment by kvcalvin** [comment]
I think this can be version 2. It looks like we generated the necessary chunks, but want to reorganize them so it is less confusing. @abigailsnyder -- does that sound right?

**Comment by abigailsnyder** [comment]
I will go back through and double check. It's possible that I got to some of the later land input files (4,5) after we opened this issue and skipped the protected lands in those files. I can check later this week and add that translation in for now, if we want.

**Comment by kvcalvin** [comment]
Thanks!

**Comment by bpbond** [comment]
Yes, thanks. I'd say that if it's a close-to-trivial amount of work, go for it; but otherwise let's kick this down the road. For now I'm going to move this to Version 2, but let me know if otherwise.

**Comment by abigailsnyder** [comment]
The protected lands only show up in `land input 2` and `land input 3` in the old Data System. 
We have then in `land input 2` in the new DS, but `land input 3 irr` in new DS needs prot lands from `land input 3` in old ds. So I will work on that this week.

**Comment by kvcalvin** [comment]
Okay, hopefully it won't take too long.

**Comment by bpbond** [comment]
Thanks. I'll handle your PR #825 .
