### ISSUE TITLE
Is states_subregions.csv wrong?

### ISSUE THREAD

**Issue by russellhz** [JGCRI/gcamdata#732]
West Virginia is listed as being in the Midwest for subregion4 in the file, but this appears to be wrong [https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf](url)

Because of this designation in the file, I have to use `left_error_keep_first_only` in many places, which is kind of sketchy. It is the only state that is listed as being in the Midwest for subregion4, but in Atlantic-S for subregion9

**Comment by bpbond** [comment]
Passing this right over to @gokuliyer .

**Comment by russellhz** [comment]
Have you had a chance to look at this @gokuliyer ?

**Comment by gokuliyer** [comment]
This seems to be a mistake and needs to be corrected. Could you also check that state_census_region.csv is correct? Also, if this is duplicated information in the two files, could we get rid of one of them?

**Comment by russellhz** [comment]
Thanks @gokuliyer! I will make that change. 

I'm not seeing where state_census_region.csv is. It's in the old data system?

**Comment by gokuliyer** [comment]
Interesting! I have it my branch but it's not in the core. We should just correct the states_subregions.csv for now.
