### ISSUE TITLE
L112.ghg_en_R_S_T_Y rounding

### ISSUE THREAD

**Issue by russellhz** [JGCRI/gcamdata#734]
#613 
@bpbond so it looks like I did just forget to remove the disabled tag from L112 (probably because I was only changing different files). This new issue is not directly related to the previous issue I fixed (I think)

There are just 3 observations where the old_new test is failing. See below. Basically, the old and new values are identical but round to different numbers. Is this a case for `FLAG_SUM_TEST`?

![image](https://user-images.githubusercontent.com/25437326/30344812-d0e5e1de-97d0-11e7-9995-1e74662e6a7c.png)

**Comment by bpbond** [comment]
Thanks for jumping on this so quickly. Sounds good to me.
