### ISSUE TITLE
Driver check for potential numerical instability?

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#736]
The driver could check for numeric values in tibbles that are less than some small value, e.g. `|x| < 1e-10`, and flag/disallow them. This would force chunks to deal with the problem noted in #613 and other places: math operations can yield very-close-to-zero numbers that should, in fact, be zero. This would let us set a single `MIN_NUMERIC_TOLERANCE` or something like that, used throughout the package.

Thoughts @rplzzz ?

**Comment by rplzzz** [comment]
My concern about this is that it's hard to know what the appropriate cutoff value should be.  Consider this example I came up with fooling around at the console:
```
> xx
[1] 2e+09 2e+09
> xx[2]-xx[1]
[1] 7.152557e-07
```
So, that result is above the cutoff, but it's entirely made up of roundoff error.  I guess we could use a simple test to flag values for follow-up, but in the end all you can really do is review proposed changes carefully and exercise good judgement about performing operations that can result in a catastrophic loss of precision.  That and, of course, look at the results and ask whether they make sense.

I'm not sure what you mean by using a single `MIN_NUMERIC_TOLERANCE` throughout the package (using it for what?), but we can talk it over sometime soon.

**Comment by bpbond** [comment]
Hmm. OK, thanks. We can discuss.

I was thinking that after any e.g. subtraction operation, chunks should

`mutate(result = if_else(abs(result) < MIN_NUMERIC, 0, result)) %>%`

**Comment by bpbond** [comment]
Note for future - this kind of check occurs in LA132.industry lines 180-185.

**Comment by bpbond** [comment]
This is largely superseded by #931 - closing.
