### ISSUE TITLE
parsing failures with gcam-usa/RECS_2009.csv

### ISSUE THREAD

**Issue by russellhz** [JGCRI/gcamdata#741]
There are multiple columns in `RECS_2009.csv` that get read in as integers, but should be doubles. My current workaround is this `RECS_2009 <- readr::read_csv("inst/extdata/gcam-usa/RECS_2009.csv", comment = "#", col_types = list(
      BTUFOOTH = readr::col_double(),
      BTUKERSPH = readr::col_double(),
      BTUKEROTH = readr::col_double()))`

Does this require a separate data chunk?

**Comment by bpbond** [comment]
One cheap-and-easy workaround to this is add ".0" to the first entry of these columns. That should force `readr` to treat them as doubles. (If this doesn't work we can add a dedicated data chunk.)

**Comment by russellhz** [comment]
Looks like that worked! Thanks
