### ISSUE TITLE
Reasons for different dplyr behavior - checking

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#745]
```R
> library(dplyr)
> packageVersion("dplyr")
[1] ‘0.5.0’
> tibble(x=1, y=2) %>% select("x", "y")
Error: All select() inputs must resolve to integer column positions.
The following do not:
*  "x"
*  "y"
> tibble(x=1, y=2) %>% select(c("x", "y"))
Error: All select() inputs must resolve to integer column positions.
The following do not:
*  c("x", "y")
> tibble(x=1, y=2) %>% select(one_of("x", "y"))
# A tibble: 1 × 2
      x     y
  <dbl> <dbl>
1     1     2
> tibble(x=1, y=2) %>% select(one_of(c("x", "y")))
# A tibble: 1 × 2
      x     y
  <dbl> <dbl>
1     1     2
```

@jhoring can you try running above sequence of commands in an R session on your machine please? If any differences please paste results here. Thanks.

**Comment by jhoring** [comment]
@bpbond I have dplyr version 0.7.1 and am not getting any of the integer column position errors.

> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> packageVersion("dplyr")
[1] ‘0.7.1’
> tibble(x=1, y=2) %>% select("x", "y")
# A tibble: 1 x 2
      x     y
  <dbl> <dbl>
1     1     2
> tibble(x=1, y=2) %>% select(c("x", "y"))
# A tibble: 1 x 2
      x     y
  <dbl> <dbl>
1     1     2
> tibble(x=1, y=2) %>% select(one_of("x", "y"))
# A tibble: 1 x 2
      x     y
  <dbl> <dbl>
1     1     2
> tibble(x=1, y=2) %>% select(one_of(c("x", "y")))
# A tibble: 1 x 2
      x     y
  <dbl> <dbl>
1     1     2

**Comment by bpbond** [comment]
OK, so that's one mystery from #728 and #744 (fyi @swd-turner ) resolved: the newer dplyr lets you do `select("x", "y")` while the older 0.5 version requires `select(one_of(c("x", "y"))`. That explains why you guys weren't getting those errors on your PRs.

I'll add a note to the wiki and Slack about this. Thanks. I may hit you guys up for other tests later if that's OK.

cc @rplzzz
