### ISSUE TITLE
A23.globaltech_eff.csv in OLD and NEW have different # of lines

### ISSUE THREAD

**Issue by rynacui** [JGCRI/gcamdata#773]
This file is in `energy-data\assumptions` in the ODS. 
Not sure why it has two more lines regarding `solar` when added to `inst\extdata\energy`.

**Comment by bpbond** [comment]
I see a four-line difference, because the new file has a three-line header, and there's now a blank line at the end.

**Comment by bpbond** [comment]
P.S. I should say that there's no difference in the content when I `diff` the files.

**Comment by rynacui** [comment]
I have two extra lines in the content, 27 versus 25.

**Comment by bpbond** [comment]
Huh...um. I can look; do you want to send to me/post here?

**Comment by bpbond** [comment]
Merged so closing.
