### ISSUE TITLE
Driver won't build on windows machine following L222.en_transformation merging in

### ISSUE THREAD

**Issue by abigailsnyder** [JGCRI/gcamdata#783]
Possibly due to `fill_decay_extrapolate`? Maybe around line 181 in `L22.en_transformation`.

There've been some errors from Check Package around `fill_decay_extrapolate` for a while, but they never stopped the driver from running or impacted my outputs.

I'm stumped. Very likely will affect @rynacui if she tries to merge master into any branch she's working on right now.

**Comment by rynacui** [comment]
Yea, I also got the check package error for `fill_decay_extrapolate` for a while...

**Comment by abigailsnyder** [comment]
@rynacui  fwiw, disabling `module_energy_L222.en_transformation` will at least allow the driver to run . Short term fix so you can stay (mostly) up to date with master and still work on your chunk.

The upside, I think the only thing downstream that would use outputs from `module_energy_L222.en_transformation` is a chunk that's assigned to me. So disabling shouldn't break anything else for a while.

**Comment by cwroney** [comment]
Weird, I just opened master, built and ran driver(), and did Check Package and received 0 errors and warnings (I'm also running windows). @pralitp wrote `fill_exp_decay_extrapolate()` for me so I'm not 100% sure what it's going on under the hood. The only thought I have is that the function checks your dplyr version and works slightly differently depending on what you have, so that's a possible source of difference (see code below). I'm running 0.7.3 currently: 

> if(utils::packageVersion("dplyr") < "0.7") {
>     d %>%
>       complete(tidyr::nesting_(select(., -year, -value)), year = union(year, out_years)) ->
>       d
>   } else {
>     nesting_vars <- paste0('`', names(d)[!(names(d) %in% c("year", "value"))], '`')
>     d %>%
>       complete(tidyr::nesting_(nesting_vars), year = union(year, out_years)) ->
>       d
>   }

**Comment by bpbond** [comment]
What version of dplyr are you running @abigailsnyder ?

**Comment by abigailsnyder** [comment]
dplyr_0.7.2
Maybe the .2 to .3 will make the difference, dare I update?

**Comment by abigailsnyder** [comment]
Since I'm still version 0.7, I don't think I'd trigger that flag, but I've accepted the dark magic at work in dsr

**Comment by bpbond** [comment]
Yeah, I'd try updating (of course, it's not my machine, and no code of _mine_ will break if something goes wrong). Given that @cwroney is running OK, seems worth a try.

>dark magic

No kidding. `“Ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn.`

**Comment by abigailsnyder** [comment]
everything is broken now. I now have no dplyr and  can't re-install it.

**Comment by abigailsnyder** [comment]
Ok, I have dplyr 0.7.4
Does not fix the L222.en_transformation issue.

**Comment by pralitp** [comment]
Could you check with @kdorheim?  She had a similar issue and I think we had to upgrade dplyr and tidyr.

**Comment by abigailsnyder** [comment]
ah I'm way behind on tidyr 0.6.1 - @kdorheim is at 0.7.1. updating tidyr to 0.7.1 fixes it.  
At least the problem will be obvious for other people now

**Comment by bpbond** [comment]
Cool! Thanks @pralitp .

**Comment by bpbond** [comment]
P.S. I will update the `gcamdata` package requirements to enforce a 0.7.1 minimum.
