### ISSUE TITLE
L222.en_transformation Outputs

### ISSUE THREAD

**Issue by cwroney** [JGCRI/gcamdata#785]
The outputs for L222.en_transformation are currently returned as empty tibbles because `tibble()` was not replaced in the Produce Outputs section with the function names. We need to fix the outputs and figure out why the package tests did not catch the outputs as empty data frames.

**Comment by cwroney** [comment]
Branch created for this issue at https://github.com/JGCRI/gcamdata/tree/Chris-L222.en_transformation-FIX. Replaced incorrect tibble() and currently troubleshooting errors from doing so.

**Comment by cwroney** [comment]
I think the empty data frames are passing through untested; after replacing the outputs with the correct names it's flagged a couple slight differences in the oldnew test.

**Comment by cwroney** [comment]
I've fixed the code in L222 so it passes all checks in the regular output. I'm suspicious that this also means that any data frames defaulting to empty, i.e., any that are conditionally made using an `if (exists(output)) {output} else {tibble(x = NA) -> output}` structure would not be tested against the old data system to see if it is also not there originally. I'm not sure how to test whether this is true.

**Comment by bpbond** [comment]
Sorry for the slowness--I've been out of town--but will dive into this on Tuesday.

**Comment by abigailsnyder** [comment]
my b I meant to close the issue I opened

**Comment by bpbond** [comment]
Closed as #804 merged.
