### ISSUE TITLE
Write A_*_data.R values into constants.R? 

### ISSUE THREAD

**Issue by fengly20** [JGCRI/gcamdata#788]
#778 

The chunk `L2321.cement` I'm working on needs a bunch of data from data scripts like `energy-data/assumptions/A_*_data.R`. Should I write those values into constants.R? @bpbond 

Thanks!

**Comment by bpbond** [comment]
Wow, that's a lot of stuff. I guess so?

**Comment by fengly20** [comment]
Sure. Thanks!
