### ISSUE TITLE
write_to_all_states

### ISSUE THREAD

**Issue by russellhz** [JGCRI/gcamdata#795]
Right now, this function requires that `region` is in `names(data)`. However, this is often not the case, so you would have to add an arbitrary `region` column to use the function. I think this should be changed to:
` if ("region" %in% names(data)){`
    `data <- data %>%`
      `select(-region)`
 ` }`

  `data %>%`
    `set_years %>%`
    `repeat_add_columns(tibble(region = gcamusa.STATES)) %>%`
    `select(one_of(names))`

rather than:
  `data %>%`
    `set_years %>%`
    `select(-region) %>%`
    `repeat_add_columns(tibble(region = gcamusa.STATES)) %>%`
    `select(one_of(names))`

**Comment by bpbond** [comment]
It looks like @abigailsnyder is proposing a fix for this too, in #790 . Off to look at that now.

**Comment by abigailsnyder** [comment]
@bpbond `select(-one_of("region"))` is what I have now; it's fine but it throws a warning any time region isn;t present. I'm going to play around with `select(-contains("region"))`

**Comment by abigailsnyder** [comment]
otherwise yeah just if statements

**Comment by bpbond** [comment]
Well, or just `data$region <- NULL`

**Comment by abigailsnyder** [comment]
that works too

**Comment by bpbond** [comment]
OK, I've made a fix as `data %>% mutate(region = NULL) %>%` and will commit that.
