### ISSUE TITLE
L222.en_transformation.R doesn't actually produce outputs

### ISSUE THREAD

**Issue by abigailsnyder** [JGCRI/gcamdata#799]
The body of the code is there, but the entire outputs look like
```
 # Produce outputs

    tibble() %>%
      add_title("Supply sector information for energy transformation sectors") %>%
      add_units("Unitless") %>%
      add_comments("Written to all regions from A22.sector") %>%
      add_legacy_name("L222.Supplysector_en") %>%
      add_precursors("energy/A22.sector", "common/GCAM_region_names") ->
      L222.Supplysector_en

    tibble() %>%
      add_title("Subsector logit exponents of energy transformation sectors") %>%
      add_units("Unitless") %>%
      add_comments("Written to all regions from A22.subsector_logit") %>%
      add_legacy_name("L222.SubsectorLogit_en") %>%
      add_precursors("energy/A22.subsector_logit", "common/GCAM_region_names") ->
      L222.SubsectorLogit_en
```

So nothing is actually getting written or tested. Throwing the inputs in is an easy fix on my end to give me the files I need for `L222.en_transformation_USA` but they haven't been tested, and I'd prefer to wait for the tests to pass. I'm going to start a branch and open a PR to do it, but if the tests fail then I don't....want to be the one to figure out why.

**Comment by cwroney** [comment]
Thanks @abigailsnyder, I caught this about a week ago and we have a fix incoming shortly, see https://github.com/JGCRI/gcamdata/issues/785. Two outputs are failing the test now that they're actually being tested so I just have to track them down and will put a pull request in. Ben and I are also trying to figure out why they're not getting tested by the oldnew so hopefully it can be caught automatically if it's happened anywhere else.

**Comment by abigailsnyder** [comment]
cool cool
