### ISSUE TITLE
#789 missing output

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/gcamdata#805]
I am working on `L2321.cement_USA` which uses `L2321.IncomeElasticity_cement_gcam3` from but I did not see it listed as an output from L2321.cement in the new data system. Is this output being stripped from the new ds?

**Comment by bpbond** [comment]
@fengly20 ?

**Comment by fengly20** [comment]
`L2321.IncomeElasticity_cement_gcam3` (and other scenarios ) was not declared as output in the `L2321.cement` skeleton. Waiting on @bpbond to decide how we should deal with those (conversations in the #789 PR).

**Comment by bpbond** [comment]
OK, sorry all–as @fengly20 points out, he asked this very question 10 days ago in #789 .

As far as I know we are keeping these outputs. So for now I'd say @kdorheim you should be using `temp-data-inject` data, and once #789 is merged you can switch to real outputs.

**Comment by kdorheim** [comment]
Sounds good thanks! @bpbond @fengly20
