### ISSUE TITLE
Correctly handling L2321.cement outputs and xml files

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#806]
In #789 we merged `module_energy_L2321.cement` and `module_energy_batch_cement_xml` but the latter is probably not correct, or at least not complete.

1. I commented out two of its inputs, `L2321.SubsectorShrwt_cement` and `L2321.SubsectorInterpTo_cement`, as they're not produced by `L2321.cement`. What should be done here?
2. The various SSP files produced by `L2321.cement` don't appear anywhere. Should they be included in this XML file? Or do they each get their own file, following e.g. `module_energy_batch_building_SSP_xml`?

@fengly20 you may want to engage with @pkyle @d3y419 @rplzzz as necessary. Thanks!

**Comment by bpbond** [comment]
Hi @fengly20 - I just talked with @pkyle and he confirmed that what should happen is that each SSP, etc., all go into a separate XML file; this provides a mechanism for scenario-specific settings to override the default ones. I'll do this for #784 , and then you can open a new PR to address this issue, patterning after what I do, OK?

**Comment by fengly20** [comment]
Sorry I just saw your message. Somehow I was not getting email notifications from Github. I'll do the XML stuff for cement.
