### ISSUE TITLE
L210.resources metadata

### ISSUE THREAD

**Issue by russellhz** [JGCRI/gcamdata#810]
Two questions:

1. Units/source for energy-data/assumptions/A10.EnvironCost_SSPs.csv

2. Are all TechChanges unitless (A10.TechChange, A10.TechChange_SSPs, A15.roofPV_TechChange)?

**Comment by pkyle** [comment]
Re (2), TechChange is an annual improvement rate. I'd call it unitless, but you might check what we've written for other similar parameters (e.g., AgProdChange).

**Comment by kvcalvin** [comment]
Re (1), you can cite my SSP paper. It has documentation there. http://www.sciencedirect.com/science/article/pii/S095937801630084X
