### ISSUE TITLE
VERSION 1 CHECKOFF - EMISSIONS

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#815]
Verify that

- [x] new data system produces exactly same `emissions` XML files as old data system (see python test results)
```
21 files tested.
0 missing output files.
```

- [x] structure and contents of files matches (see python test results) 
```
0 file discrepancies.
```

- [x] no `temp-data-inject/` files still being used (see #935)

- [x] creates same outputs as GCAM 5 (pass old new test wtih #935)

- [x] GCAM runs with the xml files substituted in (see `/pic/projects/GCAM/Dorheim/dsr/gcam-core/output/emissions_ref_database_basexdb/`)

**Comment by rplzzz** [comment]
Are these files final outputs of the old data system?  They aren't in the `xml` output directory of the old data system.  Instead, they appear to live under the `emissions-processing-code` directory.  They appear to be instructions for the `CSVtoXML` program, not actual outputs.

**Comment by bpbond** [comment]
Looks like that's correct. They still provide (?) a list of the expected xml files, but they're not those outputs themselves? I admit this is pretty murky to me.

**Comment by kdorheim** [comment]
@bpbond, @rynacui , @russellhz and @cahartin thanks for helping finish up the emissions xmls!

**Comment by bpbond** [comment]
I second that. Woo hoo! 🎉
