### ISSUE TITLE
module_emissions_L115.nh3_an_R_S_T_Y unite-join-separate calls

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#817]
Several times, `module_emissions_L115.nh3_an_R_S_T_Y` uses a series of `unite`-`join`-`separate` calls (lines 69-72, 120-123, 135-137). Is this needed? It seems like this could be accomplished simply by `join(..., by("x1" = "x2", "y1" = "y2"))`?

**Comment by bpbond** [comment]
@kdorheim Hi Kalyn, tagging you b/c you originally wrote this, I think, but feel free to ignore. Not urgent.

**Comment by kdorheim** [comment]
@bpbond If I remember correctly you are right, the `unite-join-separate` can be simplified with a `join` call. This was my first chunk, before I understood the full power and potential usefulness of `joins`.

**Comment by bpbond** [comment]
No worries at all--it's working just fine, after all. Just caught my eye. Again, optional. Thanks!

**Comment by bpbond** [comment]
@kdorheim Since you have some DSR hours, this would be one candidate to fix up.

**Comment by kdorheim** [comment]
@bpbond sounds great!
