### ISSUE TITLE
Data relationships - kind of a mess, no dedicated layer

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#830]
Right now functions like `dstrace` and `graph_chunks` and others get the raw inputs-and-outputs data from `chunk_inputs` and `chunk_outputs` and then have to manually construct/figure out relationships via joins, etc. It would be good to abstract and centralize this behind a standard layer of functions.

Just saving some notes on this topic...

High-level functions:

```R
inputs_of(chunk_name)
  # returns character vector of data object names
  # convenience function; calls upstream_data(..., data_store = NULL, max_generations = 1)
outputs_of(chunk_name)
  # returns character vector of data object names
  # convenience function; calls downstream_data(..., data_store = NULL, max_generations = 1)

upstream_data(chunk_name, data_store = NULL, max_generations = Inf)
upstream_data(data_name, data_store = NULL, max_generations = Inf)
  # returns character vector if data_store is NULL
  # returns a named list of objects if not NULL
downstream_data(chunk_name, data_store = NULL, max_generations = Inf)
  # returns character vector if data_store is NULL
  # returns a named list of objects if not NULL
upstream_chunks(chunk_name, max_generations = Inf)
  # returns character vector if data_store is NULL
  # returns a named list of objects if not NULL
downstream_chunks(chunk_name, max_generations = Inf)
  # returns character vector if data_store is NULL
  # returns a named list of objects if not NULL
```

Low-level functions (already exist):

```R
chunk_inputs()
chunk_outputs()
chunk_list()
 ```

**Comment by pralitp** [comment]
Note, #985 piles on to this issue by adding yet another place where we have custom calculation of dependencies.  Namely in the driver around line 230 where we calculate the minimum chunks required to run a `stop_before` or `stop_after`. And then that information is used in a new function called `dstrace_chunks`.

**Comment by bpbond** [comment]
This basically duplicates #757 - closing but will add a note there.
