### ISSUE TITLE
Outstanding uses of temp-data-inject

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#837]
In theory, at this point we shouldn't have any dependencies on `temp-data-inject`. But we do:

Module | Chunk | temp-data-inject object | Notes
--------| ------ | ------------------------- | ------
aglu | L2052.ag_prodchange_cost_irr_mgmt | L201.AgYield_bio_grass | ?
aglu | L2242.land_input_4_irr_mgmt | L223.LN3_MgdAllocation_bio | ?
aglu | L2242.land_input_4_irr_mgmt | L223.LN3_MgdAllocation_crop | ?
aglu | L2242.land_input_4_irr_mgmt | L223.LN3_LeafGhostShare | ?
aglu | L2242.land_input_4_irr_mgmt | L223.LN3_LeafIsGhostShareRel | ?
aglu | L2252.land_input_5_irr_mgmt | L2241.LN4_Logit | ?
aglu | L2252.land_input_5_irr_mgmt | L2241.LN4_HistMgdAllocation_crop | ?
aglu | L2252.land_input_5_irr_mgmt | L2241.LN4_MgdAllocation_crop | ?
aglu | L2252.land_input_5_irr_mgmt | L2241.LN4_HistMgdAllocation_bio | ?
aglu | L2252.land_input_5_irr_mgmt | L2241.LN4_MgdAllocation_bio | ?
aglu | L2252.land_input_5_irr_mgmt | L2241.LN4_MgdCarbon_crop | ?
aglu | L2252.land_input_5_irr_mgmt | L2241.LN4_MgdCarbon_bio | ?
aglu | L2252.land_input_5_irr_mgmt | L2241.LN4_LeafGhostShare | ?
emissions | L211.ag_nonco2 | L205.AgCost_bio | @abigailsnyder should this be `L2052.AgCost_bio_irr_mgmt`?
energy | L223.electricity | L119.Irradiance_rel_R | Chunk never done; #839
energy | L261.Cstorage | L161.RsrcCurves_MtC_R | Chunk never done; #836
energy | LA114.wind | L114.OLDregional_price_supply_points | OK
gcamusa | L244.building_USA | L143.HDDCDD_scen_state | Chunk never done; #838
gcamusa | LA144.Commercial | L143.share_state_Pop_CDD_sR9 | Chunk never done; #838 
gcamusa | LA144.Commercial | L143.share_state_Pop_HDD_sR9 | Chunk never done; #838 
gcamusa | LA144.Residential | L143.share_state_Pop_CDD_sR9 | Chunk never done; #838 
gcamusa | LA144.Residential | L143.share_state_Pop_HDD_sR9 | Chunk never done; #838 
water | L233.water.demand.livestock | L133.water_demand_livestock_R_C_W_km3_Mt | Chunk never done; #840

**Comment by bpbond** [comment]
As far as I can tell these fall into three categories:
1. Chunks that were accidentally skipped because there were two identically-named files in both `gcam-usa` and `energy`. This confused both the skeleton generating script and me. I've created new issues for these: #836 #838 #839 .
2. A chunk that was skipped for some unknown reason in `water`: #840 .
2. The reworking of the aglu land nesting seems to have orphaned a lot of objects. @abigailsnyder are you available to look and straighten this out?
3. `L114.OLDregional_price_supply_points` is a special case, and it's OK. Remove when we hit v1.1

**Comment by bpbond** [comment]
@kdorheim @russellhz @crvernon @fengly20  Not sure about your DSR time allotments, but if you have some, feel free to claim one of the following: #836 #838 #839 #840 - thanks.

**Comment by kvcalvin** [comment]
@bpbond: I removed almost all of those temp-data-injects in the `aglu-traceback` branch. What happened to that?

**Comment by bpbond** [comment]
@kvcalvin Looks like that branch hasn't been touched in a month. Did it fall through the cracks? Were we supposed to open a PR from it?

**Comment by kvcalvin** [comment]
Yes, I had done almost everything, but ran out of time so I pushed the branch but didn't open a PR. Information is in https://github.com/JGCRI/gcamdata/issues/729. My memory is that the work is all done but it could have been cleaner.

**Comment by bpbond** [comment]
OK, I've opened #841 and will deal with this. Thanks!

**Comment by kvcalvin** [comment]
Okay, hopefully it won't be too hard

**Comment by abigailsnyder** [comment]
@bpbond, I'll look into the L205 temp inject for that emissions chunk this week. Once you get #841  merged in, I'll check up on all the chunks. Slash help with getting #841 merged in or whatever comes up.

**Comment by bpbond** [comment]
Thanks @abigailsnyder

**Comment by abigailsnyder** [comment]
@bpbond  good news! The L205.AgCost_bio temp data inject in L211.ag_nonco2 DOES look like it's just pulling region - sector - subsector - technology information. 
I can easily switch it over to use L2052.AgCost_bio_irr_mgmt data, if you'd like?

**Comment by abigailsnyder** [comment]
too late, I did it; running tests and I'll open the PR after the all hands meeting

**Comment by bpbond** [comment]
@kdorheim confirms that only outstanding uses are to get us past rounding methodology change, and will be removed in 1.1. Closing.
