### ISSUE TITLE
Make a list of all OLD_DATA_SYSTEM_BEHAVIOR blocks

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#855]
After we've hit v1 (post-DSR fork integration branch changes made, XMLs verified, GCAM behavior verified), we want to deal with all the `OLD_DATA_SYSTEM_BEHAVIOR` blocks. Ideally we'll throw the switch for all of them, test, get core model proposal accepted, and then remove the old blocks.

In preparation for this it would be really handy to have a list of these blocks. This could just be a spreadsheet with columns of module (energy/aglu.etc), file, line numbers, person who made change, and one-sentence description of what the change/fix does.

@kdorheim Do you have time, and are you willing?

**Comment by kdorheim** [comment]
See attachment for a table containing the following: module, chunk name, author, old data system behavior start line, new data system start line, and a very brief description of the what is going on in the `if(OLD_DATA_SYSTEM_BEHAVIOR)` blocks of code. 

[oldbehavior_blocks.xlsx](https://github.com/JGCRI/gcamdata/files/1593667/oldbehavior_blocks.xlsx)

**Comment by kdorheim** [comment]
FYI on 5/1 I tried running `OLD_DATA_SYSTEM_BEHAVIOR <- FALSE` and the driver broke at `module_aglu_LA107.an_IMAGE_R_C_Sys_Fd_Y`

**Comment by kvcalvin** [comment]
This has been completed.
