### ISSUE TITLE
Is CONV_BBLD_EJYR correct?

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#864]
In `constants.R` we have:
```R
CONV_BBLD_EJYR <- 6.119 * 365.25 * 1e-3 # billion barrels a day to EJ per year
```

Matthew B. points out that the level 0 files are in million barrels/day, and that's what this number corresponds to, so the comment is wrong. @d3y419 @pkyle OK to change?

**Comment by pkyle** [comment]
Ha, oops! Yeah of course please rename it and change the comment.
And if you ever say anything about it I'll hit you with a $10 million lawsuit ;)

**Comment by bpbond** [comment]
Cool, thanks.
