### ISSUE TITLE
Zenodo archive & DOI

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#866]

**Comment by rplzzz** [comment]
I can flip the switch on this one if you want me to, but I'll wait for you to ok it, in case you've got something else you want to do first (note that even once the switch is flipped, it won't trigger until you draft a release)

**Comment by bpbond** [comment]
@rplzzz We're almost ready to do this. Kalyn has a couple more things to do, then I have some technical cleanup including git bfg (#489 ). Are you still willing to do this after that, say next week? Thanks.

**Comment by rplzzz** [comment]
Done.
