### ISSUE TITLE
FAO Ag Production Sugar Mismatches

### ISSUE THREAD

**Issue by abigailsnyder** [JGCRI/gcamdata#878]
@swaldhoff  found a possible issue with FAO sugar-related crops in Colombia around 2005-2010. It could very possibly be an issue in other places and years. Hard to tell if isolated and we can ignore because  calibration or if it's affecting calibration of other quantities. 

@swaldhoff can give more details. We think it's related to my PR https://github.com/JGCRI/gcamdata/pull/441

We think it has to do with underlying FAO data mismatches over the code, but it could be the code too.

**Comment by abigailsnyder** [comment]
or to do with

**Comment by swaldhoff** [comment]
Scratch all this! I figured out the problem. I was looking at the LAMP runs which use the regional ag markets. The 1990 and 2005 data aren't correct in those runs! Sorry for this. (At least it's solved.)
