### ISSUE TITLE
Fix water module xmls

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/gcamdata#880]
As part of #670 we came across two problems with water module xml files.
1. The new data system is missing `electricity_water.xml`
2. There are discrepancies in `water_demand_municipal.xml`
[fix_water_xml_materials.zip]

Please see the attached zip file for the following, 

- a pdf summarizing the water-xml problems and relevant data system chunk information
-  the old and new xml files that fail the xml test
- a txt file of the complete xml test output 

(https://github.com/JGCRI/gcamdata/files/1811475/fix_water_xml_materials.zip)

**Comment by skim301** [comment]
# join up all the assumptions into a single tibble and expand for all regions
    A45.sector %>%
      left_join_error_no_match(A45.tech_cost, by = "supplysector") %>%
      bind_cols(A45.demand) %>%
      mutate(logit.year.fillout = MODEL_YEARS[1]) %>%
      repeat_add_columns(GCAM_region_names) %>%
      mutate(logit.type = NA) ->
      L245.assumptions_all

**Comment by kdorheim** [comment]
Closed by #907
