### ISSUE TITLE
AGLU xmls missing code in new data system 

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/gcamdata#893]
There are 30 aglu xmls that are not created in the new data system because the new data system is missing the create_xml code in the new data system. @bpbond can you add template code for the following?

#### L201.ag_For_Past_bio_input.R   (old data system) 
* ag_For_Past_bio_base.xml

#### L203.demand_input.R
* food_SSP1.xml
* food_SSP2.xml
* food_SSP3.xml
* food_SSP4.xml
* food_SSP5.xml

#### L204.rebio_input.R
* resbio_input.xml

#### L205.ag_prodchange_cost_input.R 
* ag_prodchange_ssp1.xml
* ag_prodchange_ssp2.xml
* ag_prodchange_ssp4.xml
* ag_prodchange_ssp3.xml
* ag_prodchange_ssp5.xml
* ag_prodchange_ref.xml
* ag_cost.xml

#### L206.ag_Fert.R
* ag_Fert.xml

#### L2011.ag_For_Past_bio_input.R
* ag_For_Past_bio_base_IRR.xml

#### L2041.resbio_input_irr.R
* resbio_input_IRR.xml

#### L2051.ag_prodchange_cost_input_irr.R
* ag_prodchange_ssp1_IRR.xml
* ag_prodchange_ssp3_IRR.xml
* ag_prodchange_ssp2_IRR.xml
* ag_prodchange_ssp4_IRR.xml
* ag_prodchange_ssp5_IRR.xml
* ag_prodchange_ref_IRR.xml
* ag_cost_IRR.xml

#### L2061.ag_Fert_irr.R
* ag_Fert_IRR.xml

#### L2042.resbio_input_irr_mgmt.R 
* resbio_input_IRR_MGMT.xml

#### L2052.ag_prodchange_cost_irr_mgmt.R 
* ag_cost_IRR_MGMT.xml

#### L2071.ag_water_irr.R
*  ag_water_input_IRR.xml

#### L2072.ag_water_irr_mgmt.R
* ag_water_input_IRR_MGMT.xml

**Comment by bpbond** [comment]
Before I do this, we need input from @kvcalvin and @abigailsnyder , who extensively reworked the aglu system in ways that I (still, shamefully) don't fully get.

**Comment by abigailsnyder** [comment]
At least _some_ of the ag xml's up there are no longer necessary.
For example `L205.agprodchange_ref` is now superceded by `L2052_agprodchange_irr_mgmt_ref` (or whatever the order is). Since we will no longer support running GCAM without irrigation and management info, `L205` doesn't need to be generated. 

So I would say until @kvcalvin can double check, your best bet would be to go through and start looking for a `Lxxx1` or `Lxxx2` version of any `Lxxx` file that seems to be missing.

Also, might need @rynacui for the food demand files, I understand nothing about that.

**Comment by abigailsnyder** [comment]
I should say the `L205` _xml_ doesn't need to be generated. Many of the _csv_ files from `L205` go on to become inputs to `L2051` and `L2052`

**Comment by kvcalvin** [comment]
I have definitely made a list of the obsolete chunks/files before (and I thought I had sent it to Kalyn). I will try to find and re-send.

**Comment by kdorheim** [comment]
@bpbond and @kvcalvin my understanding is that the new data system aglu module should be producing the xmls from @kvcalvin's list #814.  That narrows down xmls missing new data system code to 9 xmls.

@kvcalvin could you confirm that these are required? 
@bpbond if required, could you add the `zchunk_batch` scripts? 

Thanks!

#### L201.ag_For_Past_bio_input.R (old data system)
* ag_For_Past_bio_base.xml

#### L203.demand_input.R
* food_SSP1.xml
* food_SSP2.xml
* food_SSP3.xml
* food_SSP4.xml
* food_SSP5.xml

#### L2042.resbio_input_irr_mgmt.R
* resbio_input_IRR_MGMT.xml

#### L2052.ag_prodchange_cost_irr_mgmt.R
* ag_cost_IRR_MGMT.xml

#### L2072.ag_water_irr_mgmt.R
* ag_water_input_IRR_MGMT.xml

**Comment by abigailsnyder** [comment]
my bad closing/reopening. I hit the wrong button

**Comment by kvcalvin** [comment]
Yes, all of those files are required.

**Comment by bpbond** [comment]
OK, I'll go look and add the relevant files.
