### ISSUE TITLE
module_aglu_L205.ag_prodchange_cost_input_DISABLED

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/gcamdata#914]
The aglu module `module_aglu_L205.ag_prodchange_cost_input_DISABLED ` is currently disabled and untranslated. Is this chunk intentionally being left out of the new data system, if so can we delete it?

**Comment by abigailsnyder** [comment]
I think so but @rynacui  would again be the expert on this one

**Comment by rynacui** [comment]
Both L205 and L2051 are now combined into L2052. So yes, can be deleted.

**Comment by kdorheim** [comment]
@rynacui great thanks!

**Comment by kdorheim** [comment]
This issue was addressed by  #915
