### ISSUE TITLE
Replace comp data with dsr output

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/gcamdata#918]
The numerical instability of the new data system is causing some dsr outputs to fail the old new tests. When the relative and absolute difference between dsr and gcam 5 data system outputs are small we have replaced the comparison data with dsr output, in order to make progress on the version 1 check off. 

When the numerical instability is addressed (in 1.1) the comparison data for the following will need to be replaced.

**Comment by kdorheim** [comment]
### L112.ghg_tgej_R_en_S_F_Yh

```
          dsr_value gcam5_value absolute_diff realtive_diff
min       0.00000000  0.00000000 -3.183100e-13           NaN
mean      0.02581742  0.02581742  4.211565e-19           NaN
max      28.40000000 28.40000000  2.754200e-13           NaN
na_count  0.00000000  0.00000000  0.000000e+00         48513
```

**Comment by bpbond** [comment]
See also #931
