### ISSUE TITLE
small (e-17) diff in L101.in_EJ_R_en_Si_F_Yh causes problem in L111

### ISSUE THREAD

**Issue by rynacui** [JGCRI/gcamdata#933]
There are 23 observations in `L101.in_EJ_R_en_Si_F_Yh` from GCAM5 have very small values (e-20 ~ e-17), while in the DSR output these values are zero. 

`# A tibble: 23 x 8`
 `  GCAM_region_ID          supplysector subsector stub.technology  test xyear       energy          diff`
 `           <int>                 <chr>     <chr>           <chr> <dbl> <chr>        <dbl>         <dbl>`
 `              4 industrial energy use       gas             gas     0 X1979 2.168404e-19 -2.168404e-19`
 `              4 industrial energy use       gas             gas     0 X1980 1.084202e-19 -1.084202e-19`
 `              4 industrial energy use       gas             gas     0 X1983 1.084202e-19 -1.084202e-19`
 `              4 industrial energy use       gas             gas     0 X1985 2.168404e-19 -2.168404e-19`
 `              4 industrial energy use       gas             gas     0 X1987 6.505213e-19 -6.505213e-19`
 `              4 industrial energy use       gas             gas     0 X1989 2.168404e-19 -2.168404e-19`
 `              5 industrial energy use       gas             gas     0 X1971 2.710505e-20 -2.710505e-20`
 `             15 industrial energy use       gas             gas     0 X1977 3.469447e-18 -3.469447e-18`
 `             15 industrial energy use       gas             gas     0 X1978 6.938894e-18 -6.938894e-18`
 `             15 industrial energy use       gas             gas     0 X1988 1.040834e-17 -1.040834e-17`
`# ... with 13 more rows`

This causes problem in #920, `L111.nonghg_tgej_R_en_S_F_Yh` fails old new tests.

**Comment by bpbond** [comment]
Closing, as this was resolved–temporarily–in #935 .
