### ISSUE TITLE
Fix gcam module xml problems

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/gcamdata#944]
As part of #940 we came across a few problems with gcam-usa module xml files. Out of the 15 gcam usa xmls the new data system is missing 0 files and makes 11 files containing discrepancies.

```
15 files tested.
0 missing output files.
11 file discrepancies.
```

[fix_gcamUSA_xml_materials.zip](https://github.com/JGCRI/gcamdata/files/1925697/fix_gcamUSA_xml_materials.zip)
The attachment contains the following,

* `gcam_usa_xml_problems.html`, a html summarizing the gcam-usa-xml problems
* `gcamUSA_rslts.txt`, a txt file of the complete python xml test output
* `gcamUSA_old_new_xmls` a folder containing the xmls with discrepancies from the old and new data systems
* `gcamUSA-xml-processing-code` a folder containing the batch.xmls used to create the xmls with discrepancies in the old data system.

**Comment by kdorheim** [comment]
@gokuliyer this is looking like it might be less work than anticipated, I can take care of it but may ping you for help if I run into any issues.

**Comment by gokuliyer** [comment]
Thanks @kdorheim . I should be able to work on this next week.

**Comment by kdorheim** [comment]
@gokuliyer , okay if you have time that would be great but please check in before you do so, I have already started working on some of the xmls.

**Comment by gokuliyer** [comment]
@kdorheim : I'll check in early next week.
