### ISSUE TITLE
Double check our large file strategy

### ISSUE THREAD

**Issue by pralitp** [JGCRI/gcamdata#962]
Given we are going to clean up the repository history now might be a good time to make sure our strategy for handling large data.  Currently we are zipping them (.gz?).  This means we need to enforce some checks about this policy otherwise are liable to end up with a messy history of zipped and unzipped versions of files.  We were thinking of making this and explicit test: #660 but ran into complications that .gz files have an OS bit in it (which we can work around but is messy).

Now that we have the full version 1 lets take a minute and recalculate the trade off in the current strategy.  Especially when we drop the old/new comparison data.  Does the way git "pack" it's data for storage eliminate some of the benefit?  Would git LFS be a viable option for gcamdata?

**Comment by bpbond** [comment]
It would be good to resolve this. Is there any reason to keep things compressed, finally? `inst/extdata` is currently 70 MB; it's 329 MB with everything uncompressed.

**Comment by bpbond** [comment]
OK, a couple hundred MB doesn't seem crazy, given the benefits we get from less code (don't have to support reading/writing compressed files), dealing with gz header in normalizer, easier for people to inspect files.

**Comment by bpbond** [comment]
Note that the `en_nonOECD.csv` file is 95.5 MB, close to GitHub's 100 MB hard limit; but as it's proprietary we don't push it up anyway.
