### ISSUE TITLE
License info in all files?

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#972]
Chris V. notes:

>One last thing to consider that you may have already addressed…you will want to have your license/disclaimer information represented on each file that contains code.  See the lead info here https://github.com/umatter/RWebData/blob/master/R/JSONtoDataFrame.R as an example that was published in JORS here:  https://openresearchsoftware.metajnl.com/articles/10.5334/jors.201/

**Comment by rplzzz** [comment]
I really hate this practice.  As a developer, this header ends up being just a bunch of useless garbage that I have to scroll through to get to the code that I'm trying to work on.  Is it really necessary, or is it just something everybody does because everybody has always done it?  That is, are there specific bad things that will happen if we don't do it?

**Comment by rplzzz** [comment]
Here's a response to this exact question, from someone who runs a scientific software consulting firm, that claims that it isn't necessary:
https://softwareengineering.stackexchange.com/a/125841

Also, I'm pretty sure the guy who wrote it was a classmate of mine in college.  The internet is weird that way.

**Comment by ssmithClimate** [comment]
FYI - I asked PNNL about this for another open source project, and what they agreed is that we could just put "Copyright 2018 Battelle Memorial Institute” in each code file, and the full license text in a “license.txt” file in the root of the repo along with the standard Battelle disclaimer. (and also referenced in the GitHub readme file ).

That way copyright is asserted in each file (just with one line), and the longer details are available in just one file.

**Comment by bpbond** [comment]
Yay for common sense.

**Comment by bpbond** [comment]
For the record:

```
find ./  -name "*.R" -exec sed -i '' $'1i\\\n # Copyright 2019 Battelle Memorial Institute; see the LICENSE file.\\\n\\\n' {} \;
```
