### ISSUE TITLE
Rearchitect the driver to use drake package?

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#976]
https://github.com/ropensci/drake

This is getting rave reviews in some quarters - "An R-focused pipeline toolkit for reproducibility and high-performance computing"

**Comment by pralitp** [comment]
@bpbond this came up the other day.  I think it would be really great to get this functionality into `master`.  I don't recall where this left off or why we didn't pursue it further.

If you have a chance could you take a look at the branch / try `drake-test` and see what you think?  If you have any qualms about it (increased run-time, the disk space used by the "cache") we could add it as optionals (that's kind of the way I did it my test anyways, by creating a parallel version of driver: `driver_drake()` but if we move forward I would probably refactor some things to avoid code duplication).

Also I would also be happy to chat anytime if you had any questions about it.

**Comment by ouyang363** [comment]
Agree with @pralitp .... just some personal reflection as a user/developer: currently a lot of my daily work involve iteratively modifying a little bit R code, generating xml, doing a small model run, and then figuring out whether my modification makes sense. So it would be really suffering each time to wait for a whole "driver" run to just modify one small xml. On average, there is about 2 hours everyday that one or multiple version of my gcamdata are "driving".
