### ISSUE TITLE
OLDNEW-L244.building_USA needs updating to A44.demand_satiation_mult as well

### ISSUE THREAD

**Issue by pralitp** [JGCRI/gcamdata#979]
It turns out the OLD_DATASYSTEM_BEHAVIOR in L244.building_USA was also masking an error in the assumptions file `gcam-usa/A44.demand_satiation_mult` -- where the multiplier for heating services was set to 1.0.  By definition this value must be > 1.0 and will cause an `abort()` in GCAM when run.

Zarrar and I ran across this when trying to fix this on a development branch we have been working on.  We updated these values to match values @gokuliyer and @pkyle made in their work on GCAM-USA, although I am not sure if ultimately those are the values we wanted to use or not.

**Comment by pralitp** [comment]
FYI, @bpbond and (@russellhz in case you will be working on this version 1.1 fix).

**Comment by zarrarkhan** [comment]
Attaching the updated gcam-usa/A44.demand_satiation_mult file. 
[A44.demand_satiation_mult.csv.zip](https://github.com/JGCRI/gcamdata/files/2091165/A44.demand_satiation_mult.csv.zip)

**Comment by bpbond** [comment]
Thanks you guys. So what's the timing on making this change here in `gcamdata`?

**Comment by gokuliyer** [comment]
@pkyle , I'd leave this one to you.

**Comment by pkyle** [comment]
Not sure why this requires me or anyone else specifically...someone just needs to copy that enclosed file over the existing one, right? Do we need a core model proposal or something?

**Comment by pralitp** [comment]
No, I don't think there is anything to do right now.  Maybe when it comes time to write the proposal we will have to note why we choose the multipliers to be what they were.  We took it from the EPSA branch so I assume we can copy some text from the broader GCAM-USA proposal(s).

**Comment by pralitp** [comment]
This is closed in #986
